### ISSUE TITLE
Certbot exception when renewal not necessary

### ISSUE THREAD

**Issue by kodumbeats** [appwrite/appwrite#1025]
## 🐛 Bug Report

The certificates worker throws an exception when certbot returns a good response: `Exception: Renew isn't required`. So, when a cert has no problems, the docker logs have an exception with stack trace.

## Have you spent some time to check if this issue has been raised before?

Yes.

## To Reproduce

- Install Appwrite 0.7.2 with the domain configured in advance
- `docker-compose restart`
- `docker-compose logs appwrite-worker-certificates`

## Expected behavior

Message is logged without exception or stack trace.

## Actual Behavior

```bash
$ docker logs appwrite-worker-certificates

Appwrite certificates worker v1 has started
[notice] Starting worker 47da59cba020:7:v1-certificates
[notice] Starting work on (Job{v1-certificates} | ID: 81d8aa96638b454eb84d9dce6a2ea418 | CertificatesV1 | [{"document":[],"domain":"testing.swivi.cloud","validateTarget":false,"validateCNAME":false}])
[notice] (Job{v1-certificates} | ID: 81d8aa96638b454eb84d9dce6a2ea418 | CertificatesV1 | [{"document":[],"domain":"testing.swivi.cloud","validateTarget":false,"validateCNAME":false}]) has finished

$ docker-compose restart; docker logs appwrite-worker-certificates

Appwrite certificates worker v1 has started
[notice] Starting worker 47da59cba020:8:v1-certificates
[notice] Starting work on (Job{v1-certificates} | ID: 6843f26478964bc77f3495aee2c7ce71 | CertificatesV1 | [{"document":[],"domain":"testing.swivi.cloud","validateTarget":false,"validateCNAME":false}])
[critical] (Job{v1-certificates} | ID: 6843f26478964bc77f3495aee2c7ce71 | CertificatesV1 | [{"document":[],"domain":"testing.swivi.cloud","validateTarget":false,"validateCNAME":false}]) has failed Exception: Renew isn't required in /usr/src/code/app/workers/certificates.php:109
Stack trace:
#0 /usr/src/code/vendor/resque/php-resque/lib/Resque/Job.php(201): CertificatesV1->perform()
#1 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(303): Resque_Job->perform()
#2 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(242): Resque_Worker->perform(Object(Resque_Job))
#3 /usr/src/code/vendor/resque/php-resque/bin/resque(185): Resque_Worker->work(5, false)
#4 {main}
```

## Your Environment

Appwrite 0.7.2 on Ubuntu 20.04 LTS

**Comment by kodumbeats** [comment]
We move the certificates to a mounted volume here:
https://github.com/appwrite/appwrite/blob/master/app/workers/certificates.php#L139

Certbot _really_ doesn't like when certs are moved around - this warning can be found in every README in `/etc/letsencrypt`:
```text
WARNING: DO NOT MOVE OR RENAME THESE FILES!
         Certbot expects these files to remain in this location in order
         to function properly!

We recommend not moving these files. For more information, see the Certbot
User Guide at https://certbot.eff.org/docs/using.html#where-are-my-certificates.
```

Because the certs are moved, I can't add extra `certbot` logic to check the renew dates on the certificates in use. Any thoughts on how to elegantly handle this @eldadfux ?

**Comment by YoogottamK** [comment]
Setting the `--config-dir` flag while running `certbot` might help.

```sh
$ certbot -h paths
paths:
  Flags for changing execution paths & servers
.
.
  --config-dir CONFIG_DIR
                        Configuration directory. (default: /etc/letsencrypt)
.
.
```

Instead of moving the certificates, we can ask `certbot` to directly place them there.
I'll try this out soon and see if it works.

**Comment by eldadfux** [comment]
> Setting the `--config-dir` flag while running `certbot` might help.
> 
> ```shell
> $ certbot -h paths
> paths:
>   Flags for changing execution paths & servers
> .
> .
>   --config-dir CONFIG_DIR
>                         Configuration directory. (default: /etc/letsencrypt)
> .
> .
> ```
> 
> Instead of moving the certificates, we can ask `certbot` to directly place them there.
> I'll try this out soon and see if it works.

@kodumbeats this can be a nice idea, please let me know if I can help.

**Comment by eldadfux** [comment]
Stale issue, closing down
