### ISSUE TITLE
Long function processing time if there are other functions being triggered by the same event

### ISSUE THREAD

**Issue by TafadzwaD** [appwrite/appwrite#1100]
## 🐛 Bug Report

Long function processing time if there are other functions being triggered by the same event

## Have you spent some time to check if this issue has been raised before?

(Have you googled for a similar issue or checked our older issues for a similar bug)

## Detailed Explanation

I have three functions which are triggered by the same event (usercreate and accountcreate). The event triggers the first functions and the processing time is more than 28. Sometimes the function will remain in processing state.Then the third function is not being triggered.

## My Environment

(AppWrite v:0.7.2.145, Ubuntu 20.04 )

## LogFile
``` [notice] Starting work on (Job{v1-functions} | ID: 320954a6e5f94c7d0ab16095897b31f0 | FunctionsV1 | [{"projectId":"60651a88d61ea","userId":"admin-60651a6fcda7b","event":"users.create","payload":{"$id":"607ff42ee558c","name":"jhguig hgjkf","registration":1618998318,"status":0,"email":"testers@gmail.com","emailVerification":false,"prefs":[]},"functionId":null,"executionId":null,"trigger":"event"}])
Fetched 3 functions...
Itterating function: All Users Listing
Triggered function: users.create
[critical] (Job{v1-functions} | ID: 320954a6e5f94c7d0ab16095897b31f0 | FunctionsV1 | [{"projectId":"60651a88d61ea","userId":"admin-60651a6fcda7b","event":"users.create","payload":{"$id":"607ff42ee558c","name":"jhguig hgjkf","registration":1618998318,"status":0,"email":"testers@gmail.com","emailVerification":false,"prefs":[]},"functionId":null,"executionId":null,"trigger":"event"}]) has failed Exception: Failed to create function environment: docker: Error response from daemon: Conflict. The container name "/appwrite-function-606f9ef0eeff4" is already in use by container "5442a74ec9564c7a85a8e747b8a0e2e340eb2efc169c5756f420ba8d44c073d2". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
 in /usr/src/code/app/workers/functions.php:422
Stack trace:
#0 /usr/src/code/app/workers/functions.php(198): FunctionsV1->execute('event', '60651a88d61ea', '', Object(Appwrite\Database\Database), Object(Appwrite\Database\Document), 'users.create', '{"$id":"607ff42...')
#1 /usr/src/code/vendor/resque/php-resque/lib/Resque/Job.php(201): FunctionsV1->perform()
#2 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(303): Resque_Job->perform()
#3 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(242): Resque_Worker->perform(Object(Resque_Job))
#4 /usr/src/code/vendor/resque/php-resque/bin/resque(185): Resque_Worker->work(5, false)
#5 {main}
[notice] Starting work on (Job{v1-functions} | ID: c2e72d199bd4c61f479d21430a3b2d5b | FunctionsV1 | [{"projectId":"60651a88d61ea","functionId":"607fed14e02b6","executionId":"607ff565a6961","trigger":"http"}])
Function created in 2.6253430843353 seconds with exit code 0
Function executed in 0.5060019493103 seconds with exit code 1
11 running containers counted
Starting containers cleanup
Removed container: appwrite-function-607fed442bf0e
[notice] (Job{v1-functions} | ID: c2e72d199bd4c61f479d21430a3b2d5b | FunctionsV1 | [{"projectId":"60651a88d61ea","functionId":"607fed14e02b6","executionId":"607ff565a6961","trigger":"http"}]) has finished
```

![Screenshot from 2021-04-21 12-27-29](https://user-images.githubusercontent.com/28431370/115539597-74519180-a29d-11eb-8042-3b30d8a15a43.png)

**Comment by TorstenDittmann** [comment]
This is fixed now with the new functions service 👏🏻

**Comment by TafadzwaD** [comment]
Much appreciated👏👏

**Comment by lohanidamodar** [comment]
@TorstenDittmann should we close this?
