### ISSUE TITLE
500 Status Code Error on running

### ISSUE THREAD

**Issue by Yash-Singh1** [appwrite/appwrite#2130]
I'm trying to run this on Heroku and I am getting the following error:

```console
2021-10-08T00:09:47.140428+00:00 heroku[router]: at=info method=GET path="/" host=appwrite-heroku.herokuapp.com request_id=0944c693-65fd-42d0-9b18-e51e2074219f fwd="73.70.191.190" dyno=web.1 connect=0ms service=17ms status=500 bytes=166 protocol=https
2021-10-08T00:09:47.138988+00:00 app[web.1]: 
2021-10-08T00:09:47.139005+00:00 app[web.1]: Fatal error: Uncaught PDOException: PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name does not resolve in @swoole-src/library/core/Database/PDOPool.php:44
2021-10-08T00:09:47.139005+00:00 app[web.1]: Stack trace:
2021-10-08T00:09:47.139008+00:00 app[web.1]: #0 @swoole-src/library/core/Database/PDOPool.php(44): PDO->__construct('mysql:host=mari...', 'root', 'password', Array)
2021-10-08T00:09:47.139008+00:00 app[web.1]: #1 @swoole-src/library/core/Database/PDOProxy.php(41): Swoole\Database\PDOPool->Swoole\Database\{closure}()
2021-10-08T00:09:47.139008+00:00 app[web.1]: #2 @swoole-src/library/core/ConnectionPool.php(89): Swoole\Database\PDOProxy->__construct(Object(Closure))
2021-10-08T00:09:47.139009+00:00 app[web.1]: #3 @swoole-src/library/core/ConnectionPool.php(58): Swoole\ConnectionPool->make()
2021-10-08T00:09:47.139010+00:00 app[web.1]: #4 /usr/src/code/app/http.php(80): Swoole\ConnectionPool->get()
2021-10-08T00:09:47.139010+00:00 app[web.1]: #5 {main}
2021-10-08T00:09:47.139010+00:00 app[web.1]: 
2021-10-08T00:09:47.139011+00:00 app[web.1]: Next PDOException: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name does not resolve in @swoole-src/library/core/Database/PDOPool.php:44
2021-10-08T00:09:47.139011+00:00 app[web.1]: Stack trace:
2021-10-08T00:09:47.139011+00:00 app[web.1]: #0 @swoole-src/library/core/Database/PDOPool.php(44): PDO->__construct('mysql:host=mari...', 'root', 'password', Array)
2021-10-08T00:09:47.139012+00:00 app[web.1]: #1 @swoole-src/library/core/Database/PDOProxy.php(41): Swoole\Database\PDOPool->Swoole\Database\{closure}()
2021-10-08T00:09:47.139012+00:00 app[web.1]: #2 @swoole-src/library/core/ConnectionPool.php(89): Swoole\Database\PDOProxy->__construct(Object(Closure))
2021-10-08T00:09:47.139012+00:00 app[web.1]: #3 @swoole-src/library/core/ConnectionPool.php(58): Swoole\ConnectionPool->make()
2021-10-08T00:09:47.139012+00:00 app[web.1]: #4 /usr/src/code/app/http.php(80): Swoole\ConnectionPool->get()
2021-10-08T00:09:47.139012+00:00 app[web.1]: #5 {main}
2021-10-08T00:09:47.139013+00:00 app[web.1]: thrown in @swoole-src/library/core/Database/PDOPool.php on line 44
2021-10-08T00:09:47.142280+00:00 app[web.1]: Worker 1 started succefully
```

What am I doing wrong?

**Update:**

I made Heroku clone the repository and run the DockerFile.

**Comment by MichalMaciejKowal** [comment]
You have provided the host for the database that cannot be resolved i.e. to the correct IP address (by the DNS).
