### ISSUE TITLE
🐛 Bug Report: REST API doesn't work when code executed in Appwrite Console

### ISSUE THREAD

**Issue by oliver-pham** [appwrite/appwrite#2245]
### 👟 Reproduction steps

I used the code from [Ruby playground](https://github.com/appwrite/playground-for-ruby). The code works when executed from the terminal. However, I got an error while running it in Appwrite console as a cloud function.

1. Execute the command below in `playground-for-ruby` directory:
```
docker run --rm -v $(pwd):/app -w /app --env GEM_HOME=./.appwrite appwrite/env-ruby-2.7:1.0.2 bundle install
```
2. Move `playground.rb` in `lib/` folder to the root folder for convenient code execution
3.
```
cd ..
tar -zcvf playground.tar.gz playground-for-ruby
```
4. Add Function > Settings
5. Deploy Tag > Create:
- Set "Command" to "ruby playground.rb"
- Upload `playground.tar.gz`
6. Set environment variables (`APPWRITE_PROJECT_ID`, `APPWRITE_ENDPOINT`, and `APPWRITE_API_KEY`) in Settings
5. Execute Now

### 👍 Expected behavior

The code should be executed successfully.

### 👎 Actual Behavior

I got this error from "STDERR"
```
/usr/local/src/.appwrite/gems/appwrite-2.4.0/lib/appwrite/exception.rb:6:in `initialize': wrong number of arguments (given 1, expected 3) (ArgumentError)
	from /usr/local/src/.appwrite/gems/appwrite-2.4.0/lib/appwrite/client.rb:98:in `new'
	from /usr/local/src/.appwrite/gems/appwrite-2.4.0/lib/appwrite/client.rb:98:in `rescue in fetch'
	from /usr/local/src/.appwrite/gems/appwrite-2.4.0/lib/appwrite/client.rb:95:in `fetch'
W	from /usr/local/src/.appwrite/gems/appwrite-2.4.0/lib/appwrite/client.rb:67:in `call'
	from /usr/local/src/.appwrite/gems/appwrite-2.4.0/lib/appwrite/services/database.rb:67:in `create_collection'
	from playground.rb:23:in `create_collection'
	from playground.rb:92:in `<main>'
/usr/local/lib/ruby/3.0.0/net/http.rb:987:in `initialize': Failed to open TCP connection to localhost:80 (Address not available - connect(2) for "localhost" port 80) (Errno::EADDRNOTAVAIL)
	from /usr/local/lib/ruby/3.0.0/net/http.rb:987:in `open'
	from /usr/local/lib/ruby/3.0.0/net/http.rb:987:in `block in connect'
½	from /usr/local/lib/ruby/3.0.0/timeout.rb:97:in `block in timeout'
	from /usr/local/lib/ruby/3.0.0/timeout.rb:107:in `timeout'
	from /usr/local/lib/ruby/3.0.0/net/http.rb:985:in `connect'
>	from /usr/local/lib/ruby/3.0.0/net/http.rb:970:in `do_start'
	from /usr/local/lib/ruby/3.0.0/net/http.rb:959:in `start'
>	from /usr/local/lib/ruby/3.0.0/net/http.rb:1512:in `request'
	from /usr/local/lib/ruby/3.0.0/net/http.rb:1492:in `send_request'
	from /usr/local/src/.appwrite/gems/appwrite-2.4.0/lib/appwrite/client.rb:96:in `fetch'
	from /usr/local/src/.appwrite/gems/appwrite-2.4.0/lib/appwrite/client.rb:67:in `call'
	from /usr/local/src/.appwrite/gems/appwrite-2.4.0/lib/appwrite/services/database.rb:67:in `create_collection'
	from playground.rb:23:in `create_collection'
#	from playground.rb:92:in `<main>'
9/usr/local/lib/ruby/3.0.0/net/http.rb:987:in `initialize': Address not available - connect(2) for "localhost" port 80 (Errno::EADDRNOTAVAIL)
	from /usr/local/lib/ruby/3.0.0/net/http.rb:987:in `open'
	from /usr/local/lib/ruby/3.0.0/net/http.rb:987:in `block in connect'
	from /usr/local/lib/ruby/3.0.0/timeout.rb:97:in `block in timeout'
	from /usr/local/lib/ruby/3.0.0/timeout.rb:107:in `timeout'
	from /usr/local/lib/ruby/3.0.0/net/http.rb:985:in `connect'
	from /usr/local/lib/ruby/3.0.0/net/http.rb:970:in `do_start'
	from /usr/local/lib/ruby/3.0.0/net/http.rb:959:in `start'
	from /usr/local/lib/ruby/3.0.0/net/http.rb:1512:in `request'
	from /usr/local/lib/ruby/3.0.0/net/http.rb:1492:in `send_request'
	from /usr/local/src/.appwrite/gems/appwrite-2.4.0/lib/appwrite/client.rb:96:in `fetch'
	from /usr/local/src/.appwrite/gems/appwrite-2.4.0/lib/appwrite/client.rb:67:in `call'
À	from /usr/local/src/.appwrite/gems/appwrite-2.4.0/lib/appwrite/services/database.rb:67:in `create_collection'
	from playground.rb:23:in `create_collection'
	from playground.rb:92:in `<main>'
```

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by EduardoWeber** [comment]
Hey @oliver-pham ! _I may be wrong_ but looks like the localhost from the appwrite-function container is not the same as the appwrite's localhost. So it fails trying to connect to AppWrite's server as your log suggests:
`initialize': Failed to open TCP connection to localhost:80 (Address not available - connect(2) for "localhost" port 80) (Errno::EADDRNOTAVAIL)`

If you update the `APPWRITE_ENDPOINT` variable changing from localhost to your local IP it should work.
