### ISSUE TITLE
appwrite-worker-functions container crashes

### ISSUE THREAD

**Issue by networkandcode** [appwrite/appwrite#2246]
Hi

I see this error in the appwriter-worker-functions container... How to fix please.

```
Failed to Warmup Node.js 15.5!
Failed to Warmup Node.js 16.0!
Finished warmup in 0.0054612159729004 seconds

Fatal error: Uncaught Utopia\Orchestration\Exception\Orchestration in /usr/src/code/vendor/utopia-php/orchestration/src/Orchestration/Adapter/DockerAPI.php:226
Stack trace:
#0 /usr/src/code/vendor/utopia-php/orchestration/src/Orchestration/Orchestration.php(101): Utopia\Orchestration\Adapter\DockerAPI->list(Array)
#1 /usr/src/code/app/workers/functions.php(71): Utopia\Orchestration\Orchestration->list(Array)
#2 /usr/src/code/vendor/resque/php-resque/bin/resque(67): require_once('/usr/src/code/a...')
#3 {main}
  thrown in /usr/src/code/vendor/utopia-php/orchestration/src/Orchestration/Adapter/DockerAPI.php on line 226Failed to Warmup Node.js 15.5!
```

**Comment by eldadfux** [comment]
What is the output for `docker-compose exec appwrite doctor`?

**Comment by networkandcode** [comment]
This the pod log
```
$ kubectl logs appwrite-worker-functions-577447c6b5-bnmrc -n appwrite
Appwrite functions worker v1 has started
Warming up Java 11.0 environment...
Failed to Warmup Java 11.0!
Warming up Java 16.0 environment...
Failed to Warmup Java 16.0!
Warming up .NET 3.1 environment...
Failed to Warmup .NET 3.1!
Warming up .NET 5.0 environment...
Failed to Warmup .NET 5.0!
Warming up Dart 2.10 environment...
Failed to Warmup Dart 2.10!
Warming up Dart 2.12 environment...
Failed to Warmup Dart 2.12!
Warming up Dart 2.13 environment...
Warming up Deno 1.8 environment...
Warming up Python 3.8 environment...
Failed to Warmup Dart 2.13!
Failed to Warmup Deno 1.8!
Failed to Warmup Python 3.8!
Warming up Python 3.9 environment...
Failed to Warmup Python 3.9!
Warming up Ruby 2.7 environment...
Warming up Ruby 3.0 environment...
Failed to Warmup Ruby 2.7!
Failed to Warmup Ruby 3.0!
Warming up PHP 7.4 environment...
Failed to Warmup PHP 7.4!
Warming up PHP 8.0 environment...
Warming up Node.js 14.5 environment...
Failed to Warmup PHP 8.0!
Failed to Warmup Node.js 14.5!
Warming up Node.js 15.5 environment...
Failed to Warmup Node.js 15.5!
Warming up Node.js 16.0 environment...
Failed to Warmup Node.js 16.0!
Finished warmup in 0.0061218738555908 seconds

Fatal error: Uncaught Utopia\Orchestration\Exception\Orchestration in /usr/src/code/vendor/utopia-php/orchestration/src/Orchestration/Adapter/DockerAPI.php:226
Stack trace:
#0 /usr/src/code/vendor/utopia-php/orchestration/src/Orchestration/Orchestration.php(101): Utopia\Orchestration\Adapter\DockerAPI->list(Array)
#1 /usr/src/code/app/workers/functions.php(71): Utopia\Orchestration\Orchestration->list(Array)
#2 /usr/src/code/vendor/resque/php-resque/bin/resque(67): require_once('/usr/src/code/a...')
#3 {main}
  thrown in /usr/src/code/vendor/utopia-php/orchestration/src/Orchestration/Adapter/DockerAPI.php on line 226
```

**Comment by erfanh3h** [comment]
pull this link
docker pull appwrite/runtime-for-node:16.0
then restart your appwrite.this fix me in python.
