### ISSUE TITLE
🐛 Bug Report: Fresh docker image fails to start - v0.12.1

### ISSUE THREAD

**Issue by Swinkid** [appwrite/appwrite#2670]
### 👟 Reproduction steps

When I execute the docker install command from Appwrite.io, the Appwrite container continuously restarts and throws an error.

### 👍 Expected behavior

Docker containers should start correctly.

### 👎 Actual Behavior

Appwrite container errors and restarts with the following:
`Setup] - Server database init started...

[Setup] - Creating metadata table: appwrite...

Worker 1 started successfully

[Setup] - Skip: metadata table already exists

[Setup] - Creating collection: users...

Fatal error: Uncaught PDOException: Duplicate key name '_index2' in @swoole-src/library/core/Database/PDOStatementProxy.php:64

Stack trace:

#0 /usr/src/code/vendor/utopia-php/database/src/Database/Adapter/MariaDB.php(274): Swoole\Database\PDOStatementProxy->__call('execute', Array)

#1 /usr/src/code/vendor/utopia-php/database/src/Database/Adapter/MariaDB.php(177): Utopia\Database\Adapter\MariaDB->createIndex('users', '_index2', 'fulltext', Array, Array, Array)

#2 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(324): Utopia\Database\Adapter\MariaDB->createCollection('users', Array, Array)

#3 /usr/src/code/app/http.php(143): Utopia\Database\Database->createCollection('users', Array, Array)

#4 {main}

  thrown in @swoole-src/library/core/Database/PDOStatementProxy.php on line 64

[2022-01-22 21:58:16 #1.1] ERROR php_swoole_server_rshutdown() (ERRNO 503): Fatal error: Uncaught PDOException: Duplicate key name '_index2' in @swoole-src/library/core/Database/PDOStatementProxy.php:64

Stack trace:

#0 /usr/src/code/vendor/utopia-php/database/src/Database/Adapter/MariaDB.php(274): Swoole\Database\PDOStatementProxy->__call('execute', Array)

#1 /usr/src/code/vendor/utopia-php/database/src/Database/Adapter/MariaDB.php(177): Utopia\Database\Adapter\MariaDB->createIndex('users', '_index2', 'fulltext', Array, Array, Array)

#2 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(324): Utopia\Database\Adapter\MariaDB->createCollection('users', Array, Array)

#3 /usr/src/code/app/http.php(143): Utopia\Database\Database->createCollection('users', Array, Array)

#4 {main}

  thrown in @swoole-src/library/core/Database/PDOStatementProxy.php on line 64

`

### 🎲 Appwrite version

Version 0.12.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

Fresh install of Docker and Appwrite images.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Swinkid** [comment]
Found rouge docker-compose backup causing issues
