### ISSUE TITLE
🐛 Bug Report: unknown attribute error despite the attribute being avaliable

### ISSUE THREAD

**Issue by lost-RD** [appwrite/appwrite#2815]
### 👟 Reproduction steps

I created a collection. I added attributes to it. I then added another attribute to it, specifically a bool named privacy_policy, a few minutes later.

I then attempted to create a document using the SDK.

### 👍 Expected behavior

I expected the document to be created.

I have verified that the attribute exists by querying the API:

```
{
	"sum": 17,
	"attributes": [
		{
...
		{
			"key": "privacy_policy",
			"type": "boolean",
			"status": "available",
			"required": false,
			"array": false,
			"default": false
		}
	]
}
```
I also verified that I was sending valid data to the right attribute name:
```
{
  privacy_policy: true,
...
}
```

### 👎 Actual Behavior

This error occurred:

```
AppwriteException [Error]: Invalid document structure: Unknown attribute: "privacy_policy"
    at Client.call (/home/xxx/yyy/03-webhooks/node_modules/node-appwrite/lib/client.js:160:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 400,
  response: {
    message: 'Invalid document structure: Unknown attribute: "privacy_policy"',
    code: 400,
    version: '0.12.1'
  }
}
```

### 🎲 Appwrite version

Version 0.12.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Pretty standard, Debian running Appwrite in Docker.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by lost-RD** [comment]
Disregard, I am a dumbass. Wrong collection ID supplied.
