### ISSUE TITLE
🐛 Bug Report: Delete a document does not trigger `database.documents.delete` event

### ISSUE THREAD

**Issue by gepd** [appwrite/appwrite#3028]
### 👟 Reproduction steps

1. create a function with this options:

```
{
            "$id": "remove",
            "name": "remove",
            "runtime": "node-16.0",
            "path": "remove",
            "entrypoint": "src/index.js",
            "execute": [],
            "events": [
                "database.documents.delete"
            ],
            "schedule": "",
            "timeout": 15
        }
```

2. Delete a document
3. See the logs in the function

### 👍 Expected behavior

The function should be trigger when a document is deleted

### 👎 Actual Behavior

I don't see any record in the function logs (console)

When I run `docker logs appwrite-worker-functions` I see this error:

```
...has failed Exception: Deployment not found. Create deployment before trying to execute a function in /usr/src/code/app/workers/functions.php:217
Stack trace:
#0 /usr/src/code/app/workers/functions.php(84): FunctionsV1->execute('6147b8cbd33ad', Object(Utopia\Database\Document), Object(Utopia\Database\Database), '', Array, 'event', 'database.docume...', '{"name":"hee","...', '', '6147b89390975', '')
#1 /usr/src/code/src/Appwrite/Resque/Worker.php(110): FunctionsV1->run()
#2 /usr/src/code/vendor/resque/php-resque/lib/Resque/Job.php(201): Appwrite\Resque\Worker->perform()
#3 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(303): Resque_Job->perform()
#4 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(242): Resque_Worker->perform(Object(Resque_Job))
#5 /usr/src/code/vendor/resque/php-resque/bin/resque(185): Resque_Worker->work('0.1', false)
#6 {main}
```

If I manually run the function ("Execute Now" Button) I can see the record in console log

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by gepd** [comment]
I'll close this issue as after remove the function and rename it, it started to work
