### ISSUE TITLE
🐛 Bug Report: Cloud Function not able to find environment variables

### ISSUE THREAD

**Issue by hey-nicolasklein** [appwrite/appwrite#3226]
### 👟 Reproduction steps

* Creating a new cloud function with the appwrite cli
* Add any sdk call to the function like for example ` var files = await database.listDocuments('mediaItems');`

Here is the function:

````

const sdk = require("node-appwrite");

module.exports = async function (req, res) {
  const client = new sdk.Client();

  // You can remove services you don't use
  let account = new sdk.Account(client);
  let avatars = new sdk.Avatars(client);
  let database = new sdk.Database(client);
  let functions = new sdk.Functions(client);
  let health = new sdk.Health(client);
  let locale = new sdk.Locale(client);
  let storage = new sdk.Storage(client);
  let teams = new sdk.Teams(client);
  let users = new sdk.Users(client);

  if (
    !req.env['APPWRITE_FUNCTION_ENDPOINT'] ||
    !req.env['APPWRITE_FUNCTION_API_KEY']
  ) {
    console.warn("Environment variables are not set. Function cannot use Appwrite SDK.");
  } else {
    client
      .setEndpoint(req.env['APPWRITE_FUNCTION_ENDPOINT'])
      .setProject(req.env['APPWRITE_FUNCTION_PROJECT_ID'])
      .setKey(req.env['APPWRITE_FUNCTION_API_KEY'])
      .setSelfSigned(true);
  }

  var files = await database.listDocuments('mediaItems');

  res.json({
    areDevelopersAwesome: true,
  });
};

````

### 👍 Expected behavior

The function executes and uses env variables set by appwrite to authenticate, which are used in the preset generated by `appwrite init function`.

### 👎 Actual Behavior

The following error is listed in the logs:

```
Error: getaddrinfo ENOTFOUND hostname
    at Client.call (/usr/code-start/node_modules/node-appwrite/lib/client.js:168:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Database.listDocuments (/usr/code-start/node_modules/node-appwrite/lib/services/database.js:792:16)
    at async module.exports (/usr/code-start/src/index.js:43:15)
    at async /usr/local/src/server.js:38:13
```

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

Locally hosted using docker

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by radvansky-tomas** [comment]
Nothing to apologise, had some issue. This should be in documentation OR even better, NOT required. server knows localhost, this is local function. I dont really understand the need for endpoint at all

**Comment by mrdiin** [comment]
@hey-nicolasklein Sorry to bring this up again, but I tried exactly what you're saying you did. Did you set it just as the machine address or you added the /v1? I tried both to no luck btw. Thanks.

**Comment by stnguyen90** [comment]
@mrdiin, please make sure your endpoint is set the the machine IP or domain with the /v1 like `https://1.1.1.1/v1`. Double check to make sure `client.setEndpoint()` is called with the right value.

**Comment by mrdiin** [comment]
Hi @stnguyen90 I did that but now this error comes up: 
```html
<html>
<body>
<!--StartFragment-->

An internal curl error has occurred within the executor! Error Msg: Operation timed out
--
 

<br class="Apple-interchange-newline"><!--EndFragment-->
</body>
</html>
```

**Comment by stnguyen90** [comment]
@mrd it might be easier to troubleshoot over [discord](https://appwrite.io/discord).

**Comment by DEADSEC-SECURITY** [comment]
Actually would be interesting if appwrite would pass these env vars automatically. We need them if we are using services regardless so might as well have the appwrite server do the work.
