### ISSUE TITLE
🐛 Bug Report: NOAUTH Authentication RedisException thrown

### ISSUE THREAD

**Issue by rome2o** [appwrite/appwrite#3309]
I've been working on adding possibility of Procfile based deployments so one could deploy to Heroku or Dokku keeping in mind the entrypoints for all required containers e.g. worker-deletes and so fourth.

Ultimately, the Procfile should look like following

```
web: php -e app/http.php -dopcache.preload=opcache.preload=/usr/src/code/app/preload.php
worker-functions: . worker-functions
worker-audits: ...
worker-deletes: ...
```

Before I jumped into spinning those containers up, I thought to **run deployment through Dockerfile** on my Dokku server.

Initially I was getting the following error:

```
ERROR   php_swoole_server_rshutdown() (ERRNO 503): Fatal error: Uncaught Exception: Failed to connect to database: SQLSTATE[HY000] [2002] Connection refused in /usr/src/code/app/http.php:75
```

After fiddling around, I found out that the error shown is wrong. **Redis credentials had issues, not database**. I happen to proceed connecting database successfully.

The next roadblock is the following.

```
       Fatal error: Uncaught RedisException: NOAUTH Authentication required. in /usr/src/code/vendor/utopia-php/cache/src/Cache/Adapter/Redis.php:32
       Stack trace:
       #0 /usr/src/code/vendor/utopia-php/cache/src/Cache/Adapter/Redis.php(32): Redis->get('cache-_console:...')
       #1 /usr/src/code/vendor/utopia-php/cache/src/Cache/Cache.php(47): Utopia\Cache\Adapter\Redis->load('cache-_console:...', 86400)
       #2 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(761): Utopia\Cache\Cache->load('cache-_console:...', 86400)
       #3 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(379): Utopia\Database\Database->getDocument(Object(Utopia\Database\Document), 'audit')
       #4 /usr/src/code/app/http.php(104): Utopia\Database\Database->getCollection('audit')
       #5 {main}
         thrown in /usr/src/code/vendor/utopia-php/cache/src/Cache/Adapter/Redis.php on line 32
       [2022-05-30 08:43:03 #8.4]       ERROR   php_swoole_server_rshutdown() (ERRNO 503): Fatal error: Uncaught RedisException: NOAUTH Authentication required. in /usr/src/code/vendor/utopia-php/cache/src/Cache/Adapter/Redis.php:32
       Stack trace:
       #0 /usr/src/code/vendor/utopia-php/cache/src/Cache/Adapter/Redis.php(32): Redis->get('cache-_console:...')
       #1 /usr/src/code/vendor/utopia-php/cache/src/Cache/Cache.php(47): Utopia\Cache\Adapter\Redis->load('cache-_console:...', 86400)
       #2 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(761): Utopia\Cache\Cache->load('cache-_console:...', 86400)
       #3 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(379): Utopia\Database\Database->getDocument(Object(Utopia\Database\Document), 'audit')
       #4 /usr/src/code/app/http.php(104): Utopia\Database\Database->getCollection('audit')
       #5 {main}
         thrown in /usr/src/code/vendor/utopia-php/cache/src/Cache/Adapter/Redis.php on line 32
```

Could someone please help?

Thanks

### 👟 Reproduction steps
Spin up a Dokku server, assign environment variables or push the application to Heroku with environment variables all setup. 

#### Dokku
```git push dokku master:master```

#### Heroku
```git push heroku master:master```

### 👍 Expected behavior

It should connect to Redis as all the configurations are correct. I've tested it through Medis and TablePlus

### 👎 Actual Behavior

The app crashes upon deployment after the Dockerfile build is succeeded and app is about to release. 

### 🎲 Appwrite version

Version 0.14.x

### 💻 Operating system

Linux

### 🧱 Your Environment

N.A

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
I believe the problem is the [library](https://github.com/chrisboulton/php-resque) Appwrite uses to connect to redis [doesn't properly pass the user to authenticate](https://github.com/chrisboulton/php-resque/blob/968b7e6a307a2079051dfc571d2fc2be0546209f/lib/Resque/Redis.php#L134).

The core team is working on replacing the library with one that will support username and password.

**Comment by usamashafiqs** [comment]
Any update on this ?

**Comment by rome2o** [comment]
For me, this was an issue because the REDIS_URL wasn't being parsed properly in the source code of Appwrite. 

Try putting Redis credentials in a plain format in your .env, and see if it works.

If you wish to debug this, try to print in console the Redis configuration upon boot and see what changes in .env would be required.

Hopefully this would fix your issue.

**Comment by adipriyantobpn** [comment]
possibly _APP_REDIS_PASS and _APP_REDIS_USER are not passed into Dockerfile too?

https://github.com/appwrite/appwrite/blob/master/Dockerfile#L86

**Comment by liudonghua123** [comment]
I have the similar issues when I try to run appwrite using docker compose followed the guidance on https://github.com/appwrite/appwrite?tab=readme-ov-file#unix.

```bash
docker run -it --rm \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --volume "$(pwd)"/appwrite:/usr/src/code/appwrite:rw \
    --entrypoint="install" \
    appwrite/appwrite:1.4.12
```

Details logs: [logs.txt](https://github.com/appwrite/appwrite/files/13734159/logs.txt)

**Comment by aquelegustavo** [comment]
Hello everyone, how are you?

I came across the same issue. I noticed that Redis in docker compose installed via script (https://appwrite.io/docs/advanced/self-hosting#install-with-docker) does not set a password. For security reasons, I added line 823 (screenshot below) so that Redis requires a password for connections.

![image](https://github.com/appwrite/appwrite/assets/36718581/3907fcf3-6d69-455d-b11e-21a4b62e8323)

After making this change, I noticed that the services appwrite and appwrite-task-maintenance are unable to connect to Redis. The appwrite-realtime service seems to be working fine.

In the case of the appwrite container, it is unable to open the console, triggering the following error in the log when accessed through port 80:
![image](https://github.com/appwrite/appwrite/assets/36718581/ca382e14-1236-4bfc-be77-e4ac486c1282)

The appwrite-task-maintenance container throws the following error (a lot of times on terminal):
![image](https://github.com/appwrite/appwrite/assets/36718581/f743cab9-7e5e-4aad-b918-f954f3dabafd)
 
I hope I have contributed to the discussion and at least saved some time for those investigating this issue =)

**Comment by andrekutianski** [comment]
This also affects environments where an external Redis is used that is not defined in the default docker-compose. Appwrite forces you to use a local Redis with this authentication issue.

**Comment by robsoncombr** [comment]
Just found this to avoid duplicates. Redis connection configuration, to me, looks like not to be considering the configured _APP_REDIS_USER / _APP_REDIS_PASS trying to connect without credentials that fails.

**Comment by kodejuice** [comment]
> This also affects environments where an external Redis is used that is not defined in the default docker-compose. Appwrite forces you to use a local Redis with this authentication issue.

Exactly what i'm facing rn
Any solutions?

**Comment by FaisalMohammadi** [comment]
is there any update tot this? i am runnig to the same problem. I have external redis set up and putte the credentials inside .env file and also tried with passing `--requirepass ${_APP_REDIS_PASS}`.

**Comment by bingoku** [comment]
This issue has persisted for several years without resolution.

Upon testing, it was observed that the appwrite-task-maintenance service encounters the NOAUTH Authentication required error whenever Redis is configured with a password. This occurs regardless of whether Redis is running inside the docker-compose environment or externally. If the password requirement is removed from the external Redis instance, the appwrite-task-maintenance service starts without issues.

Additionally, Appwrite currently lacks support for Redis Cluster configurations, which limits scalability options

These limitations suggest that Appwrite’s self-hosted version may not yet be suitable for production environments and might be more appropriate for development or testing purposes. 😂

**Comment by felixlu07** [comment]
@bingoku Encountered something similar as well. Keep getting persistent issues with `attributes` creation where it is perpetually stuck in `pending` state. 

How I troubleshooted was to attempt to create an attribute, then almost immediately run `docker logs appwrite --since=2m` to check the exact error message; I saw --> "NOAUTH Authentication required" errors with Redis in Appwrite 1.6.1". Despite having correct Redis credentials in both .env and docker-compose.yml, the errors continued. 

The fix was to completely remove Redis authentication by clearing the Redis credentials in `.env` (`_APP_REDIS_USER` and `_APP_REDIS_PASS`) and removing the `--requirepass` parameter from `docker-compose.yml`. After restarting with `docker-compose down` && `docker-compose up -d`, I no longer had the attributes stuck in `processing`, and everything worked perfectly. 

I could be wrong, but this seems to suggests a bug in how some Appwrite services handle Redis authentication, which appears to be a recurring issue across versions.

**Comment by keskinonur** [comment]
I came up with the same problem and fix it by suppling like this in the [docker-compose.yml ](https://appwrite.io/install/compose):

```
  redis:
    image: redis:7.2.4-alpine
    container_name: appwrite-redis
    <<: *x-logging
    restart: unless-stopped
    command: >
      redis-server
      --maxmemory            512mb
      --maxmemory-policy     allkeys-lru
      --maxmemory-samples    5
      --requirepass ${_APP_REDIS_PASS}
    networks:
      - appwrite
    environment:
      - REDIS_HOST=${_APP_REDIS_HOST}
      - REDIS_PORT=${_APP_REDIS_PORT}
      - REDIS_PASSWORD=${_APP_REDIS_PASS}
    volumes:
      - appwrite-redis:/data:rw
```

**Comment by kodejuice** [comment]
I fixed this by creating a Redis proxy: https://github.com/kodejuice/redis-proxy/

**Comment by ibaraki-douji** [comment]
i think i found a part of the issue, some part of the app doesn't use the user to start the redis connection : 
https://github.com/appwrite/appwrite/blob/879ba114a32c6241aacd3f7915b4ea3415039e58/app/init/resources.php#L200C1-L213C4
https://github.com/appwrite/appwrite/blob/879ba114a32c6241aacd3f7915b4ea3415039e58/app/worker.php#L67C1-L82C3
https://github.com/appwrite/appwrite/blob/879ba114a32c6241aacd3f7915b4ea3415039e58/app/realtime.php#L232C4-L252C6

and there is apparently others issues as the API container throws NOAUTH even with default password
possible causes :
https://github.com/appwrite/appwrite/blob/879ba114a32c6241aacd3f7915b4ea3415039e58/app/init/registers.php#L363C25-L369C44

**Comment by HarshMN2345** [comment]
Fixed by 86c34b4. Closing this.

**Comment by ibaraki-douji** [comment]
yes, i can also confirm it's resolved, my 2.2.0 instance don't use a redis-proxy anymore and works fine

see :
- https://github.com/appwrite/appwrite/pull/13622
- https://github.com/utopia-php/monorepo/pull/260

**Comment by HarshMN2345** [comment]
> yes, i can also confirm it's resolved, my 2.2.0 instance don't use a redis-proxy anymore and works fine
> 
> see :
> 
> * [fix(redis): honour _APP_REDIS_USER and pass credentials to the queue publisher #13622](https://github.com/appwrite/appwrite/pull/13622)
> * [fix(queue): authenticate Redis connections when credentials are configured utopia-php/monorepo#260](https://github.com/utopia-php/monorepo/pull/260)


Thankss for confirming
