### ISSUE TITLE
🐛 Bug Report: Deployment stuck on 'processing'

### ISSUE THREAD

**Issue by gregfr** [appwrite/appwrite#3388]
### 👟 Reproduction steps

Try to deploy a function, according to the docs

### 👍 Expected behavior

The function should be deployed

### 👎 Actual Behavior

The function stays "processing"

Not sure if it's related, but the log is filled with:
```
appwrite    | [Error] Timestamp: 2022-06-16T15:39:44+00:00
appwrite    | [Error] Method: GET
appwrite    | [Error] URL: /
appwrite    | [Error] Type: Utopia\Exception
appwrite    | [Error] Message: Not Found
appwrite    | [Error] File: /usr/src/code/vendor/utopia-php/framework/src/App.php
appwrite    | [Error] Line: 719
```

I'm completly new to Appwrite and installed it locally to evaluate it.

Thanks in advance

Regards

### 🎲 Appwrite version

Version 0.14.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Docker version 19.03.6

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
Hey there 👋
The error log you provided is fine, it is fired by Appwrite Dashboard when figuring out if you are logged, so it then knows if it should redirect you to your projects, or sign-in page.

Errors regarding failed deployment would most likely be in one of these logs:
```sh
docker-compose logs appwrite-worker-functions
docker-compose logs appwrite-executor
```

Can you spot any problem there?

Also, infinite processing might mean the workers are not running. A simple solution might be to make sure all Appwrite containers are running by doing `docker-compose up -d`. To ensure everything is up, you can do `docker-compose ps`. Then you can redeploy your function and see if deployment gets picked up.

**Comment by gregfr** [comment]
Thanks for your answer.
These two containers are not referenced in my docker-composer.yml file. It's really weird my compose file is VERY different from the one in the documentation... maybe it has been updated recently?

So I changed the one I have with the new one, now I have the login screen and "invalid credentials"... what am I doing wrong?

**Comment by gregfr** [comment]
In the browser console, I see:
```
Failed to load resource: the server responded with a status of 401 (Unauthorized)
code: 401
message: "User (role: guest) missing scope (account)"
type: "general_unauthorized_scope"
version: "0.14.2"
```

**Comment by gregfr** [comment]
Ok after purging the volumes and containers several times, I have the registration screen.

**Comment by gregfr** [comment]
So I've recreated a project and a function. The result is the same ("processing"). In the logs I see:

appwrite-executor:
```
Warming up Node.js 16.0 environment...
Warming up PHP 8.0 environment...
Warming up Ruby 3.0 environment...
Warming up Python 3.9 environment...
Removing orphan runtimes...
Failed to Warmup PHP 8.0!
Failed to Warmup Python 3.9!
Failed to Warmup Ruby 3.0!
Failed to Warmup Node.js 16.0!
```

appwrite-worker-functions:
```
has failed TypeError: Executor\Executor::__construct(): Argument #1 ($endpoint) must be of type string, null given, called in /usr/src/code/app/workers/functions.php on line 36 and defined in /usr/src/code/src/Executor/Executor.php:29
Stack trace:
#0 /usr/src/code/app/workers/functions.php(36): Executor\Executor->__construct(NULL)
#1 /usr/src/code/src/Appwrite/Resque/Worker.php(94): FunctionsV1->init()
#2 /usr/src/code/vendor/resque/php-resque/lib/Resque/Job.php(198): Appwrite\Resque\Worker->setUp()
#3 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(303): Resque_Job->perform()
#4 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(242): Resque_Worker->perform(Object(Resque_Job))
#5 /usr/src/code/vendor/resque/php-resque/bin/resque(185): Resque_Worker->work('0.1', false)
}
```

**Comment by gregfr** [comment]
Not sure if it's related, but pointing my browser to `https://open-runtimes.com` gives `ERR_CONNECTION_REFUSED`

**Comment by stnguyen90** [comment]
How did you install Appwrite? Did you upgrade from an older version?

**Comment by gregfr** [comment]
I tried to follow the documentation: https://appwrite.io/docs/installation#manual

It didn't work the first time, so I cleaned up everything and did it again.

**Comment by gregfr** [comment]
Thanks for your answer.
The compose file is indeed in a folder named `apprwite`. I did:
```
docker-compose down
docker-compose up --remove-orphans
```

So I have a nice bunch of containers:
![image](https://user-images.githubusercontent.com/361582/176132865-8feea80d-6116-4a8b-90e1-0f09c1ea2674.png)

and the network named is as expected:
![image](https://user-images.githubusercontent.com/361582/176133046-b970122e-9ea4-460f-a212-f7001578a4ba.png)

**Comment by gregfr** [comment]
In the logs I found something:

```
appwrite-worker-functions       | [critical] (Job{v1-functions} | ID: 3a295dd41fce2dd087045971ff1d8db2 | FunctionsV1 | [{"project":{"teamId":"62b0267f0cd3696b75fc","name":"Test001","description":"","logo":"","url":"","version":"0.14.2","legalName":"","legalCountry":"","legalState":"","legalCity":"","legalAddress":"","legalTaxId":"","services":[],"auths":{"limit":0,"emailPassword":true,"usersAuthMagicURL":true,"anonymous":true,"invites":true,"JWT":true,"phone":true},"authProviders":[],"platforms":[],"webhooks":[],"keys":[],"domains":[],"search":"62b0267f12ccc2a94119 Test001","$read":["team:62b0267f0cd3696b75fc"],"$write":["team:62b0267f0cd3696b75fc\/developer","team:62b0267f0cd3696b75fc\/owner"],"$id":"62b0267f12ccc2a94119","$internalId":"1","$collection":"projects"},"user":{"name":"hostmaster","email":"hostmaster@argis.fr","status":true,"password":"$2y$08$sr2sHi0l7qYvnCEEctSUSeqdCX8cVmkVdIId1695PvjfYRiNeTUu.","passwordUpdate":1655711293,"prefs":[],"registration":1655711293,"emailVerification":false,"reset":false,"sessions":[{"userId":"62b0263d94fe4a148b7e","provider":"email","providerUid":"hostmaster@argis.fr","providerAccessToken":null,"providerAccessTokenExpiry":null,"providerRefreshToken":null,"secret":"158d600fec9ba71556b372a30cc0bec343a8a79b76f0e7392a86244e01b821c2","expire":1687247293,"userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/102.0.0.0 Safari\/537.36","ip":"192.168.144.1","countryCode":"--","osCode":"LIN","osName":"GNU\/Linux","osVersion":"","clientType":"browser","clientCode":"CH","clientName":"Chrome","clientVersion":"102.0","clientEngine":"Blink","clientEngineVersion":"102.0.0.0","deviceName":"desktop","deviceBrand":"","deviceModel":"","$id":"62b0263daec6de695fbc","$internalId":"1","$read":["user:62b0263d94fe4a148b7e"],"$write":["user:62b0263d94fe4a148b7e"],"$collection":"sessions"},{"userId":"62b0263d94fe4a148b7e","provider":"email","providerUid":"hostmaster@argis.fr","providerAccessToken":null,"providerAccessTokenExpiry":null,"providerRefreshToken":null,"secret":"e154f8f1be55a55f26aedd0f026e6168930a64b9ca86e335434b9c0b20778087","expire":1687940790,"userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/102.0.0.0 Safari\/537.36","ip":"192.168.240.1","countryCode":"--","osCode":"LIN","osName":"GNU\/Linux","osVersion":"","clientType":"browser","clientCode":"CH","clientName":"Chrome","clientVersion":"102.0","clientEngine":"Blink","clientEngineVersion":"102.0.0.0","deviceName":"desktop","deviceBrand":"","deviceModel":"","$id":"62babb36b06d3f53a3da","$internalId":"2","$read":["user:62b0263d94fe4a148b7e"],"$write":["user:62b0263d94fe4a148b7e"],"$collection":"sessions"},{"userId":"62b0263d94fe4a148b7e","provider":"email","providerUid":"hostmaster@argis.fr","providerAccessToken":null,"providerAccessTokenExpiry":null,"providerRefreshToken":null,"secret":"32d2993318c39f9fbbc7dbe64621e6ebb84303da195f733b20e2a299e58e03b8","expire":1687941355,"userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/102.0.0.0 Safari\/537.36","ip":"192.168.128.1","countryCode":"--","osCode":"LIN","osName":"GNU\/Linux","osVersion":"","clientType":"browser","clientCode":"CH","clientName":"Chrome","clientVersion":"102.0","clientEngine":"Blink","clientEngineVersion":"102.0.0.0","deviceName":"desktop","deviceBrand":"","deviceModel":"","$id":"62babd6bce5bbbcc747f","$internalId":"3","$read":["user:62b0263d94fe4a148b7e"],"$write":["user:62b0263d94fe4a148b7e"],"$collection":"sessions"}],"tokens":[],"memberships":[{"teamId":"62b0267f0cd3696b75fc","userId":"62b0263d94fe4a148b7e","roles":["owner"],"invited":1655711359,"joined":1655711359,"confirm":true,"secret":"","search":"62b0267f0f1f97a4c843 62b0263d94fe4a148b7e","$id":"62b0267f0f1f97a4c843","$internalId":"1","$read":["team:62b0267f0cd3696b75fc","user:62b0263d94fe4a148b7e"],"$write":["team:62b0267f0cd3696b75fc\/owner","user:62b0263d94fe4a148b7e"],"$collection":"memberships"}],"search":"62b0263d94fe4a148b7e hostmaster@argis.fr hostmaster","$read":["role:all"],"$write":["user:62b0263d94fe4a148b7e"],"$id":"62b0263d94fe4a148b7e","$internalId":"1","$collection":"users"},"payload":[],"context":null,"events":["functions.62babbe349bfcba43312.deployments.62babbf546e1e56b0171.delete","functions.*.deployments.*.delete","functions.62babbe349bfcba43312.deployments.*.delete","functions.*.deployments.62babbf546e1e56b0171.delete","functions.62babbe349bfcba43312.deployments.62babbf546e1e56b0171","functions.*.deployments.*","functions.62babbe349bfcba43312.deployments.*","functions.*.deployments.62babbf546e1e56b0171","functions.62babbe349bfcba43312","functions.*"]}]) has failed TypeError: Executor\Executor::__construct(): Argument #1 ($endpoint) must be of type string, null given, called in /usr/src/code/app/workers/functions.php on line 36 and defined in /usr/src/code/src/Executor/Executor.php:29
appwrite-worker-functions       | Stack trace:
appwrite-worker-functions       | #0 /usr/src/code/app/workers/functions.php(36): Executor\Executor->__construct(NULL)
appwrite-worker-functions       | #1 /usr/src/code/src/Appwrite/Resque/Worker.php(94): FunctionsV1->init()
appwrite-worker-functions       | #2 /usr/src/code/vendor/resque/php-resque/lib/Resque/Job.php(198): Appwrite\Resque\Worker->setUp()
appwrite-worker-functions       | #3 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(303): Resque_Job->perform()
appwrite-worker-functions       | #4 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(242): Resque_Worker->perform(Object(Resque_Job))
appwrite-worker-functions       | #5 /usr/src/code/vendor/resque/php-resque/bin/resque(185): Resque_Worker->work('0.1', false)
appwrite-worker-functions       | #6 {main}

```

maybe it's related?

**Comment by stnguyen90** [comment]
> Thanks for your answer. The compose file is indeed in a folder named `apprwite`. I did:
> 
> ```
> docker-compose down
> docker-compose up --remove-orphans
> ```
> 
> So I have a nice bunch of containers: ![image](https://user-images.githubusercontent.com/361582/176132865-8feea80d-6116-4a8b-90e1-0f09c1ea2674.png)
> 
> and the network named is as expected: ![image](https://user-images.githubusercontent.com/361582/176133046-b970122e-9ea4-460f-a212-f7001578a4ba.png)
> 
> I tried to create a network juste named "appwrite":
> 
> ```
> docker network create appwrite
> ```
> 
> and adjusting the `docker-compose.yml` file, but the result is the same.

There may be some networks you're missing...perhaps it's due to missing env vars. Can you compare your env vars to https://gist.github.com/eldadfux/977869ff6bdd7312adfd4e629ee15cc5 again to see if you have everything. In particular, there's a `_APP_EXECUTOR_HOST` env var you may be missing.

**Comment by stnguyen90** [comment]
> I'm testing with both nodejs and php versions of https://github.com/appwrite/demos-for-functions/tree/master/nodejs/get-covid-stats.

@gregfr, that repo is for an older version of Appwrite. I suggest you follow our [Functions docs](https://appwrite.io/docs/functions) for setting up a sample function and deploying it to Appwrite. You might also want to either [upgrade](https://appwrite.io/docs/upgrade) your Appwrite instance or make sure to install version [0.17.1](https://www.npmjs.com/package/appwrite-cli/v/0.17.1) of the Appwrite CLI since the latest version of the Appwrite CLI is for Appwrite version 0.15.X.

For example Appwrite Functions in the newer format, refer to the [Open Runtimes Functions Examples](https://github.com/open-runtimes/examples) repo.

> Docker Error: WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.

If this continues to be a problem, check out [this](https://medium.com/geekculture/appwrite-frequently-asked-questions-374ce81513fe#00aa).

**Comment by gregfr** [comment]
Tanks for your answer. Any plan to update the demos? it would help people get started with this new technology. If not, please at least mention that so people don't try and use them.

**Comment by stnguyen90** [comment]
@gregfr, what demos are you referring to?

**Comment by gregfr** [comment]
I tried this:

https://github.com/appwrite/demos-for-functions/tree/master/nodejs/get-covid-stats

**Comment by stnguyen90** [comment]
> Any plan to update the demos?

You can find the new examples/demos [here](https://github.com/open-runtimes/examples). Contributions are more than welcome!

> please at least mention

Thanks for the suggestion 🙏. We've added a warning on the [README](https://github.com/appwrite/demos-for-functions/blob/master/README.md) to let users know not to use the demos if they are on Appwrite versions 0.13.X or above. 

@gregfr, anything else you need, or can this be closed?

**Comment by stnguyen90** [comment]
Closing due to inactivity.
