### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by iBelow** [appwrite/appwrite#3548]
### 👟 Reproduction steps

installing appwrite 0.15.2 (docker)

### 👍 Expected behavior

working container

### 👎 Actual Behavior

 appwrite/appwrite:0.15.2   "docker-php-entrypoint..."

```
Worker 34 started successfully

Fatal error: Uncaught PDOException: Unknown column '_createdAt' in 'field list' in @swoole-src/library/core/Database/PDOStatementProxy.php:64
Stack trace:
#0 /usr/src/code/vendor/utopia-php/database/src/Database/Adapter/MariaDB.php(521): Swoole\Database\PDOStatementProxy->__call('execute', Array)
#1 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(1125): Utopia\Database\Adapter\MariaDB->createDocument('_metadata', Object(Utopia\Database\Document))
#2 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(378): Utopia\Database\Database->createDocument(Object(Utopia\Database\Document), Object(Utopia\Database\Document))
#3 /usr/src/code/app/http.php(157): Utopia\Database\Database->createCollection('tokens', Array, Array)
#4 {main}
  thrown in @swoole-src/library/core/Database/PDOStatementProxy.php on line 64
[2022-07-14 11:57:03 #1.6]      ERROR   php_swoole_server_rshutdown() (ERRNO 503): Fatal error: Uncaught PDOException: Unknown column '_createdAt' in 'field list' in @swoole-src/library/core/Database/PDOStatementProxy.php:64
Stack trace:
#0 /usr/src/code/vendor/utopia-php/database/src/Database/Adapter/MariaDB.php(521): Swoole\Database\PDOStatementProxy->__call('execute', Array)
#1 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(1125): Utopia\Database\Adapter\MariaDB->createDocument('_metadata', Object(Utopia\Database\Document))
#2 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(378): Utopia\Database\Database->createDocument(Object(Utopia\Database\Document), Object(Utopia\Database\Document))
#3 /usr/src/code/app/http.php(157): Utopia\Database\Database->createCollection('tokens', Array, Array)
#4 {main}
  thrown in @swoole-src/library/core/Database/PDOStatementProxy.php on line 64
```

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by iBelow** [comment]
migration not working, but working this simple solution

FIX (on linux): 
sudo docker volume prune


!!! WARNING !!!
