### ISSUE TITLE
🐛 Bug Report: Function fails with exception "Unsupported endpoint in ...."

### ISSUE THREAD

**Issue by khashashin** [appwrite/appwrite#3556]
### 👟 Reproduction steps

I have created a function that is triggered when a user is created. This function uses Python 3.10 interpreter. 

![image](https://user-images.githubusercontent.com/17837758/179431184-af5ab70b-4096-4e55-b9e3-23515fc7b6fd.png)

![image](https://user-images.githubusercontent.com/17837758/179431208-fa3a3b6b-0fc2-4a4f-8637-310c7c814b59.png)

Logs are empty
![image](https://user-images.githubusercontent.com/17837758/179431222-c1195208-edfd-4e81-8700-655d664c195f.png)

Here is the function itself (check the email address of new created user and block the user if it is temporary email address:

```python
# main.py
import os
import json
import http.client

NECWV_BLOCK_TEMP_EMAIL_API_KEY = os.environ.get("NECWV_BLOCK_TEMP_EMAIL_API_KEY", "")
NECWV_PROJECT_ID = os.environ.get("NECWV_PROJECT_ID", "")
NECWV_API_KEY = os.environ.get("NECWV_API_KEY", "")

NECWV_FUNCTION_EVENT_DATA = os.environ.get("APPWRITE_FUNCTION_EVENT_DATA", "")

temp_email_block_headers = {
    "x-api-key": NECWV_BLOCK_TEMP_EMAIL_API_KEY
}

appwrite_headers = {
    'X-Appwrite-Project': NECWV_PROJECT_ID,
    'X-Appwrite-Key': NECWV_API_KEY,
    'Content-Type': 'application/json'
}


conn = http.client.HTTPSConnection("block-temporary-email.com")


def validate():
    print("Starting validation of User email address")
    print("NECWV_FUNCTION_EVENT_DATA: ", NECWV_FUNCTION_EVENT_DATA)
    conn.request("GET", "/check/email/gekasdih9as82@tebyy.com", headers=temp_email_block_headers)
    response = conn.getresponse()
    data = response.read()
    data = json.loads(data)
    if data["temporary"]:
        print("User email address is temporary")
        print("Starting user blocking procedure")
        connect_to_appwrite = http.client.HTTPSConnection("top.dodom.dev")
        d = json.dumps({"status": False})
        connect_to_appwrite.request(
            "PATCH",
            '/v1/users/s8d7gh87r9wsdgf/status',
            headers=appwrite_headers,
            body=d
        )
        response = connect_to_appwrite.getresponse()
        if response.status == 200:
            print("User blocked successfully")
    else:
        print("Email address is not temporary")


if __name__ == '__main__':
    validate()
```

This function works properly when I run it locally on my PC, it changes the status of the user as false as expected. But it does not work under appwrite.

### 👍 Expected behavior

The function should be executed

### 👎 Actual Behavior

It fails with exception:
```
has failed Exception: Unsupported endpoint in /usr/src/code/src/Executor/Executor.php:32
```

The whole output when I do `docker logs --follow appwrite-worker-functions`:

```
[notice] Starting work on (Job{v1-functions} | ID: 42e6c7c5c08d8ed124179f30e258ee95 | FunctionsV1 | [{"project":{"teamInternalId":"2","teamId":"62d20f323c0022a1fe8d","name":"Test CWV","description":"","logo":"","url":"","version":"0.15.2","legalName":"","legalCountry":"","legalState":"","legalCity":"","legalAddress":"","legalTaxId":"","services":[],"auths":{"limit":0,"emailPassword":true,"usersAuthMagicURL":true,"anonymous":true,"invites":true,"JWT":true,"phone":true},"authProviders":[],"platforms":[{"projectInternalId":"2","projectId":"chechen-word-voting-test","type":"web","name":"localhost","key":"","store":"","hostname":"localhost","$id":"62d20f486471a671d14c","$internalId":"1","$createdAt":1657933640,"$updatedAt":1657933640,"$read":["role:all"],"$write":["role:all"],"$collection":"platforms"}],"webhooks":[],"keys":[{"projectInternalId":"2","projectId":"chechen-word-voting-test","name":"Email Validation and User Control","scopes":["users.read","users.write"],"secret":"secret","expire":0,"$id":"62d41c2f19e68ecb8ab6","$internalId":"1","$createdAt":1658068015,"$updatedAt":1658068015,"$read":["role:all"],"$write":["role:all"],"$collection":"keys"}],"domains":[],"search":"chechen-word-voting-test Test CWV","$read":["team:62d20f323c0022a1fe8d"],"$write":["team:62d20f323c0022a1fe8d\/developer","team:62d20f323c0022a1fe8d\/owner"],"$id":"chechen-word-voting-test","$internalId":"2","$createdAt":1657933618,"$updatedAt":1657933618,"$collection":"projects"},"user":{"name":"Fname Sname","email":"myemail@dodom.dev","phone":null,"status":true,"password":"sueperpuperpass","passwordUpdate":123,"prefs":[],"registration":123,"emailVerification":false,"phoneVerification":null,"reset":false,"sessions":[{"userInternalId":"1","userId":"123","provider":"email","providerUid":"myemail@dodom.dev","providerAccessToken":null,"providerAccessTokenExpiry":null,"providerRefreshToken":null,"secret":"asd123","expire":1689467257,"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/103.0.0.0 Safari\/537.36","ip":"123.123.123.123","countryCode":"ch","osCode":"WIN","osName":"Windows","osVersion":"10","clientType":"browser","clientCode":"CH","clientName":"Chrome","clientVersion":"103.0","clientEngine":"Blink","clientEngineVersion":"103.0.0.0","deviceName":"desktop","deviceBrand":"","deviceModel":"","$id":"62d205f930b4592a1159","$internalId":"1","$createdAt":1657931257,"$updatedAt":1657931257,"$read":["user:62d205f9185fc6f54846"],"$write":["user:62d205f9185fc6f54846"],"$collection":"sessions"}],"tokens":[],"memberships":[{"userInternalId":"1","userId":"62d205f9185fc6f54846","teamInternalId":"1","teamId":"62d206362b8230c848be","roles":["owner"],"invited":1657931318,"joined":1657931318,"confirm":true,"secret":"","search":"62d206362e2ed8c14834 62d205f9185fc6f54846","$id":"62d206362e2ed8c14834","$internalId":"1","$createdAt":1657931318,"$updatedAt":1657931318,"$read":["team:62d206362b8230c848be","user:62d205f9185fc6f54846"],"$write":["team:62d206362b8230c848be\/owner","user:62d205f9185fc6f54846"],"$collection":"memberships"},{"userInternalId":"1","userId":"62d205f9185fc6f54846","teamInternalId":"2","teamId":"62d20f323c0022a1fe8d","roles":["owner"],"invited":1657933618,"joined":1657933618,"confirm":true,"secret":"","search":"62d20f324051cb2a6234 62d205f9185fc6f54846","$id":"62d20f324051cb2a6234","$internalId":"2","$createdAt":1657933618,"$updatedAt":1657933618,"$read":["team:62d20f323c0022a1fe8d","user:62d205f9185fc6f54846"],"$write":["team:62d20f323c0022a1fe8d\/owner","user:62d205f9185fc6f54846"],"$collection":"memberships"}],"search":"62d205f9185fc6f54846 myemail@dodom.dev Fname Sname","$read":["role:all"],"$write":["user:62d205f9185fc6f54846"],"$id":"62d205f9185fc6f54846","$internalId":"1","$createdAt":1657931257,"$updatedAt":1657931257,"$collection":"users"},"payload":{"$id":"check-email-blacklist","$createdAt":1658062005,"$updatedAt":1658099841,"execute":["role:all"],"name":"Check Email Blacklist and Block user","status":"disabled","runtime":"python-3.10","deployment":"","vars":{"NECWV_BLOCK_TEMP_EMAIL_API_KEY":"apikey","NECWV_API_KEY":"apikey2","NECWV_PROJECT_ID":"chechen-word-voting-test"},"events":["users.*.create"],"schedule":"* * * * *","scheduleNext":0,"schedulePrevious":0,"timeout":15},"context":[],"events":["functions.check-email-blacklist.update","functions.*.update","functions.check-email-blacklist","functions.*"]}])
[critical] (Job{v1-functions} | ID: 42e6c7c5c08d8ed124179f30e258ee95 | FunctionsV1 | [{"project":{"teamInternalId":"2","teamId":"62d20f323c0022a1fe8d","name":"Test CWV","description":"","logo":"","url":"","version":"0.15.2","legalName":"","legalCountry":"","legalState":"","legalCity":"","legalAddress":"","legalTaxId":"","services":[],"auths":{"limit":0,"emailPassword":true,"usersAuthMagicURL":true,"anonymous":true,"invites":true,"JWT":true,"phone":true},"authProviders":[],"platforms":[{"projectInternalId":"2","projectId":"chechen-word-voting-test","type":"web","name":"localhost","key":"","store":"","hostname":"localhost","$id":"62d20f486471a671d14c","$internalId":"1","$createdAt":1657933640,"$updatedAt":1657933640,"$read":["role:all"],"$write":["role:all"],"$collection":"platforms"}],"webhooks":[],"keys":[{"projectInternalId":"2","projectId":"chechen-word-voting-test","name":"Email Validation and User Control","scopes":["users.read","users.write"],"secret":"apikey2","expire":0,"$id":"62d41c2f19e68ecb8ab6","$internalId":"1","$createdAt":1658068015,"$updatedAt":1658068015,"$read":["role:all"],"$write":["role:all"],"$collection":"keys"}],"domains":[],"search":"chechen-word-voting-test Test CWV","$read":["team:62d20f323c0022a1fe8d"],"$write":["team:62d20f323c0022a1fe8d\/developer","team:62d20f323c0022a1fe8d\/owner"],"$id":"chechen-word-voting-test","$internalId":"2","$createdAt":1657933618,"$updatedAt":1657933618,"$collection":"projects"},"user":{"name":"Fname Sname","email":"myemail@dodom.dev","phone":null,"status":true,"password":"sueperpuperpass","passwordUpdate":1657931257,"prefs":[],"registration":1657931257,"emailVerification":false,"phoneVerification":null,"reset":false,"sessions":[{"userInternalId":"1","userId":"62d205f9185fc6f54846","provider":"email","providerUid":"myemail@dodom.dev","providerAccessToken":null,"providerAccessTokenExpiry":null,"providerRefreshToken":null,"secret":"9960a7736472b00556ef07971c8e1f54c387fd5e09027c3491dfed462990aecd","expire":1689467257,"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/103.0.0.0 Safari\/537.36","ip":"123.123.123.123","countryCode":"ch","osCode":"WIN","osName":"Windows","osVersion":"10","clientType":"browser","clientCode":"CH","clientName":"Chrome","clientVersion":"103.0","clientEngine":"Blink","clientEngineVersion":"103.0.0.0","deviceName":"desktop","deviceBrand":"","deviceModel":"","$id":"62d205f930b4592a1159","$internalId":"1","$createdAt":1657931257,"$updatedAt":1657931257,"$read":["user:62d205f9185fc6f54846"],"$write":["user:62d205f9185fc6f54846"],"$collection":"sessions"}],"tokens":[],"memberships":[{"userInternalId":"1","userId":"62d205f9185fc6f54846","teamInternalId":"1","teamId":"62d206362b8230c848be","roles":["owner"],"invited":1657931318,"joined":1657931318,"confirm":true,"secret":"","search":"62d206362e2ed8c14834 62d205f9185fc6f54846","$id":"62d206362e2ed8c14834","$internalId":"1","$createdAt":1657931318,"$updatedAt":1657931318,"$read":["team:62d206362b8230c848be","user:62d205f9185fc6f54846"],"$write":["team:62d206362b8230c848be\/owner","user:62d205f9185fc6f54846"],"$collection":"memberships"},{"userInternalId":"1","userId":"62d205f9185fc6f54846","teamInternalId":"2","teamId":"62d20f323c0022a1fe8d","roles":["owner"],"invited":1657933618,"joined":1657933618,"confirm":true,"secret":"","search":"62d20f324051cb2a6234 62d205f9185fc6f54846","$id":"62d20f324051cb2a6234","$internalId":"2","$createdAt":1657933618,"$updatedAt":1657933618,"$read":["team:62d20f323c0022a1fe8d","user:62d205f9185fc6f54846"],"$write":["team:62d20f323c0022a1fe8d\/owner","user:62d205f9185fc6f54846"],"$collection":"memberships"}],"search":"62d205f9185fc6f54846 myemail@dodom.dev Fname Sname","$read":["role:all"],"$write":["user:62d205f9185fc6f54846"],"$id":"62d205f9185fc6f54846","$internalId":"1","$createdAt":1657931257,"$updatedAt":1657931257,"$collection":"users"},"payload":{"$id":"check-email-blacklist","$createdAt":1658062005,"$updatedAt":1658099841,"execute":["role:all"],"name":"Check Email Blacklist and Block user","status":"disabled","runtime":"python-3.10","deployment":"","vars":{"NECWV_BLOCK_TEMP_EMAIL_API_KEY":"apikey","NECWV_API_KEY":"apikey2","NECWV_PROJECT_ID":"chechen-word-voting-test"},"events":["users.*.create"],"schedule":"* * * * *","scheduleNext":0,"schedulePrevious":0,"timeout":15},"context":[],"events":["functions.check-email-blacklist.update","functions.*.update","functions.check-email-blacklist","functions.*"]}]) has failed Exception: Unsupported endpoint in /usr/src/code/src/Executor/Executor.php:32
Stack trace:
#0 /usr/src/code/app/workers/functions.php(36): Executor\Executor->__construct('appwrite-execut...')
#1 /usr/src/code/src/Appwrite/Resque/Worker.php(97): FunctionsV1->init()
#2 /usr/src/code/vendor/resque/php-resque/lib/Resque/Job.php(198): Appwrite\Resque\Worker->setUp()
#3 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(303): Resque_Job->perform()
#4 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(242): Resque_Worker->perform(Object(Resque_Job))
#5 /usr/src/code/vendor/resque/php-resque/bin/resque(185): Resque_Worker->work('0.1', false)
#6 {main}
```

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by gepd** [comment]
Seems like you're using a not valid syntax, check this template as refrence: https://github.com/appwrite/functions-starter/blob/main/python-3.10/src/index.py

**Comment by khashashin** [comment]
Should the function implement `main` method or should it be placed in `src` folder? Are there some conversion about the structure of functions?

**Comment by Meldiron** [comment]
You can find a recommended structure for functions here: https://github.com/appwrite/functions-starter
Depending on when you place your main python file, you need to provide the correct path to the entry point when making a deployment.

**Comment by Meldiron** [comment]
Regarding main method, also, you can refer to function starters. there you can see what a function should look like in every language.

**Comment by stnguyen90** [comment]
Would you please double check this in your .env?

```
_APP_EXECUTOR_HOST=http://appwrite-executor/v1
```

FYI, regarding your code, `os.environ.get("NECWV_BLOCK_TEMP_EMAIL_API_KEY", "")` will not work. variables are in `req.env` in your `main`.

**Comment by khashashin** [comment]
> Would you please double check this in your .env?
> 
> ```
> _APP_EXECUTOR_HOST=http://appwrite-executor/v1
> ```

Thanks for pointing on that. After checking the logs of `appwrite-executer` I found following:

```
khashashin@dockers-khasdev:~/appwrite$ docker-compose logs --follow appwrite-executor
WARNING: Some networks were defined but are not used by any service: gateway
Attaching to appwrite-executor
appwrite-executor               | Removing orphan runtimes...
appwrite-executor               | Warming up Python 3.9 environment...
appwrite-executor               | Warming up Python 3.10 environment...
appwrite-executor               |
appwrite-executor               | Warning: Undefined variable $orchestration in /usr/src/code/app/executor.php on line 660
appwrite-executor               | Warming up Deno 1.12 environment...
appwrite-executor               | Warming up Deno 1.13 environment...
appwrite-executor               | Warming up Deno 1.14 environment...
appwrite-executor               | Warming up Deno 1.21 environment...
appwrite-executor               | Warming up Dart 2.12 environment...
appwrite-executor               | Warming up Dart 2.13 environment...
appwrite-executor               | Warming up Dart 2.14 environment...
appwrite-executor               | Failed to Warmup Python 3.9!
appwrite-executor               | Warming up Dart 2.15 environment...
appwrite-executor               | Warming up Dart 2.16 environment...
appwrite-executor               | Failed to Warmup Python 3.10!
appwrite-executor               | Warming up Dart 2.17 environment...
appwrite-executor               | Failed to Warmup Deno 1.14!
appwrite-executor               | Warming up .NET 3.1 environment...
appwrite-executor               | Failed to Warmup Deno 1.12!
appwrite-executor               | Successfully Warmed up Deno 1.21!
appwrite-executor               | Successfully Warmed up Deno 1.13!
appwrite-executor               | Warming up .NET 6.0 environment...
appwrite-executor               | Warming up Java 8.0 environment...
appwrite-executor               | Warming up Java 11.0 environment...
appwrite-executor               | Failed to Warmup Dart 2.13!
appwrite-executor               | Warming up Java 17.0 environment...
appwrite-executor               | Failed to Warmup Dart 2.12!
appwrite-executor               | Warming up Java 18.0 environment...
appwrite-executor               | Failed to Warmup Dart 2.14!
appwrite-executor               | Warming up Swift 5.5 environment...
appwrite-executor               | Failed to Warmup Dart 2.15!
appwrite-executor               | Failed to Warmup Dart 2.16!
appwrite-executor               | Warming up Kotlin 1.6 environment...
appwrite-executor               | Warming up C++ 17.0 environment...
appwrite-executor               | Failed to Warmup Dart 2.17!
appwrite-executor               | Warming up Node.js 15.5 environment...
appwrite-executor               | Failed to Warmup Java 11.0!
appwrite-executor               | Warming up Ruby 3.0 environment...
appwrite-executor               | Failed to Warmup Java 8.0!
appwrite-executor               | Warming up Python 3.8 environment...
appwrite-executor               | Failed to Warmup .NET 3.1!
appwrite-executor               | Warming up Node.js 16.0 environment...
appwrite-executor               | Failed to Warmup .NET 6.0!
appwrite-executor               | Warming up PHP 8.0 environment...
appwrite-executor               | Failed to Warmup Java 18.0!
appwrite-executor               | Failed to Warmup Swift 5.5!
appwrite-executor               | Warming up Ruby 3.1 environment...
appwrite-executor               | Warming up PHP 8.1 environment...
appwrite-executor               | Failed to Warmup Java 17.0!
appwrite-executor               | Warming up Node.js 18.0 environment...
appwrite-executor               | Warming up Node.js 17.0 environment...
appwrite-executor               | Failed to Warmup Kotlin 1.6!
appwrite-executor               | Failed to Warmup C++ 17.0!
appwrite-executor               | Failed to Warmup Node.js 15.5!
appwrite-executor               | Failed to Warmup Ruby 3.0!
appwrite-executor               | Failed to Warmup Node.js 16.0!
appwrite-executor               | Failed to Warmup Ruby 3.1!
appwrite-executor               | Failed to Warmup PHP 8.0!
appwrite-executor               | Failed to Warmup Python 3.8!
appwrite-executor               | Failed to Warmup Node.js 18.0!
appwrite-executor               | Failed to Warmup PHP 8.1!
appwrite-executor               | Failed to Warmup Node.js 17.0!
```

**Comment by khashashin** [comment]
And here the log output of `appwrite-executor` after deploying the function:
```
appwrite-executor               | Warming up Node.js 17.0 environment...
appwrite-executor               | Failed to Warmup Kotlin 1.6!
appwrite-executor               | Failed to Warmup C++ 17.0!
appwrite-executor               | Failed to Warmup Node.js 15.5!
appwrite-executor               | Failed to Warmup Ruby 3.0!
appwrite-executor               | Failed to Warmup Node.js 16.0!
appwrite-executor               | Failed to Warmup Ruby 3.1!
appwrite-executor               | Failed to Warmup PHP 8.0!
appwrite-executor               | Failed to Warmup Python 3.8!
appwrite-executor               | Failed to Warmup Node.js 18.0!
appwrite-executor               | Failed to Warmup PHP 8.1!
appwrite-executor               | Failed to Warmup Node.js 17.0!
appwrite-executor               | [Error] Type: Exception
appwrite-executor               | [Error] Message: Runtime not found
appwrite-executor               | [Error] File: /usr/src/code/app/executor.php
appwrite-executor               | [Error] Line: 421
appwrite-executor               | [Error] Type: Utopia\Orchestration\Exception\Orchestration
appwrite-executor               | [Error] Message: Docker Error: WARNING! Your password will be stored unencrypted in /.docker/config.json.
appwrite-executor               | Configure a credential helper to remove this warning. See
appwrite-executor               | https://docs.docker.com/engine/reference/commandline/login/#credentials-store
appwrite-executor               |
appwrite-executor               |
appwrite-executor               | [Error] File: /usr/src/code/vendor/utopia-php/orchestration/src/Orchestration/Adapter/DockerCLI.php
appwrite-executor               | [Error] Line: 28
```

**Comment by khashashin** [comment]
After correcting the `_APP_EXECUTOR_HOST=http://appwrite-executor/v1` variable I see at least the error directly in appwrite console

 
![image](https://user-images.githubusercontent.com/17837758/179583939-65cebd37-87c4-4dff-b98f-c58fccfcc8d4.png)

![image](https://user-images.githubusercontent.com/17837758/179584001-e2d90c35-c1c0-49d2-81e0-97cf35654121.png)

**Comment by stnguyen90** [comment]
> I've following two env variables in my .env:
> 
> ```
> # hub.docker.com credentials
> DOCKERHUB_PULL_USERNAME=username
> DOCKERHUB_PULL_PASSWORD=userpassword
> ```

I don't think you *need* to have these. Can you try without these set?

**Comment by khashashin** [comment]
> I don't think you _need_ to have these. Can you try without these set?

Yes now it works:
![image](https://user-images.githubusercontent.com/17837758/179604080-370e62dd-97d1-452e-94a4-3bce3115624f.png)

Just to summarize the steps related to this issue:
1. Follow the functions template (in this case [this](https://github.com/appwrite/functions-starter/tree/main/python-3.10))
  - Also follow the folder structure
2. Set the environment variable in your .env file: `_APP_EXECUTOR_HOST=http://appwrite-executor/v1`
3. Remove `DOCKERHUB_PULL_USERNAME=username` and `DOCKERHUB_PULL_PASSWORD=userpassword`

To debug always check the logs for two containers:

```
docker-compose logs --follow appwrite-executor
docker-compose logs --follow appwrite-worker-functions
```
