### ISSUE TITLE
Failed: SQLSTATE[42S02]: Base table or view not found

### ISSUE THREAD

**Issue by zedpr0** [appwrite/appwrite#3713]
I keep getting errors in my appwrite-usage docker, my logs are as bellow:

```
Failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'appwrite._3_database_3' doesn't exist
[PDO] MySQL connection restarted
Failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'appwrite.___metadata' doesn't exist
#0 /usr/src/code/src/Appwrite/Extend/PDOStatement.php(88): PDOStatement->execute(NULL)
#1 /usr/src/code/vendor/utopia-php/database/src/Database/Adapter/MariaDB.php(431): Appwrite\Extend\PDOStatement->execute()
#2 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(1065): Utopia\Database\Adapter\MariaDB->getDocument('_metadata', 'stats')
#3 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(391): Utopia\Database\Database->getDocument(Object(Utopia\Database\Document), 'stats')
#4 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(1049): Utopia\Database\Database->getCollection('stats')
#5 /usr/src/code/src/Appwrite/Stats/Usage.php(232): Utopia\Database\Database->getDocument('stats', 'dc23d9360fdaf30...')
#6 /usr/src/code/src/Appwrite/Stats/Usage.php(323): Appwrite\Stats\Usage->createOrUpdateMetric('62acb68028978ba...', 1661212800, '1d', 'network', 0, 0)
#7 /usr/src/code/src/Appwrite/Stats/Usage.php(347): Appwrite\Stats\Usage->syncFromInfluxDB('network', Array, Array)
#8 /usr/src/code/app/tasks/usage.php(138): Appwrite\Stats\Usage->collect()
#9 /usr/src/code/vendor/utopia-php/cli/src/CLI/Console.php(208): {closure}()
#10 /usr/src/code/app/tasks/usage.php(163): Utopia\CLI\Console::loop(Object(Closure), 30)
#11 /usr/src/code/vendor/utopia-php/cli/src/CLI/CLI.php(233): {closure}()
#12 /usr/src/code/app/cli.php(32): Utopia\CLI\CLI->run()
#13 {main}
```

I have tried restoring from backup, reinstalling appwrite, and migrating, but i still get this issue. Im not sure whats wrong. Could use some pointers as to what next steps I could take.

Apart from that the appwrite-usage docker is using 100% of a CPU core.

🎲 Appwrite version

Version 0.15.3.402

💻 Operating system

Ubuntu 22.04 LTS

**Comment by christyjacob4** [comment]
@zedpr0 👋  

It looks like the database got into an inconsistent state somehow. If this project of yours is not important, I would recommend starting fresh by using the following commands from the `appwrite/` directory that was created during installation

```sh
docker compose down -v --remove-orphans
docker compose up -d --build --force-recreate
```

This should fix the issue. If not, please share the logs from the `appwrite` and `mariadb` containers upon the fresh start using

```sh
docker compose logs appwrite
docker compose logs mariadb
```

**Comment by zedpr0** [comment]
@christyjacob4 Thanks for the reply, is there anyway to fix it without loosing my data?

**Comment by stnguyen90** [comment]
@zedpr0,  please share the logs from the `appwrite` and `mariadb` containers upon the fresh start using

```
docker compose logs appwrite
docker compose logs mariadb
```

Would you please also give more context? What happened before this? Did you upgrade recently? 

Finally, do you have these environment variables set?

```
_APP_MAINTENANCE_INTERVAL=86400
_APP_MAINTENANCE_RETENTION_EXECUTION=1209600
_APP_MAINTENANCE_RETENTION_ABUSE=86400
_APP_MAINTENANCE_RETENTION_AUDIT=120960
```

**Comment by zedpr0** [comment]
@stnguyen90 thanks for the reply.

appewrite:

`[Static Files] Loadded 137 files
Worker 1 started successfully
Worker 4 started successfully
Worker 5 started successfully
Worker 3 started successfully
Worker 2 started successfully
Worker 6 started successfully
Worker 8 started successfully
Worker 9 started successfully
Worker 7 started successfully
Worker 10 started successfully
Worker 11 started successfully
Worker 12 started successfully
[Setup] - Server database init started...
[Setup] - Creating metadata table: appwrite...
[Setup] - Server database init completed...
Server started successfully (max payload is 6,291,456 bytes)
Master pid 1, manager pid 8`

mariadb: 

`2022-08-23 04:13:34+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.7.4+maria~focal started.
2022-08-23 04:13:34+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2022-08-23 04:13:34+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.7.4+maria~focal started.
2022-08-23 04:13:35+00:00 [Note] [Entrypoint]: MariaDB upgrade not required
2022-08-23  4:13:35 0 [Note] mysqld (server 10.7.4-MariaDB-1:10.7.4+maria~focal) starting as process 1 ...
2022-08-23  4:13:35 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2022-08-23  4:13:35 0 [Note] InnoDB: Number of transaction pools: 1
2022-08-23  4:13:35 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
2022-08-23  4:13:35 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
2022-08-23  4:13:35 0 [Note] InnoDB: Using Linux native AIO
2022-08-23  4:13:35 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
2022-08-23  4:13:35 0 [Note] InnoDB: Completed initialization of buffer pool
2022-08-23  4:13:35 0 [Note] InnoDB: 128 rollback segments are active.
2022-08-23  4:13:35 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2022-08-23  4:13:35 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2022-08-23  4:13:35 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2022-08-23  4:13:35 0 [Note] InnoDB: 10.7.4 started; log sequence number 484715826454; transaction id 1611608026
2022-08-23  4:13:35 0 [Note] Plugin 'FEEDBACK' is disabled.
2022-08-23  4:13:35 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2022-08-23  4:13:35 0 [Warning] You need to use --log-bin to make --expire-logs-days or --binlog-expire-logs-seconds work.
2022-08-23  4:13:35 0 [Note] Server socket created on IP: '0.0.0.0'.
2022-08-23  4:13:35 0 [Note] Server socket created on IP: '::'.
2022-08-23  4:13:35 0 [Note] mysqld: ready for connections.
Version: '10.7.4-MariaDB-1:10.7.4+maria~focal'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
2022-08-23  4:13:35 0 [Note] InnoDB: Buffer pool(s) load completed at 220823  4:13:35`

I have all the variables except for _APP_MAINTENANCE_RETENTION_ABUSE=86400

For context, last upgrade was early this month, i only noticed this when i checked my cpu usage graph and since the 5th of august its been 150% / 200%, which is alarming, upon investigation its just the appwrite-usage docker, seems to be running a loop trying to aggregate every 30 seconds and so for the meantime i set it to only aggregate every 900 seconds. But that still leaves the issue of the database.

**Comment by joeyouss** [comment]
Hi @zedpr0 , wanted to check in if this is working for you now?

**Comment by EVDOG4LIFE** [comment]
Closing out due to age, if this is still valid - please create a support thread on our [discord](discord.gg/appwrite)
