### ISSUE TITLE
🐛 Bug Report: Fatal error: Uncaught PDOException: Data truncated for column '_createdAt' at row 1

### ISSUE THREAD

**Issue by VincentDatrier** [appwrite/appwrite#3770]
### 👟 Reproduction steps

Version: 1.0.0-RC1 (Fresh install)

The newest RC, freshly installed, does not start, and the appwrite container crash-loops:

```
[Static Files] Loadded 141 files
Worker 1 started successfully
[...]
Worker 96 started successfully
[Setup] - Server database init started...
[Setup] - Creating metadata table: appwrite...
[Setup] - Creating collection: cache...

Fatal error: Uncaught PDOException: Data truncated for column '_createdAt' at row 1 in @swoole-src/library/core/Database/PDOStatementProxy.php:64
Stack trace:
#0 /usr/src/code/vendor/utopia-php/database/src/Database/Adapter/MariaDB.php(532): Swoole\Database\PDOStatementProxy->__call('execute', Array)
#1 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(1223): Utopia\Database\Adapter\MariaDB->createDocument('_metadata', Object(Utopia\Database\Document))
#2 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(477): Utopia\Database\Database->createDocument(Object(Utopia\Database\Document), Object(Utopia\Database\Document))
#3 /usr/src/code/app/http.php(160): Utopia\Database\Database->createCollection('cache', Array, Array)
#4 {main}
  thrown in @swoole-src/library/core/Database/PDOStatementProxy.php on line 64
[2022-09-05 19:37:22 #1.8]	ERROR	php_swoole_server_rshutdown() (ERRNO 503): Fatal error: Uncaught PDOException: Data truncated for column '_createdAt' at row 1 in @swoole-src/library/core/Database/PDOStatementProxy.php:64
Stack trace:
#0 /usr/src/code/vendor/utopia-php/database/src/Database/Adapter/MariaDB.php(532): Swoole\Database\PDOStatementProxy->__call('execute', Array)
#1 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(1223): Utopia\Database\Adapter\MariaDB->createDocument('_metadata', Object(Utopia\Database\Document))
#2 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(477): Utopia\Database\Database->createDocument(Object(Utopia\Database\Document), Object(Utopia\Database\Document))
#3 /usr/src/code/app/http.php(160): Utopia\Database\Database->createCollection('cache', Array, Array)
#4 {main}
  thrown in @swoole-src/library/core/Database/PDOStatementProxy.php on line 64
`

### 👍 Expected behavior

It should finish starting.

### 👎 Actual Behavior

It does not start.

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

Fedora Linux 36 (5.19.6-200.fc36.x86_64)
Docker 20.10.17


### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@VincentDatrier, thanks for creating this issue! 🙏  Did you install this on a server that already had an existing Appwrite installation?

I was able to install it fine:

```
appwrite  | [Setup] - Creating collection: builds...
appwrite  | [Setup] - Creating collection: executions...
appwrite  | [Setup] - Creating collection: certificates...
appwrite  | [Setup] - Creating collection: buckets...
appwrite  | [Setup] - Creating collection: stats...
appwrite  | [Setup] - Creating collection: realtime...
appwrite  | [Setup] - Creating collection: cache...
appwrite  | [Setup] - Creating collection: variables...
appwrite  | [Setup] - Creating default bucket...
appwrite  | [Setup] - Creating files collection for default bucket...
appwrite  | [Setup] - Server database init completed...
appwrite  | Server started successfully (max payload is 6,291,456 bytes)
```

**Comment by VincentDatrier** [comment]
Hi Steven,

Indeed I had; I didn't realize doing a docker compose down from the created folder wouldn't delete volumes (why would it though, that's the whole point of volumes!).

I manually removed all volumes from previous versions and appwrite booted successfully.

Sorry for the inconvenience!

Best.
