### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by mrarticuno** [appwrite/appwrite#3826]
### 👟 Reproduction steps

In a fresh new project, when I try to execute a function (any language) it fails for connection refused.

NodeJS example function:

`const sdk = require("node-appwrite");

/*
  'req' variable has:
    'headers' - object with request headers
    'payload' - request body data as a string
    'variables' - object with function variables

  'res' variable has:
    'send(text, status)' - function to return text response. Status code defaults to 200
    'json(obj, status)' - function to return JSON response. Status code defaults to 200

  If an error is thrown, a response with code 500 will be returned.
*/

module.exports = async function (req, res) {
  const client = new sdk.Client();

  // You can remove services you don't use
  let account = new sdk.Account(client);
  let avatars = new sdk.Avatars(client);
  let database = new sdk.Databases(client);
  let functions = new sdk.Functions(client);
  let health = new sdk.Health(client);
  let locale = new sdk.Locale(client);
  let storage = new sdk.Storage(client);
  let teams = new sdk.Teams(client);
  let users = new sdk.Users(client);

  if (
    !req.env["APPWRITE_FUNCTION_ENDPOINT"] ||
    !req.env["APPWRITE_FUNCTION_API_KEY"]
  ) {
    console.warn(
      "Environment variables are not set. Function cannot use Appwrite SDK."
    );
  } else {
    client
      .setEndpoint(req.env["APPWRITE_FUNCTION_ENDPOINT"])
      .setProject(req.env["APPWRITE_FUNCTION_PROJECT_ID"])
      .setKey(req.env["APPWRITE_FUNCTION_API_KEY"])
      .setSelfSigned(true);
  }

  const allUsers = await users.list();

  res.json({
    allUsers,
    areDevelopersAwesome: true,
  });
};
`

### 👍 Expected behavior

function return json.

### 👎 Actual Behavior

`Error: getaddrinfo EAI_AGAIN hostname
    at Client.call (/usr/code-start/node_modules/node-appwrite/lib/client.js:174:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Users.list (/usr/code-start/node_modules/node-appwrite/lib/services/users.js:54:16)
    at async module.exports (/usr/code-start/src/index.js:45:20)
    at async /usr/local/src/server.js:38:13`

logs from appwrite-executor pod:
`Function executed in 5.2419531345367 seconds, status: failed

Warming up Node.js 16.0 environment...

Warming up PHP 8.0 environment...

Warming up Ruby 3.0 environment...

Running maintenance task ...

[Error] Type: Exception

[Error] Message: Runtime not found. Please create the runtime.

[Error] File: /usr/src/code/app/executor.php

[Error] Line: 463

[Error] Type: Exception

[Error] Message: An internal curl error has occurred within the executor! Error Msg: Connection refused

[Error] File: /usr/src/code/app/executor.php

[Error] Line: 533`

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

Default setup.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@mrarticuno, did you create the following variables for your function?

1. `APPWRITE_FUNCTION_ENDPOINT`
2. `APPWRITE_FUNCTION_API_KEY`
