### ISSUE TITLE
🐛 Bug Report: trying use mysql as database insted of mariadb and without docker

### ISSUE THREAD

**Issue by ProKn1fe** [appwrite/appwrite#3851]
### 👟 Reproduction steps

php8.0 app/http.php with mysql as backend database.
Env variables
_APP_DB_HOST=localhost
_APP_DB_PORT=3306
_APP_DB_SCHEMA=appwrite
_APP_DB_USER=root
_APP_DB_PASS=pass
_APP_DB_ROOT_PASS=pass

### 👍 Expected behavior

No errors:D

### 👎 Actual Behavior

```
Worker 1 started successfully
Worker 2 started successfully
Worker 3 started successfully
Worker 4 started successfully
Worker 5 started successfully
Worker 6 started successfully
Worker 7 started successfully
Worker 8 started successfully
Worker 9 started successfully
Worker 10 started successfully
Worker 11 started successfully
Worker 12 started successfully
Worker 13 started successfully
Worker 14 started successfully
Worker 15 started successfully
Worker 17 started successfully
Worker 18 started successfully
Worker 19 started successfully
Worker 20 started successfully
Worker 21 started successfully
Worker 22 started successfully
Worker 23 started successfully
Worker 16 started successfully
Worker 24 started successfully
[Setup] - Server database init started...
[Setup] - Creating metadata table: appwrite...
[Setup] - Creating collection: functions...
PHP Fatal error:  Uncaught PDOException: Specified key was too long; max key length is 3072 bytes in @swoole-src/library/core/Database/PDOStatementProxy.php:64
Stack trace:
#0 /home/appwrite/vendor/utopia-php/database/src/Database/Adapter/MariaDB.php(185): Swoole\Database\PDOStatementProxy->__call()
#1 /home/appwrite/vendor/utopia-php/database/src/Database/Database.php(519): Utopia\Database\Adapter\MariaDB->createCollection()
#2 /home/appwrite/app/http.php(162): Utopia\Database\Database->createCollection()
#3 {main}
  thrown in @swoole-src/library/core/Database/PDOStatementProxy.php on line 64

Fatal error: Uncaught PDOException: Specified key was too long; max key length is 3072 bytes in @swoole-src/library/core/Database/PDOStatementProxy.php:64
Stack trace:
#0 /home/appwrite/vendor/utopia-php/database/src/Database/Adapter/MariaDB.php(185): Swoole\Database\PDOStatementProxy->__call()
#1 /home/appwrite/vendor/utopia-php/database/src/Database/Database.php(519): Utopia\Database\Adapter\MariaDB->createCollection()
#2 /home/appwrite/app/http.php(162): Utopia\Database\Database->createCollection()
#3 {main}
  thrown in @swoole-src/library/core/Database/PDOStatementProxy.php on line 64
[2022-09-15 17:50:49 #52382.4]  ERROR   php_swoole_server_rshutdown() (ERRNO 503): Fatal error: Uncaught PDOException: Specified key was too long; max key length is 3072 bytes in @swoole-src/library/core/Database/PDOStatementProxy.php:64
Stack trace:
#0 /home/appwrite/vendor/utopia-php/database/src/Database/Adapter/MariaDB.php(185): Swoole\Database\PDOStatementProxy->__call()
#1 /home/appwrite/vendor/utopia-php/database/src/Database/Database.php(519): Utopia\Database\Adapter\MariaDB->createCollection()
#2 /home/appwrite/app/http.php(162): Utopia\Database\Database->createCollection()
#3 {main}
  thrown in @swoole-src/library/core/Database/PDOStatementProxy.php on line 64
```

### 🎲 Appwrite version

Latest master branch

### 💻 Operating system

Linux

### 🧱 Your Environment

Latest Ubuntu 22.04.1

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@ProKn1fe, unfortunately, MySQL isn't supported out of the box right now. We plan to make this configurable in the future. If you really want to use MySQL right now, you can try to replace this line of code for all appwrite containers before they start:

https://github.com/appwrite/appwrite/blob/19eb6c7e506768e434d97c5c1f800af2c45dbaec/app/init.php#L55

with:

```php
use Utopia\Database\Adapter\MySQL as MariaDB;
```
