### ISSUE TITLE
🐛 Bug Report: storage.createFile() failed

### ISSUE THREAD

**Issue by xypmhxy** [appwrite/appwrite#3911]
### 👟 Reproduction steps

```dart
final input = await storage.getFileDownload(
      bucketId: 'my bucketId', fileId: imageFileId);

// input has correct data

final storageFile = await storage.createFile(
            bucketId: 'my bucketId'',
            fileId: fileId,
            file: InputFile(bytes: input));
```
output:

```
Unhandled exception:
AppwriteException: storage_file_empty, No file sent (400)
#0      ClientMixin.prepareResponse (package:dart_appwrite/src/client_mixin.dart:73:9)
#1      ClientIO.call (package:dart_appwrite/src/client_io.dart:220:14)
<asynchronous suspension>
#2      Storage.createFile (package:dart_appwrite/services/storage.dart:242:17)
<asynchronous suspension>
#3      start.<anonymous closure> (package:appwrite_function/main.dart:51:29)
<asynchronous suspension>
```

### 👍 Expected behavior

it work 

### 👎 Actual Behavior

```
Unhandled exception:
AppwriteException: storage_file_empty, No file sent (400)
#0      ClientMixin.prepareResponse (package:dart_appwrite/src/client_mixin.dart:73:9)
#1      ClientIO.call (package:dart_appwrite/src/client_io.dart:220:14)
<asynchronous suspension>
#2      Storage.createFile (package:dart_appwrite/services/storage.dart:242:17)
<asynchronous suspension>
#3      start.<anonymous closure> (package:appwrite_function/main.dart:51:29)
<asynchronous suspension>
```

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Are you running on mobile? How big is your file? Would you please make sure you're passing a path and filename to InputFile?

**Comment by stnguyen90** [comment]
@xypmhxy did you get a chance to address my [comment](https://github.com/appwrite/appwrite/issues/3911#issuecomment-1255922455)? So that you know, I'll need to close this due to inactivity soon.

**Comment by stnguyen90** [comment]
Closing due to inactivity.
