### ISSUE TITLE
🐛 Bug Report: Creation of function using CLI causes Appwrite to become unuseable

### ISSUE THREAD

**Issue by Tandashi** [appwrite/appwrite#4322]
### 👟 Reproduction steps

Run the latest `appwrite` version with Docker.

Command from Documentation:
```bash
docker run -it --rm \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --volume "$(pwd)"/appwrite:/usr/src/code/appwrite:rw \
    --entrypoint="install" \
    appwrite/appwrite:1.0.2
```

Then initialise a project using the `appwrite-cli` (installed using brew).
Try to create a new function using the `appwrite-cli` with `appwrite init function`.

Running `appwrite init function --verbose` shows this error:
```
> appwrite -v
0.15.0

> appwrite init function --verbose
? What would you like to name your function? Get Coins
? What runtime would you like to use? Node.js (node-16.0)
AppwriteException [Error]: Error: Server Error
    at Client.call (/opt/homebrew/Cellar/appwrite/HEAD-30da60a/libexec/lib/node_modules/appwrite-cli/lib/client.js:206:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async functionsCreate (/opt/homebrew/Cellar/appwrite/HEAD-30da60a/libexec/lib/node_modules/appwrite-cli/lib/commands/functions.js:103:16)
    at async initFunction (/opt/homebrew/Cellar/appwrite/HEAD-30da60a/libexec/lib/node_modules/appwrite-cli/lib/commands/init.js:67:18) {
  code: 500,
  response: { message: 'Error: Server Error', code: 500, version: '1.0.1' }
}
```

### 👍 Expected behavior

A new function should be created

### 👎 Actual Behavior

The complete instance is unuseable until a full restart using `docker-compose restart`.

Accessing the web-interface only shows:
```
{"message":"Error: Server Error","code":500,"version":"1.0.1"}
```
and is not useable anymore.

Docker logs from `appwrite` container.
```
localhost is not a publicly accessible domain. Skipping SSL certificate generation.
localhost is not a publicly accessible domain. Skipping SSL certificate generation.
localhost is not a publicly accessible domain. Skipping SSL certificate generation.
localhost is not a publicly accessible domain. Skipping SSL certificate generation.
[Error] Type: Utopia\Exception
[Error] Message: Error handler had an error
[Error] File: /usr/src/code/vendor/utopia-php/framework/src/App.php
[Error] Line: 610
[Error] Type: Utopia\Exception
[Error] Message: Error handler had an error
[Error] File: /usr/src/code/vendor/utopia-php/framework/src/App.php
[Error] Line: 610
[Error] Type: Error
[Error] Message: Class "Appwrite\Migration\Version\V13" not found
[Error] File: /usr/src/code/src/Appwrite/Utopia/Request/Filters/V14.php
[Error] Line: 27
[Error] Type: Utopia\Exception
[Error] Message: Error handler had an error
[Error] File: /usr/src/code/vendor/utopia-php/framework/src/App.php
[Error] Line: 610
[Error] Type: Error
[Error] Message: Class "Appwrite\Migration\Version\V13" not found
[Error] File: /usr/src/code/src/Appwrite/Utopia/Request/Filters/V14.php
[Error] Line: 27
localhost is not a publicly accessible domain. Skipping SSL certificate generation.
localhost is not a publicly accessible domain. Skipping SSL certificate generation.
localhost is not a publicly accessible domain. Skipping SSL certificate generation.
localhost is not a publicly accessible domain. Skipping SSL certificate generation.
[Error] Type: Utopia\Exception
[Error] Message: Error handler had an error
[Error] File: /usr/src/code/vendor/utopia-php/framework/src/App.php
[Error] Line: 610
[Error] Type: Utopia\Exception
[Error] Message: Error handler had an error
[Error] File: /usr/src/code/vendor/utopia-php/framework/src/App.php
[Error] Line: 610
[Error] Type: Error
[Error] Message: Class "Appwrite\Migration\Version\V13" not found
[Error] File: /usr/src/code/src/Appwrite/Utopia/Request/Filters/V14.php
[Error] Line: 27
[Error] Type: Utopia\Exception
[Error] Message: Error handler had an error
[Error] File: /usr/src/code/vendor/utopia-php/framework/src/App.php
[Error] Line: 610
[Error] Type: Error
[Error] Message: Class "Appwrite\Migration\Version\V13" not found
[Error] File: /usr/src/code/src/Appwrite/Utopia/Request/Filters/V14.php
[Error] Line: 27
localhost is not a publicly accessible domain. Skipping SSL certificate generation.
[Error] Type: Utopia\Exception
[Error] Message: Error handler had an error
[Error] File: /usr/src/code/vendor/utopia-php/framework/src/App.php
[Error] Line: 610
```

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

Local Docker Environment

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Because of https://github.com/appwrite/sdk-for-cli/issues/52, installing via homebrew installs an older version. I recommend installing via NPM to get the latest CLI that works with Appwrite version 1.0.x

**Comment by Gilbertelnino** [comment]
> Because of [appwrite/sdk-for-cli#52](https://github.com/appwrite/sdk-for-cli/issues/52), installing via homebrew installs an older version. I recommend installing via NPM to get the latest CLI that works with Appwrite version 1.0.x

Thanks, That works
