### ISSUE TITLE
🐛 Bug Report: $permissions is an Object rather than Array

### ISSUE THREAD

**Issue by Shiba-Kar** [appwrite/appwrite#4543]
### 👟 Reproduction steps

1. Write to USER database and write to username collection  The is only one document in the collection.
 ```dart 
    
 static Future<bool> saveUsername(
    Databases databases,
    String username,
    String userId,
  ) async {
    try {
      await databases.createDocument(
        databaseId: userDatabaseID,
        collectionId: usernameCollectionID,
        documentId: userId,
        permissions: [
          Permission.write(Role.user(userId)),
          Permission.update(Role.user(userId)),
          Permission.delete(Role.user(userId)),
          Permission.read(Role.any())
        ],
        data: {"username": username},
      );
      return true;
    } on AppwriteException catch (e) {
      Utils.debLog(e);
      return false;
    }
  }

  ```
2. Read the list of usernames in the usernames collection 

```dart
  static Future<bool> checkUsername(
    Databases databases,
    String username,
  ) async {
    var documentList = await databases.listDocuments(
      databaseId: userDatabaseID,
      collectionId: usernameCollectionID,
      queries: [Query.equal('username', username)],
    );
    return true;
}
```
This is the json when Flutter Client is used to create a document 
```json
{
    "username": "shibakar786",
    "$id": "6350f1e19829f6f21940",
    "$createdAt": "2022-10-20T06:59:49.498+00:00",
    "$updatedAt": "2022-10-20T06:59:49.498+00:00",
    "$permissions": {
        "0": "update(\"user:6350f1e19829f6f21940\")",
        "1": "delete(\"user:6350f1e19829f6f21940\")",
        "4": "read(\"any\")"
    },
    "$collectionId": "634d7d09e65bbc4b37b6",
    "$databaseId": "634d7cac5a7a4ada2259"
}
```
This is the json when Appwrite Dashboard is used  to create a document 
```json
{
    "username": "test",
    "$id": "63515a3ae52b8d9be12a",
    "$createdAt": "2022-10-20T14:24:58.938+00:00",
    "$updatedAt": "2022-10-20T14:24:58.938+00:00",
    "$permissions": [
        "read(\"any\")",
        "update(\"any\")",
        "delete(\"any\")"
    ],
    "$collectionId": "634d7d09e65bbc4b37b6",
    "$databaseId": "634d7cac5a7a4ada2259"
}
```
### 👍 Expected behavior

List of Documets

### 👎 Actual Behavior

Error

```shell
Reloaded 1 of 1787 libraries in 1,813ms (compile: 46 ms, reload: 741 ms, reassemble: 845 ms).
E/flutter (15782): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'List<dynamic>'
E/flutter (15782): #0      new Document.fromMap
package:appwrite/…/models/document.dart:41
E/flutter (15782): appwrite/sdk-for-flutter#1      new DocumentList.fromMap.<anonymous closure>
package:appwrite/…/models/document_list.dart:20
E/flutter (15782): appwrite/sdk-for-flutter#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
E/flutter (15782): appwrite/sdk-for-flutter#3      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
E/flutter (15782): appwrite/sdk-for-flutter#4      new List.from (dart:core-patch/array_patch.dart:41:17)
E/flutter (15782): appwrite/sdk-for-flutter#5      new DocumentList.fromMap
package:appwrite/…/models/document_list.dart:20
E/flutter (15782): appwrite/sdk-for-flutter#6      Databases.listDocuments
package:appwrite/services/databases.dart:35
```

### 🎲 Appwrite version

Version 2.0.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Shiba-Kar, thanks for raising this issue! 🙏 We'll look into this, but for now, can you try to create without the write permission since you already specified update and delete:

```dart
       permissions: [
         Permission.update(Role.user(userId)),
         Permission.delete(Role.user(userId)),
         Permission.read(Role.any())
       ],
```

BTW, if everyone should be able to read every document, you can put the `Permission.read(Role.any())` permission on the collection and not pass any permissions as update and delete for the current user should be the default.

**Comment by Shiba-Kar** [comment]
What might have gone wrong ? I am using Appwrite ``v:1.0.3.501`` and ``appwrite: ^8.1.0`` in flutter and ``dart_appwrite: ^7.1.0`` in functions

**Comment by stnguyen90** [comment]
@Shiba-Kar there's a bug with including write with update or delete. Please try without write as I suggested.

**Comment by stnguyen90** [comment]
Although this no longer results in an error, we now have extra permissions stored. Passing in:

```json
[
    "read(\"user:steven\")",
    "write(\"user:steven\")",
    "update(\"user:steven\")",
    "delete(\"user:steven\")"
]
```

results in:

```json
[
    "read(\"user:steven\")",
    "update(\"user:steven\")",
    "delete(\"user:steven\")",
    "update(\"user:steven\")",
    "delete(\"user:steven\")"
]
```
