### ISSUE TITLE
🐛 Bug Report: appwrite-executor restarts when using external SMTP with credentials

### ISSUE THREAD

**Issue by sanderkollerie** [appwrite/appwrite#4676]
### 👟 Reproduction steps

When I put my SMTP credentials in the .env file The appwriter-executor keeps on restarting.

### 👍 Expected behavior

Mail must send and apprwrite-executor must run.

### 👎 Actual Behavior

The executor won't start and keeps on restarting.

```
Removing orphan runtimes...

Warning: Undefined variable $orchestration in /usr/src/code/app/executor.php on line 682

Warning: Undefined variable $orchestration in /usr/src/code/app/executor.php on line 682

Warning: Undefined variable $orchestration in /usr/src/code/app/executor.php on line 682

Warning: Undefined variable $orchestration in /usr/src/code/app/executor.php on line 695

Fatal error: Uncaught Utopia\Orchestration\Exception\Orchestration: Docker Error: WARNING! Your password will be stored unencrypted in /.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

 in /usr/src/code/vendor/utopia-php/orchestration/src/Orchestration/Adapter/DockerCLI.php:28
Stack trace:
#0 /usr/src/code/app/executor.php(60): Utopia\Orchestration\Adapter\DockerCLI->__construct('username is shown here', 'Password is shown here')
#1 @swoole-src/library/core/ConnectionPool.php(86): {closure}()
#2 @swoole-src/library/core/ConnectionPool.php(67): Swoole\ConnectionPool->make()
#3 /usr/src/code/app/executor.php(682): Swoole\ConnectionPool->put(NULL)
#4 {main}
  thrown in /usr/src/code/vendor/utopia-php/orchestration/src/Orchestration/Adapter/DockerCLI.php on line 28
[2022-11-15 11:39:11 #6.2]      ERROR   php_swoole_server_rshutdown() (ERRNO 503): Fatal error: Uncaught Utopia\Orchestration\Exception\Orchestration: Docker Error: WARNING! Your password will be stored unencrypted in /.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

 in /usr/src/code/vendor/utopia-php/orchestration/src/Orchestration/Adapter/DockerCLI.php:28
Stack trace:
#0 /usr/src/code/app/executor.php(60): Utopia\Orchestration\Adapter\DockerCLI->__construct('username is shown here', 'Password is shown here')
#1 @swoole-src/library/core/ConnectionPool.php(86): {closure}()
#2 @swoole-src/library/core/ConnectionPool.php(67): Swoole\ConnectionPool->make()
#3 /usr/src/code/app/executor.php(682): Swoole\ConnectionPool->put(NULL)
#4 {main}
  thrown in /usr/src/code/vendor/utopia-php/orchestration/src/Orchestration/Adapter/DockerCLI.php on line 28
```

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@sanderkollerie this seems really odd...Are you sure you only updated the `_APP_SMTP_*` env variables because there errors you're seeing are more related to the `DOCKERHUB_PULL_*` env variables?

**Comment by stnguyen90** [comment]
@sanderkollerie have you had a chance to check the environment variables I mentioned? Please note, I will need to close this soon if there is no activity.

**Comment by stnguyen90** [comment]
Closing due to inactivity
