### ISSUE TITLE
Server error after upgrade from 0.15.2 to 1.1

### ISSUE THREAD

**Issue by theMeysam** [appwrite/appwrite#4698]
Hi my dear friends. I upgrade my appwrite from 0.15.2 to 1.1 (did all steps from https://appwrite.io/docs/upgrade) but unfortunately within migrate process I get bellow errors: 

```
Starting Data Migration to version 1.1.0
[PDO] MySQL connection restarted
Migrating Project: Appwrite (console)
Migrating Collections
Migrating Collection "_metadata"
Migrating Collection "audit"
Migrating Collection "abuse"
Migrating Collection "databases"
Migrating Collection "collections"
Migrating Collection "attributes"
Migrating Collection "indexes"
Migrating Collection "projects"
'region' from projects: Invalid document structure: Attribute "$createdAt" has invalid type. Date is not valid
'_key_team' from projects: Invalid document structure: Attribute "$createdAt" has invalid type. Date is not valid
Migrating Collection "platforms"
Migrating Collection "domains"
Migrating Collection "keys"
Migrating Collection "webhooks"
Migrating Collection "users"
Migrating Collection "tokens"
Migrating Collection "sessions"
'expire' from sessions: Invalid document structure: Attribute "$createdAt" has invalid type. Date is not valid
Migrating Collection "teams"
Migrating Collection "memberships"
Migrating Collection "functions"
Migrating Collection "deployments"
Migrating Collection "builds"
Migrating Collection "executions"
Migrating Collection "certificates"
Migrating Collection "buckets"
Migrating Collection "stats"
Migrating Collection "realtime"
Migrating Collection "cache"
Migrating Collection "files"
Migrating Collection "variables"
Migrating Documents
Migrating Collection _metadata:
25 / 25
Migrating Collection audit:
18 / 18
Migrating Collection abuse:
100 / 2155
200 / 2155
300 / 2155
400 / 2155
500 / 2155
600 / 2155
700 / 2155
800 / 2155
900 / 2155
1000 / 2155
1100 / 2155
1200 / 2155
1300 / 2155
1400 / 2155
1500 / 2155
1600 / 2155
1700 / 2155
1800 / 2155
1900 / 2155
2000 / 2155
2100 / 2155
2155 / 2155 
Migrating Collection databases:
0 / 0
Migrating Collection attributes:
0 / 0
Migrating Collection indexes:
0 / 0
Migrating Collection projects:
1 / 1
Failed to update document: Invalid document structure: Unknown attribute: "region"
Migrating Collection platforms:
3 / 3
Migrating Collection domains:
1 / 1
Migrating Collection keys:
1 / 1
Migrating Collection webhooks:
0 / 0
Migrating Collection users:
1 / 1
Migrating Collection tokens:
0 / 0
Migrating Collection sessions:
11 / 11
Migrating Collection teams:
1 / 1
Migrating Collection memberships:
1 / 1
Migrating Collection functions:
0 / 0
Migrating Collection deployments:
0 / 0
Migrating Collection builds:
0 / 0
Migrating Collection executions:
0 / 0
Migrating Collection certificates:
1 / 1
Migrating Collection buckets:
1 / 1
Migrating Collection stats:
0 / 0
Migrating Collection realtime:
10 / 10
Migrating Collection cache:

Fatal error: Uncaught Exception: Collection not found in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php:1557
Stack trace:
#0 /usr/src/code/src/Appwrite/Migration/Migration.php(148): Utopia\Database\Database->count(Object(Utopia\Database\Document))
#1 /usr/src/code/src/Appwrite/Migration/Migration.php(112): Appwrite\Migration\Migration->documentsIterator('cache')
#2 {main}
  thrown in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php on line 1557
```
And now when I try to login to my console it show "Server error" and I can not login to my appwrite.😩
Can anyone please advice me?

**Comment by stnguyen90** [comment]
@theMeysam did you upgrade to the latest 1.0.x? If not, please try to:

1. restore back to 0.15.x
2. upgrade to the latest 1.0.x
3. run the migrate command
4. upgrade to 1.1.0
5. run the migrate command

**Comment by stnguyen90** [comment]
@theMeysam, have you have a chance to restore and try the upgrade again?

**Comment by stnguyen90** [comment]
Closing due to inactivity.
