### ISSUE TITLE
🐛 Bug Report: Appwrite 1.2.1 Function execution error "Cannot find module"

### ISSUE THREAD

**Issue by eugv86** [appwrite/appwrite#5320]
### 👟 Reproduction steps

Using appwrite CLI with following commands;
1. appwrite init function (Runtime: Node.js)
2. appwrite functions createDeployment --functionId="YOUR FUNCTION ID"--entrypoint='index.js' --code="." --activate=true

PS: no changes made to the template code that gets created following CLI commands 

### 👍 Expected behavior

Successful function execution

### 👎 Actual Behavior

Error: Cannot find module '/usr/code-start/index.js'
Require stack:
- /usr/local/src/server.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:81:25)
    at require (node:internal/modules/cjs/helpers:93:18)
    at /usr/local/src/server.js:55:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Docker does show that my container has exited with fatal error. Seems like that might be the culprit for me. Any ideas?

`2023-04-04 10:31:20 Fatal error: Uncaught Exception: Failed to connect to database: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Try again in /usr/src/code/app/http.php:77
2023-04-04 10:31:20 Stack trace:
2023-04-04 10:31:20 #0 {main}
2023-04-04 10:31:20   thrown in /usr/src/code/app/http.php on line 77
2023-04-04 10:31:20 [2023-04-04 15:31:20 #1.8]  ERROR   php_swoole_server_rshutdown() (ERRNO 503): Fatal error: Uncaught Exception: Failed to connect to database: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Try again in /usr/src/code/app/http.php:77
2023-04-04 10:31:20 Stack trace:
2023-04-04 10:31:20 #0 {main}
2023-04-04 10:31:20   thrown in /usr/src/code/app/http.php on line 77`

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by shaikahmadnawaz** [comment]
To resolve this issue, try the following steps:

1. Check the file path of your index.js file. Make sure that it is located in the root directory of your function deployment package.

2. Ensure that all the dependencies required by your function are included in the deployment package. You can check the dependencies by looking at the package.json file in the root directory of your function.

3. Make sure that you have specified the correct entrypoint file name in the --entrypoint flag while creating the function deployment. For example, if your entrypoint file is named main.js instead of index.js, you should specify --entrypoint='main.js' instead of --entrypoint='index.js'.

4. If you are still unable to resolve the issue, try rebuilding your function deployment package and creating a new deployment. You can do this by running the following command in the root directory of your function:

```
appwrite functions createDeployment --functionId="YOUR FUNCTION ID"--entrypoint='index.js' --code="." --activate=true
```

This command will rebuild your function deployment package and create a new deployment with the correct entrypoint file and dependencies.

Additionally, the error message also indicates that there is an issue connecting to the Appwrite database. You may want to verify that the database connection settings are correctly configured in your Appwrite server settings.

**Comment by eugv86** [comment]
@shaikahmadnawaz @joeyouss  Tried this at no avail, also completed deleted container and image and started from scratch with the same error result when executing a function.

**Comment by shaikahmadnawaz** [comment]
> @shaikahmadnawaz @joeyouss  Tried this at no avail, also completed deleted container and image and started from scratch with the same error result when executing a function. 

Ohhh, sorry for that.

**Comment by shaikahmadnawaz** [comment]
Great, thanks for informing ❤️

**Comment by SwaroopSambhayya** [comment]
Awesome! this helped me a lot! appwrite has to update their docs

**Comment by joeyouss** [comment]
CC @gewenyu99

**Comment by gewenyu99** [comment]
> I got it to work but looks like there were a few issues and the documentation might be wrong or unconcise.
> 
> 1. something was wrong with my database connection in docker (fixed it by completely re-creating the image and container)
> 2. @shaikahmadnawaz not sure why but appwrite seems to ignore the entry path inside package.json. so I explicitly set the entrypoint during deployment eg: **"src/index.js"** instead of leaving it as 'index.js' like the appwrite documentation suggests. Maybe there is something I'm not understanding but documentation also says that `"Library folders such as node_modules or vendor should not be included in your tarball "` If I do that then the function errors with `Cannot find module 'node-appwrite'`. So either the documentation is wrong or I'm not understanding it.
> 
> The folder structure that works for me:
> 
> ```
> functions/
> ├─ fnTest/
> │  ├─ node_modules/
> │  │  ├─ node-appwrite/
> │  ├─ src/
> │  │  ├─ index.js
> │  ├─ package.json
> ```
> 
> The deployment command:
> 
> ```
> appwrite functions createDeployment --functionId={ID}--entrypoint='src/index.js' --code="./functions/fntest" --activate=true
> ```

Yep, that's expected. You actually provide the entry path. **The entry point in package.json is ignored.**

You also **shouldn't include the node_modules folder**, Appwrite will use your package.json in the build step to install dependencies. Chances are there's something funky with your folder structure and how you tarballed your function.

You can use the CLI's function init command to generate a template and use the CLI to deploy the same function, and edit from there. This will prevent issues like incorrect folder structure and incorrectly zipping your files.

Thanks!

**Comment by joeyouss** [comment]
Hi @eugv86 , is this resolved now?

**Comment by Meldiron** [comment]
This has been an old bug, which is now resolved. I was able to create new function with Appwrite CLI, run it locally, and deploy it all with no issues.

If the problem persists for you, please reopen the issue and I will investigate your problem
