### ISSUE TITLE
Server Error: Invalid document structure: Unknown attribute: "region"

### ISSUE THREAD

**Issue by sunjianan9900** [appwrite/appwrite#5500]
I upgraded from 1.0.3 to 1.3.3,
```
docker run -it --rm \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --volume "$(pwd)"/appwrite:/usr/src/code/appwrite:rw \
    --entrypoint="install" \
    appwrite/appwrite:1.3.3
```

 and after the upgrade I used New Organization to get a server error, then I realized I forgot to do the migration, so I did the docker compose exec appwrite migrate command

```
cd appwrite/
docker compose exec appwrite migrate
```

Then my New Organization succeeded, but the next step to create project gave me a server error again
The error is as follows

```
Failed: Invalid document structure: Unknown attribute: "region"


#0 /usr/src/code/src/Appwrite/Usage/Calculators/TimeSeries.php(421): Utopia\Database\Database->createDocument(Object(Utopia\Database\Document), Object(Utopia\Database\Document))


#1 /usr/src/code/src/Appwrite/Usage/Calculators/TimeSeries.php(503): Appwrite\Usage\Calculators\TimeSeries->createOrUpdateMetric('1', '2023-05-04T00:0...', '1d', 'documents.63410...', 2, 0)


#2 /usr/src/code/src/Appwrite/Usage/Calculators/TimeSeries.php(528): Appwrite\Usage\Calculators\TimeSeries->syncFromInfluxDB('documents.datab...', Array, Array)


#3 /usr/src/code/app/tasks/usage.php(132): Appwrite\Usage\Calculators\TimeSeries->collect()


#4 /usr/src/code/vendor/utopia-php/cli/src/CLI/Console.php(208): {closure}()


#5 /usr/src/code/app/tasks/usage.php(137): Utopia\CLI\Console::loop(Object(Closure), 30)


#6 /usr/src/code/vendor/utopia-php/cli/src/CLI/CLI.php(233): {closure}()


#7 /usr/src/code/app/cli.php(32): Utopia\CLI\CLI->run()


#8 {main}
```

![image](https://user-images.githubusercontent.com/10936316/236098205-51b29392-ed21-4051-9ac9-c2dc22cfb5f4.png)

This is doctor

```
Checking for production best practices...
🔴 Hostname has no public suffix (localhost)
🟢 CNAME target has a public suffix (xxxxxxx)
🟢 Using a unique secret key for encryption
🟢 App environment is set for production
🟢 Abuse protection is enabled
🟢 Console access limits are enabled
🔴 HTTPS force option is disabled
🔴 Logging adapter is disabled

Checking connectivity...
Database............connected 👍
Queue...............connected 👍
Cache...............connected 👍
SMTP.............disconnected 👎
StatsD..............connected 👍
InfluxDB............connected 👍

Checking volumes...
🟢 Uploads Volume is readable
🟢 Uploads Volume is writeable
🟢 Cache Volume is readable
🟢 Cache Volume is writeable
🟢 Config Volume is readable
🟢 Config Volume is writeable
🟢 Certs Volume is readable
🟢 Certs Volume is writeable

Checking disk space usage...
🟢 Uploads Volume has 34.08GB free space (46.13% used)
🟢 Cache Volume has 34.08GB free space (46.13% used)
🟢 Config Volume has 34.08GB free space (46.13% used)
🟢 Certs Volume has 34.08GB free space (46.13% used)

A new version (1.3.3) is available! 🥳

```

**Comment by sunjianan9900** [comment]
```
docker compose exec appwrite migrate version=1.1.2
docker compose exec appwrite migrate version=1.2.1
docker compose exec appwrite migrate version=1.3.3
```
