### ISSUE TITLE
🐛 Bug Report: requests from chrome extensions is not supported by appwrite 

### ISSUE THREAD

**Issue by ashuvssut** [appwrite/appwrite#5576]
### 👟 Reproduction steps

1. Create a appwrite function or anything which uses websdk to call it (like requesting Accounts API)
2. request that AppWrite API.
3. It will return the following error

 ```
cloud.appwrite.io/v1/functions/646ddsd0afg7d29dsff04ed/executions:1 
        
Failed to load resource: the server responded with a status of 403 ()
AppwriteException: Unsupported platform`
...
...
...
onSubmit @ Popup.js:16850
```

### 👍 Expected behavior

It should acknowledge requests from chrome extension

### 👎 Actual Behavior

 I am developing a chrome extension which will send requests to Appwrite

The following is the `AppwriteException: Unsupported platform` when I called my function
 ```
cloud.appwrite.io/v1/functions/646ddsd0afg7d29dsff04ed/executions:1 
        
Failed to load resource: the server responded with a status of 403 ()
Popup.js:14760  AppwriteException: Unsupported platform
    at Client.<anonymous> (chrome-extension://ojahchgdfhgiecodieokahphpmicndba/assets/js/Popup.js:13494:17)
    at Generator.next (<anonymous>)
    at fulfilled (chrome-extension://ojahchgdfhgiecodieokahphpmicndba/assets/js/Popup.js:13224:24)
registerUser @ Popup.js:14760
Popup.js:16850  Error: AppwriteException: Unsupported platform
    at registerUser (Popup.js:14761:13)
    at async onSubmit (Popup.js:16848:20)
onSubmit @ Popup.js:16850
```

Same Error happens when I use Web SDK's Account API

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

appwrite websdk version: 11.0.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ashuvssut** [comment]
Having a setting to whitelist the "chrome-extension://<extension-id>" origin in the Appwrite project settings would be nice
