### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by manol-o** [appwrite/appwrite#5612]
### 👟 Reproduction steps

Build a appwrite function with this code:

```
const sdk = require("node-appwrite");

const config = {
  project: process.env.PROJECT,
  endpoint: process.env.ENDPOINT,
  endpoint: process.env.KEY,
};

module.exports = async (req, res) => {
  const client = new sdk.Client()
    .setEndpoint(config.endpoint)
    .setProject(process.env.APPWRITE_FUNCTION_PROJECT_ID)
    .setKey(config.key);

  const users = new sdk.Users(client);

  const promise = await users.get($SOME_USER);

  promise.then(
    function (response) {
      //...
    },
    function (error) {
      //..
    }
  );

  res.json({
    success: false,
    message: "whats going on here?",
  });
};

```
run the function (with $SOME_USER filled in)
API Key is set to be allowed to read users (Auth -> users.read)

### 👍 Expected behavior

the code should just successfully run so that we can go further in the promise function.

### 👎 Actual Behavior

response is

trigger : http
status : failed
statusCode : 500
response : 
stdout : 
stderr : Error: connect ECONNREFUSED 127.0.0.1:80
    at Client.call (/usr/code-start/node_modules/node-appwrite/lib/client.js:178:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Users.get (/usr/code-start/node_modules/node-appwrite/lib/services/users.js:549:16)
    at async module.exports (/usr/code-start/index.js:18:19)
    at async /usr/local/src/server.js:68:13
duration : 0.256274938583374

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by manol-o** [comment]
Btw I am using the server sdk because I need to auth a user for some other service... But with the user sdk I hit the rate limit because it comes from the same ip (internal ip from the server...). An option to turn off rate limiting only internally for functions would help much...

**Comment by manol-o** [comment]
I made also an FR here:
https://github.com/appwrite/appwrite/issues/5614
Somehow the bug mentioned seems to fight around the missing feature (disable Rate-limiting in functions context), because I cant check the user auth from a function (because of the same IP)

**Comment by manol-o** [comment]
this line
```
endpoint: process.env.KEY,
```
has to be 

```
key: process.env.KEY,
```
but now I'm getting
```
TypeError: promise.then is not a function
    at module.exports (/usr/code-start/index.js:102:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /usr/local/src/server.js:68:13
```

**Comment by manol-o** [comment]
ok also could fix this with the following line:
```
    const promise = await users.list().then( ...
```
So I will close the issue thanks for anyone reading my nice monolog ;) 

Anyway I'm working around just for the following issue:
https://github.com/appwrite/appwrite/issues/5614
Would be good to put this on list,
thanks for the good work btw dear appwrite team! I <3 appwrite!
