### ISSUE TITLE
🐛 Bug Report: `ali-oss` Doesn't Work in Node Runtime

### ISSUE THREAD

**Issue by wilhantian** [appwrite/appwrite#5642]
### 👟 Reproduction steps

I created a default function using cli, only adding the 'ali-oss' node dependency and not referencing it in the JS file (declared only in package. json). After deploying the function, prompt after execution: 
[Error] Type: Exception
[Error] Message: An internal curl error has occurred within the executor! Error Msg: Connection refused
[Error] File: /usr/src/code/app/executor.php
[Error] Line: 541

### 👍 Expected behavior

Unable to execute function

### 👎 Actual Behavior

Properly execute functions

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I use Appwrite 1.3.6，functions Node16.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Haimantika** [comment]
Hi @wilhantian 👋 did you check the appwrite-executor logs? What does it show?

**Comment by stnguyen90** [comment]
FYI, this was discussed on [Discord](https://discord.com/channels/564160730845151244/1114453293876387910).

As mentioned on Discord, I ran this manually using [Open Runtimes](https://github.com/open-runtimes/open-runtimes/tree/main/runtimes/node-18.0) and got the following error:

```
00:56:51 0|server  | TypeError: Cannot read properties of undefined (reading 'split')
00:56:51 0|server  |     at toIdentifier (/usr/local/src/node_modules/http-errors/index.js:257:14)
00:56:51 0|server  |     at forEachCode (/usr/local/src/node_modules/http-errors/index.js:228:16)
00:56:51 0|server  |     at Array.forEach (<anonymous>)
00:56:51 0|server  |     at populateConstructorExports (/usr/local/src/node_modules/http-errors/index.js:226:9)
00:56:51 0|server  |     at Object.<anonymous> (/usr/local/src/node_modules/http-errors/index.js:29:1)
00:56:51 0|server  |     at Module._compile (node:internal/modules/cjs/loader:1105:14)
00:56:51 0|server  |     at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
00:56:51 0|server  |     at Module.load (node:internal/modules/cjs/loader:981:32)
00:56:51 0|server  |     at Module._load (node:internal/modules/cjs/loader:827:12)
00:56:51 0|server  |     at Module.require (node:internal/modules/cjs/loader:1005:19)
```

It seems ali-oss modifies some libraries that causes some incompatibility with Open Runtimes.

**Comment by eldadfux** [comment]
@wilhantian is this still happening on newer version of Appwrite on the Node runtime?

**Comment by HarshMN2345** [comment]
No repro on this one and nothing since 2024-10-25, so there is nothing to go on. Closing. Happy to reopen if you can still hit it and post the steps.
