### ISSUE TITLE
🐛 Bug Report: [Python SDK] Optional parameter documentSecurity is required when creating a collection 

### ISSUE THREAD

**Issue by sheecegardezi** [appwrite/appwrite#5762]
### 👟 Reproduction steps

```
import logging
from appwrite.client import Client
from appwrite.services.teams import Teams
from appwrite.services.databases import Databases


# Setup logging
logging.basicConfig(level=logging.INFO)

# Create Appwrite client
client = Client()

client.set_endpoint('http://localhost/v1')\
      .set_project('clouddashbaord')\
      .set_key('******') 
logging.info("Appwrite client initialized.")


databases = Databases(client)
database_name = 'abc'
try:
  databases.create(database_name,database_name)
  logging.info(f"Database '{database_name}' created.")
except Exception as e:
    logging.warning(f"Database '{database_name}' already exists.")

collection_name = 'some_collection'
databases.create_collection(database_name, collection_name, collection_name,document_security=[])
```

### 👍 Expected behavior

According to the SDK documentation, documentSecurity should be optional when creating a collection. The collection should be created without any errors. Following code works fine:

```
import logging
from appwrite.client import Client
from appwrite.services.teams import Teams
from appwrite.services.databases import Databases


# Setup logging
logging.basicConfig(level=logging.INFO)

# Create Appwrite client
client = Client()

client.set_endpoint('http://localhost/v1')\
      .set_project('clouddashbaord')\
      .set_key('******') 
logging.info("Appwrite client initialized.")


databases = Databases(client)
database_name = 'abc'
try:
  databases.create(database_name,database_name)
  logging.info(f"Database '{database_name}' created.")
except Exception as e:
    logging.warning(f"Database '{database_name}' already exists.")

collection_name = 'some_collection'
databases.create_collection(database_name, collection_name, collection_name, document_security=False)
```

### 👎 Actual Behavior

When running the code without providing the documentSecurity parameter, it throws an error.

```
Traceback (most recent call last):
  File "~/.venv/lib/python3.10/site-packages/appwrite/client.py", line 97, in call
    response.raise_for_status()
  File "~/.venv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://localhost/v1/databases/clouddashboard/collections

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/appwrite/startup.py", line 39, in <module>
    databases.create_collection(database_name, 'premission3', 'premission3')
  File "~/.venv/lib/python3.10/site-packages/appwrite/services/databases.py", line 135, in create_collection
    return self.client.call('post', path, {
  File "~/.venv/lib/python3.10/site-packages/appwrite/client.py", line 109, in call
    raise AppwriteException(response.json()['message'], response.status_code, response.json().get('type'), response.json())
appwrite.exception.AppwriteException: Server Error
```
docker logs gives details:

```
(.venv) user@machine:$ docker logs appwrite
[Error] Timestamp: 2023-07-03T18:00:45+00:00
[Error] Method: POST
[Error] URL: /v1/databases/:databaseId/collections
[Error] Type: TypeError
[Error] Message: {closure}(): Argument #5 ($documentSecurity) must be of type bool, null given, called in /usr/src/code/vendor/utopia-php/framework/src/App.php on line 593
[Error] File: /usr/src/code/app/controllers/api/databases.php
[Error] Line: 720
```

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

local machine

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Haimantika** [comment]
Thanks for bringing this issue up @sheecegardezi . @gewenyu99 can you take a look?

**Comment by lohanidamodar** [comment]
@sheecegardezi Thank you for raising the issue, I was able to reproduce it. The issue seems to be because of poor null values handling on our part. We are actively working to fix this and will get back once we have something concrete.

**Comment by christyjacob4** [comment]
@sheecegardezi we have a PR open with the fix and it should be deployed soon 

https://github.com/appwrite/sdk-generator/pull/687

**Comment by sheecegardezi** [comment]
Thanks for looking into it @christyjacob4 https://github.com/appwrite/appwrite/issues/5761 is similar issue too.
