### ISSUE TITLE
🐛 Bug Report: on uploading images in appwrite storage bucket it showing this error

### ISSUE THREAD

**Issue by MyCoding331** [appwrite/appwrite#5771]
### On uploading images in appwrite storage bucket it showig this error

```
AppwriteException [Error]: Server Error
    at Client.call (C:\Users\smoiz\Desktop\moiz-work\api\pupeteer\node_modules\node-appwrite\lib\client.js:172:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async uploadChunk (C:\Users\smoiz\Desktop\moiz-work\api\pupeteer\node_modules\node-appwrite\lib\services\storage.js:370:24)
    at async Writable.<anonymous> (C:\Users\smoiz\Desktop\moiz-work\api\pupeteer\node_modules\node-appwrite\lib\services\storage.js:437:25) {
  code: 500,
  type: 'general_unknown',
  response: {
    message: 'Server Error',
    code: 500,
    type: 'general_unknown',
    version: '0.10.44'
  }
}
```

**Comment by Haimantika** [comment]
Hi, @MyCoding331 we will need more information to help you. If you need help with your code, the best place to get support-related queries answered is - https://appwrite.io/discord

**Comment by MyCoding331** [comment]
> > > I think iam getting this error was because the image was corrected after the change it worked...!!

**Comment by Haimantika** [comment]
Hi @MyCoding331 👋 Image upload is working fine for me. Are you still facing this error?

**Comment by MyCoding331** [comment]
Nah..!!! I got the solution
