### ISSUE TITLE
🐛 Bug Report: deleting a document with relationships can cause 500 error

### ISSUE THREAD

**Issue by t0mm4rx** [appwrite/appwrite#5850]
### 👟 Reproduction steps

Hello,

I have collection A with two one-way one-to-many relationship fields to collection B.
Collection A has value `Set NULL` for the `On deleting a document` property.
Example:
```js
{ $id: 'abc', $collectionId: 'a', 'profiles': [{$id: 'xyz', $collectionId: 'b'}, {$id: '123', $collectionId: 'b'}], 'profiles_archived': [{$id: 'xyz', $collectionId: 'b'}] }
```
I loop over documents and delete them using databases.deleteDocument.

1. When both of the fields contain no document, I get a 500 error and this error:
```
[Error] Method: DELETE
[Error] URL: /v1/databases/:databaseId/collections/:collectionId/documents/:documentId
[Error] Type: PDOException
[Error] Message: There is already an active transaction
[Error] File: @swoole-src/library/core/Database/PDOProxy.php
[Error] Line: 43
```

2. When one of the two fields is not empty (so it still has at least one relationship), I have this error:
```
[Error] Method: DELETE
[Error] URL: /v1/databases/:databaseId/collections/:collectionId/documents/:documentId
[Error] Type: Exception
[Error] Message: Unknown PDO Type for object
[Error] File: /usr/src/code/vendor/utopia-php/database/src/Database/Adapter/MariaDB.php
[Error] Line: 1347
```

### 👍 Expected behavior

We should be able to delete the document.

### 👎 Actual Behavior

It throws a 500 error.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Self-deployed 1.3.7.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by t0mm4rx** [comment]
I just reproduced the issue from a fresh Appwrite 1.3.7 install.

- create two relationship fields between A and B
- share some A docs between the two fields
- perform mass random operations on both A and B

Now I can't delete any documents from A without deleting all of its relationships from B.

Here is a backup of the demo I setup: https://drive.google.com/file/d/1QI3YN3Nze_rCXuzl8rKmMgUbcz42YJEv/view?usp=sharing

**Comment by fballan93** [comment]
This is happening to us too. bumping up

**Comment by Haimantika** [comment]
Thanks @t0mm4rx and @fballan93 for bringing this issue up. I have notified the team about it.

**Comment by Emilien-Lambert** [comment]
Same here with appwrite `1.3.8`

```
[Error] Timestamp: 2023-08-18T13:26:18+00:00
[Error] Method: DELETE
[Error] URL: /v1/databases/:databaseId/collections/:collectionId/documents/:documentId
[Error] Type: Exception
[Error] Message: Unknown PDO Type for object
[Error] File: /usr/src/code/vendor/utopia-php/database/src/Database/Adapter/MariaDB.php
[Error] Line: 1347
```

**Comment by t0mm4rx** [comment]
It seems that in **some** cases, updating the doc to remove all of its relationships and waiting a little bit before the deletion helps.

For example:
```js
// Remove relationships
await databases.update_document("db", "collection", "to_delete", {
profiles: [],
})

// Wait a little bit
await new Promise(resolve => setTimeout(resolve, 1000));

// Then remove the doc
await databases.delete_document("db", "collection", "to_delete")
```

**Comment by abnegate** [comment]
Hey @t0mm4rx, there were changes to the permissions logic relating to your issue in 1.4.x, are you still able to reproduce the in the latest version?

**Comment by mahyess** [comment]
@abnegate  Still exists in 1.4.1.

**Comment by abnegate** [comment]
@mahyess Thank you, I'll look into this further :+1:

**Comment by ItzNotABug** [comment]
`1.4.4` seems to be affected as well.

**Comment by Emilien-Lambert** [comment]
`1.4.9` Always affect, impossible to delete some documents that have a relationship

```Bash
[Error] Method: DELETE
[Error] URL: /v1/databases/:databaseId/collections/:collectionId/documents/:documentId
[Error] Type: Utopia\Database\Exception
[Error] Message: Unknown PDO Type for object
[Error] File: /usr/src/code/vendor/utopia-php/database/src/Database/Adapter/MariaDB.php
[Error] Line: 1562
```

This is really blocking me. Is there an alternative to delete a document manually in mariaDB maybe? 

![image](https://github.com/appwrite/appwrite/assets/52819523/ce2bd2b8-f7c7-471a-ae42-ae2666ad7523)

**Comment by stnguyen90** [comment]
> I also get a slightly different error when I try to delete another type of document that also has a Two-way relationship attributes.
> 
> I have this error :
> 
> [Error] Timestamp: 2023-08-18T14:49:55+00:00
> [Error] Method: DELETE
> [Error] URL: /v1/databases/:databaseId/collections/:collectionId/documents/:documentId
> [Error] Type: PDOException
> [Error] Message: Unknown column 'situations' in 'field list'
> [Error] File: @swoole-src/library/core/Database/PDOStatementProxy.php
> [Error] Line: 64

Like @Emilien-Lambert, here's another scenario:

appwrite.json:

```json
{
    "projectId": "[REPLACE WITH YOUR PROJECT ID]",
    "projectName": "Demo",
    "databases": [
        {
            "$id": "set-null",
            "name": "Set Null",
            "$createdAt": "2023-11-13T17:47:46.192+00:00",
            "$updatedAt": "2023-11-13T17:47:46.192+00:00",
            "enabled": true
        }
    ],
    "collections": [
        {
            "$id": "demo-1",
            "$permissions": [],
            "databaseId": "set-null",
            "name": "demo 1",
            "enabled": true,
            "documentSecurity": false,
            "attributes": [
                {
                    "key": "demo2",
                    "type": "relationship",
                    "status": "available",
                    "error": "",
                    "required": false,
                    "array": false,
                    "relatedCollection": "demo-2",
                    "relationType": "manyToMany",
                    "twoWay": true,
                    "twoWayKey": "demo1",
                    "onDelete": "setNull",
                    "side": "child"
                }
            ],
            "indexes": []
        },
        {
            "$id": "demo-2",
            "$permissions": [],
            "databaseId": "set-null",
            "name": "demo 2",
            "enabled": true,
            "documentSecurity": false,
            "attributes": [
                {
                    "key": "demo3",
                    "type": "relationship",
                    "status": "available",
                    "error": "",
                    "required": false,
                    "array": false,
                    "relatedCollection": "demo-3",
                    "relationType": "oneToMany",
                    "twoWay": true,
                    "twoWayKey": "demo2",
                    "onDelete": "setNull",
                    "side": "child"
                },
                {
                    "key": "demo1",
                    "type": "relationship",
                    "status": "available",
                    "error": "",
                    "required": false,
                    "array": false,
                    "relatedCollection": "demo-1",
                    "relationType": "manyToMany",
                    "twoWay": true,
                    "twoWayKey": "demo2",
                    "onDelete": "setNull",
                    "side": "parent"
                }
            ],
            "indexes": []
        },
        {
            "$id": "demo-3",
            "$permissions": [],
            "databaseId": "set-null",
            "name": "demo-3",
            "enabled": true,
            "documentSecurity": false,
            "attributes": [
                {
                    "key": "demo2",
                    "type": "relationship",
                    "status": "available",
                    "error": "",
                    "required": false,
                    "array": false,
                    "relatedCollection": "demo-2",
                    "relationType": "oneToMany",
                    "twoWay": true,
                    "twoWayKey": "demo3",
                    "onDelete": "setNull",
                    "side": "parent"
                }
            ],
            "indexes": []
        }
    ]
}
```

Then, create the documents:

```shell
appwrite databases createDocument --databaseId set-null --collectionId demo-3 --documentId demo-3 --data '{
    "demo2": [
        {
            "$id": "demo-2",
            "demo1": [
                {
                    "$id": "demo-1"
                }
            ]
        }
    ]
}'
```

Finally, try to delete demo-3:

```shell
appwrite databases deleteDocument --databaseId set-null --collectionId demo-3 --documentId demo-3
```

This results in ServerError with this in the stacktrace:

```
Unknown column 'demo1' in 'field list': null
#16 /usr/src/code/vendor/utopia-php/database/src/Database/Adapter/MariaDB.php(1044): __call
#15 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(3200): updateDocument
#14 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(4066): updateDocument
#13 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(475): Utopia\Database\{closure}
#12 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(4067): skipRelationships
#11 /usr/src/code/vendor/utopia-php/database/src/Database/Validator/Authorization.php(166): Utopia\Database\{closure}
#10 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(4068): skip
#9 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(3883): deleteSetNull
#8 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(3834): deleteDocumentRelationships
#7 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(456): Utopia\Database\{closure}
#6 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(3834): silent
#5 /usr/src/code/app/controllers/api/databases.php(3573): deleteDocument
#4 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(521): {closure}
#3 /usr/src/code/app/controllers/api/databases.php(3581): withRequestTimestamp
#2 /usr/src/code/vendor/utopia-php/framework/src/App.php(508): {closure}
#1 /usr/src/code/vendor/utopia-php/framework/src/App.php(673): execute
#0 /usr/src/code/app/http.php(253): run
```

**Comment by stnguyen90** [comment]
This should be fixed by https://github.com/utopia-php/database/pull/396 which was included in https://github.com/utopia-php/database/releases/tag/0.49.2, but that hasn't been released in any 1.5.x tag yet.

**Comment by stnguyen90** [comment]
Looks like this is still a problem:

```
appwrite  | [Error] Timestamp: 2024-04-25T18:08:08+00:00
appwrite  | [Error] Method: DELETE
appwrite  | [Error] URL: /v1/databases/:databaseId/collections/:collectionId/documents/:documentId
appwrite  | [Error] Type: PDOException
appwrite  | [Error] Message: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'demo1' in 'field list'
appwrite  | [Error] File: @swoole/library/core/Database/PDOStatementProxy.php
appwrite  | [Error] Line: 44
appwrite  | [Error] Type: Utopia\Exception
appwrite  | [Error] Message: Error handler had an error: Appwrite\Extend\Exception::__construct(): Argument #3 ($code) must be of type ?int, string given, called in /usr/src/code/app/controllers/general.php on line 712
appwrite  | [Error] File: /usr/src/code/vendor/utopia-php/framework/src/App.php
appwrite  | [Error] Line: 574
```

**Comment by stnguyen90** [comment]
Oh... https://github.com/appwrite/appwrite/pull/8006 wasn't merged yet.
