### ISSUE TITLE
🐛 Bug Report: select query in a relationship database

### ISSUE THREAD

**Issue by monofactory** [appwrite/appwrite#5880]
### 👟 Reproduction steps

 Query.select([
    "title",
    "category",
    "imageLinks",
    "uid",
    ...
    "users.*"  // relationship collection "users" All of the user's data is imported  
  ]),

### 👍 Expected behavior

Query.select([
    "title",
    "category",
    "imageLinks",
    "uid",
    ...
     "users.name" // Only the data I want ==> not working
  ]),

### 👎 Actual Behavior

AppwriteException: general_unknown, Server Error (500), #0      ClientMixin.prepareResponse (package:appwrite/src/client_mixin.dart:73:9)
#1      ClientIO.call (package:appwrite/src/client_io.dart:373:14)

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

appwrite 1.3.8

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by isaiah-banks** [comment]
I just ran into this issue the other day and, unfortunately, this is expected, for now at least. You cannot query relationships (see: https://appwrite.io/docs/databases-relationships#query. You have to select the entire row and parse from there. There might be a more clever way around that, but I haven't thought of one yet.

**Comment by joeyouss** [comment]
HI
Querying is currently not supported in relationships.

**Comment by joeyouss** [comment]
Hi @monofactory shall I close this issue if no additional help is required here?

**Comment by abnegate** [comment]
Hey @monofactory, is this still an issue for you in 1.4.x? If so, are you able to add the appwrite container logs here?

**Comment by fogelito** [comment]
hey @monofactory I am pretty sure, This should work... 
 Is this still an issue? 
 If this is on self-hosted, please provide logs, if it is on the cloud, please check after recent update
Thank a lot

**Comment by mattie-cmsp** [comment]
I wanted to chime in on this, as it relates to the FR I opened #7033 .

I'm affected by the same issue.  But, this is not a bug, this is an FR as the documentation and code states that the features required to resolve this need are potentially planned for a future release.

> [Queries](https://appwrite.io/docs/products/databases/relationships#queries)
Queries are currently not available in the experimental version of Appwrite Relationships but will be added in a later version.

I don't know if there is a place to track planned features like this one.  And as I've spent some time looking through the code for Appwrite and Utopia Database, I'd be willing to contribute code changes to both or either this issue and/or my interim FR.

**Comment by RedLeeder** [comment]
+1 For query support for relationships. I have a use case where I would love to have the ability to only have certain fields return for related documents.

**Comment by abnegate** [comment]
This is now supported via select queries on Appwrite Cloud
