### ISSUE TITLE
🐛 Bug Report: Create Team, List Teams exception when developing with flutter

### ISSUE THREAD

**Issue by csbok** [appwrite/appwrite#5980]
### 👟 Reproduction steps

1. Create anonymous user using the flutter sdk on client. `account.createAnonymousSession();`
2. Create a team using the flutter sdk on client. `teams.create(teamId: ID.unique(), name: 'test team',)`
3. The appwrite cloud dashboard shows that the team has been created, but `Unhandled Exception: type 'Null' is not a subtype of type 'Map<String, dynamic>'` exception occur.

```
  factory Team.fromMap(Map<String, dynamic> map) {
    return Team(
      $id: map['\$id'].toString(),
      $createdAt: map['\$createdAt'].toString(),
      $updatedAt: map['\$updatedAt'].toString(),
      name: map['name'].toString(),
      total: map['total'],
      prefs: Preferences.fromMap(map['prefs']), // here!
    );
  }
  ```
4. This exception is also thrown when calling List Teams. `teams.list();`

### 👍 Expected behavior

Create Team, List Teams exception should not be thrown.
Team::prefs should be not null and it will be Map<String, dynamic> map type.

### 👎 Actual Behavior

An exception occurs in the flutter client environment when calling Create Team, List Teams sdk code.
Below is the log from the flutter console.

```
`[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: type 'Null' is not a subtype of type 'Map<String, dynamic>'
#0      new Team.fromMap (package:appwrite/src/models/team.dart:39:37)
#1      Teams.create (package:appwrite/services/teams.dart:55:24)
<asynchronous suspension>
#2      TeamListScreen._createTeam (package:task/team/list.dart:36:20)
<asynchronous suspension>
#3      TeamListScreen._init (package:task/team/list.dart:10:5)
<asynchronous suspension>`
```

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Something else

### 🧱 Your Environment

flutter : 3.10.6
dart : 3.0.6
appwrite flutter sdk : 9.0.1
appwrite server : https://cloud.appwrite.io/v1
flutter running device : iOS Simulator (iOS 16.2) on Intel MacBook 2019

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by csbok** [comment]
I read this reply. https://github.com/appwrite/sdk-for-flutter/issues/162#issuecomment-1637043624
Appwrite Cloud is not yet compatible with Flutter SDK 9.0.1.
When I changed the Flutter SDK version to 8.3.0, it was solved and I close the issue.
