### ISSUE TITLE
🐛 Bug Report: After installing cli tryed to check version but getting error on all commands

### ISSUE THREAD

**Issue by ShridharBanavasi1997** [appwrite/appwrite#6089]
### 👟 Reproduction steps

Nott able to run any of teh apperite command after installing appwerite cli

on install i got like this :
```
 sudo npm install -g appwrite-cli

added 76 packages in 8s

16 packages are looking for funding
  run `npm fund` for details

```

### 👍 Expected behavior

Version number shoud have been displayed

### 👎 Actual Behavior

```
usr/local/lib/node_modules/appwrite-cli/lib/commands/assistant.js:13
const assistant = new Command("assistant").description(commandDescriptions['assistant']).configureHelp({
                                                                                         ^

TypeError: (intermediate value).description(...).configureHelp is not a function
    at Object.<anonymous> (/usr/local/lib/node_modules/appwrite-cli/lib/commands/assistant.js:13:90)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/appwrite-cli/index.js:18:23)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)

Node.js v18.17.1

```

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Linux mint

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by fballan93** [comment]
Im having the same exact error i tried on windows 11 , Macos sanoma , Macos ventura

**Comment by joeyouss** [comment]
Hi @ShridharBanavasi1997 , closing this in favor of https://github.com/appwrite/sdk-for-cli/issues/92

Please keep an eye on the linked issue for updates. Thank you for reporting this!
