### ISSUE TITLE
🐛 Bug Report: In Creating Team in Kotlin Android 

### ISSUE THREAD

**Issue by neerajkumarSenior** [appwrite/appwrite#6093]
### 👟 Reproduction steps

FATAL EXCEPTION: OkHttp Dispatcher
                                                                                                    Process: com.example.myapplication, PID: 17060
                                                                                                    java.lang.NullPointerException: null cannot be cast to non-null type kotlin.collections.Map<kotlin.String, kotlin.Any>
                                                                                                    	at io.appwrite.models.Team$Companion.from(Team.kt:83)
                                                                                                    	at io.appwrite.services.Teams$create$converter$1.invoke(Teams.kt:103)
                                                                                                    	at io.appwrite.services.Teams$create$converter$1.invoke(Teams.kt:102)
                                                                                                    	at io.appwrite.Client$awaitResponse$2$1.onResponse(Client.kt:533)
                                                                                                    	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)

### 👍 Expected behavior

![Screenshot 2023-08-31 185240](https://github.com/appwrite/appwrite/assets/113840005/3afc4465-929a-4f7f-a1aa-ed2cdce71ff3)

### 👎 Actual Behavior

![Screenshot 22](https://github.com/appwrite/appwrite/assets/113840005/67ca743e-810b-48f6-8ded-e3238d39ac50)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

we are creating simple app in kotlin android native using appwrite cloud  data addess succed in team  but our app is crash 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by neerajkumarSenior** [comment]
we are creating simple app in kotlin android native using appwrite cloud data added succeed in team but our app is crash 
![Screenshot 33](https://github.com/appwrite/appwrite/assets/113840005/cc43f315-395a-48d8-8ec9-f046774ed5a4)

**Comment by stnguyen90** [comment]
@neerajkumarSenior, thanks for creating this issue! 🙏🏼 What version of the Android SDK are you using?

**Comment by neerajkumarSenior** [comment]
What version of the Android SDK are you using?
we are using both version of android sdk 2 or 3 latest

**Comment by stnguyen90** [comment]
@neerajkumarSenior Version 2 of the Appwrite Android SDK is meant for Appwrite version 1.3. Cloud is on 1.1.2 so would you please try using [Version 1.1.0](https://github.com/appwrite/sdk-for-android/tree/1.1.0) of the SDK?

**Comment by neerajkumarSenior** [comment]
thanks for that it's working now...
