### ISSUE TITLE
Ensure collections with datetime attributes are migrated

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#6176]
### 👟 Reproduction steps

1. Create a collection with a datetime attribute
2. Migrate that project

### 👍 Expected behavior

The collection is migrated

### 👎 Actual Behavior

Collection is not migrated

Docker logs: 

```
appwrite-worker-migrations  | Unknown attribute type: datetime
appwrite-worker-migrations  | Unknown attribute type: datetime
appwrite-worker-migrations  | #0 /usr/src/code/vendor/utopia-php/migration/src/Migration/Sources/Appwrite.php(783): Utopia\Migration\Sources\Appwrite->convertAttribute(Array, Object(Utopia\Migration\Resources\Database\Collection))
appwrite-worker-migrations  | #1 /usr/src/code/vendor/utopia-php/migration/src/Migration/Sources/Appwrite.php(431): Utopia\Migration\Sources\Appwrite->exportAttributes(100)
appwrite-worker-migrations  | #2 /usr/src/code/vendor/utopia-php/migration/src/Migration/Source.php(76): Utopia\Migration\Sources\Appwrite->exportGroupDatabases(100, Array)
appwrite-worker-migrations  | #3 /usr/src/code/vendor/utopia-php/migration/src/Migration/Source.php(39): Utopia\Migration\Source->exportResources(Array, 100)
appwrite-worker-migrations  | #4 /usr/src/code/vendor/utopia-php/migration/src/Migration/Destination.php(37): Utopia\Migration\Source->run(Array, Object(Closure))
appwrite-worker-migrations  | #5 /usr/src/code/vendor/utopia-php/migration/src/Migration/Transfer.php(147): Utopia\Migration\Destination->run(Array, Object(Closure), Object(Utopia\Migration\Sources\Appwrite))
appwrite-worker-migrations  | #6 /usr/src/code/app/workers/migrations.php(243): Utopia\Migration\Transfer->run(Array, Object(Closure))
appwrite-worker-migrations  | #7 /usr/src/code/app/workers/migrations.php(65): MigrationsV1->processMigration()
appwrite-worker-migrations  | #8 /usr/src/code/src/Appwrite/Resque/Worker.php(125): MigrationsV1->run()
appwrite-worker-migrations  | #9 /usr/src/code/vendor/resque/php-resque/lib/Resque/Job.php(201): Appwrite\Resque\Worker->perform()
appwrite-worker-migrations  | #10 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(303): Resque_Job->perform()
appwrite-worker-migrations  | #11 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(242): Resque_Worker->perform(Object(Resque_Job))
appwrite-worker-migrations  | #12 /usr/src/code/vendor/resque/php-resque/bin/resque(185): Resque_Worker->work('0.1', false)
appwrite-worker-migrations  | #13 {main}
```

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Tested on commit [c6530eff3b9088cc898b32a98e25402f8f6af21d](https://github.com/appwrite/appwrite/tree/c6530eff3b9088cc898b32a98e25402f8f6af21d) of 1.4.x branch and tried to migrate a 1.3.8 project

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Tasks:

* [ ] https://github.com/utopia-php/migration/pull/17
* [ ] Bump in Appwrite
