### ISSUE TITLE
🐛 Bug Report: Unable to Delete the project tables from DB when Project is deleted from Console

### ISSUE THREAD

**Issue by punitdiwan** [appwrite/appwrite#6252]
### 👟 Reproduction steps

I installed a fresh Appwrite Instance and added a domain and SSL has been generated. 

I have created a new project and added Web integration. 

Then I went to Project Settings and deleted the project. The Project is deleted from the Console. 

I waited two minutes so that I give enough time `appwrite-worker-delete` workers to get executed.

I logged into  `appwrite-mariadb` container  and did `SHOW TABLES` in `appwrite` database and I can see all the tables there. 

Main Error Msg from Log:
================

> Utopia\Database\Exception: Collection "domains" not found in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php:4053

Here is the complete Log from `appwrite-worker-deletes`:

```
[critical] (Job{v1-deletes} | ID: bcad93b55474b31614efd449e4be7281 | DeletesV1 | [{"project":{"$id":"console","$internalId":"console","name":"Appwrite","$collection":"projects","description":"Appwrite core engine","logo":"","teamId":-1,"webhooks":[],"keys":[],"platforms":[{"$collection":"platforms","name":"Localhost","type":"web","hostname":"localhost"},{"$collection":"platforms","name":"Current Host","type":"web","hostname":"awtest.maitretech.com"}],"legalName":"","legalCountry":"","legalState":"","legalCity":"","legalAddress":"","legalTaxId":"","auths":{"invites":true,"limit":1,"duration":31536000},"authWhitelistEmails":[],"authWhitelistIPs":[],"authProviders":{"githubEnabled":true,"githubSecret":"","githubAppid":""}},"type":"document","document":{"teamInternalId":"1","teamId":"650441186bedc466112d","name":"welcome","region":"default","description":"","database":"database_db_main","logo":"","url":"","version":"1.4.2","legalName":"","legalCountry":"","legalState":"","legalCity":"","legalAddress":"","legalTaxId":"","services":[],"smtp":[],"templates":[],"auths":{"limit":0,"maxSessions":10,"passwordHistory":0,"passwordDictionary":false,"duration":31536000,"personalDataCheck":false,"emailPassword":true,"usersAuthMagicURL":true,"anonymous":true,"invites":true,"JWT":true,"phone":true},"authProviders":[],"platforms":[{"projectInternalId":"2","projectId":"welcome","type":"web","name":"web","key":"","store":"","hostname":"*","$id":"65044237d198833f166d","$internalId":"2","$createdAt":"2023-09-15T11:38:31.858+00:00","$updatedAt":"2023-09-15T11:38:38.616+00:00","$permissions":["read(\"any\")","update(\"any\")","delete(\"any\")"],"$collection":"platforms"}],"webhooks":[],"keys":[],"search":"welcome welcome","$internalId":"2","$id":"welcome","$createdAt":"2023-09-15T11:38:21.481+00:00","$updatedAt":"2023-09-15T11:38:21.481+00:00","$permissions":["read(\"team:650441186bedc466112d\")","update(\"team:650441186bedc466112d\/owner\")","update(\"team:650441186bedc466112d\/developer\")","delete(\"team:650441186bedc466112d\/owner\")","delete(\"team:650441186bedc466112d\/developer\")"],"$collection":"projects"},"resource":null,"datetime":null,"hourlyUsageRetentionDatetime":null}]) has failed Utopia\Database\Exception: Collection "domains" not found in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php:4053
Stack trace:
#0 /usr/src/code/app/workers/deletes.php(373): Utopia\Database\Database->find(Object(Utopia\Database\Document), Array)
#1 /usr/src/code/app/workers/deletes.php(50): DeletesV1->deleteProject(Object(Utopia\Database\Document))
#2 /usr/src/code/src/Appwrite/Resque/Worker.php(125): DeletesV1->run()
#3 /usr/src/code/vendor/resque/php-resque/lib/Resque/Job.php(201): Appwrite\Resque\Worker->perform()
#4 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(303): Resque_Job->perform()
#5 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(242): Resque_Worker->perform(Object(Resque_Job))
#6 /usr/src/code/vendor/resque/php-resque/bin/resque(185): Resque_Worker->work('1', false)
#7 {main}
```

### 👍 Expected behavior

`appwrite-worker-deletes` should delete all the tables from the database 

### 👎 Actual Behavior

Project Tables are not deleted from the backend database and delete worked throws an error mentioned in **Reproduction Steps** Section. 

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite  Versions: 1.4.1 and 1.4.2 (Checked on both Versions after clearing volumes properly)
Remote Server OS: Linux
Used From: Web Console
Host OS: Windows 10 where the web console is opened. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@punitdiwan, thanks for raising this! We'll look into this soon!

For reference, the Discord thread: https://discord.com/channels/564160730845151244/1152174829496184882
