### ISSUE TITLE
🐛 Bug Report: [Functions] Function Fails Without Logs If No Body is Provided

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/appwrite#6431]
### 👟 Reproduction steps

1. Execute a Function from the Dashboard
2. Enter the Header as `Content-Type: application/json`
3. Leave the `Body` empty.

Function's execution will fail with no logs, no errors.

---
Issue caused by - 
```js
if (contentType.includes('application/json')) {
    body = await parseJson(req);
}
```
Logs from container - 
```bash
Error: Invalid JSON
08:36:01 0|server  |     at createError (/usr/local/server/node_modules/micro/lib/index.js:20:14)
08:36:01 0|server  |     at parseJSON (/usr/local/server/node_modules/micro/lib/index.js:120:9)
08:36:01 0|server  |     at /usr/local/server/node_modules/micro/lib/index.js:158:39
08:36:01 0|server  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
08:36:01 0|server  |     at async /usr/local/server/src/server.js:31:16
```

### 👍 Expected behavior

If the body doesn't exist, or empty then -
1. Crash with an error
2. Ignore & process the function as is

### 👎 Actual Behavior

Execution fails without any error.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by sundaram2021** [comment]
hey @ItzNotABug  can you help me produce this error

**Comment by Emeka212** [comment]
> hey @ItzNotABug can you help me produce this error

Step to reproduce
--
1. Create a sample node.js function
2. upload the function to the appwrite console
3. Run the function directly from the appwrite console
4. While running the function don't pass in a body value, just leave it empty.
5. Check the function log, and see it output.

Actual behaviour
--
Execution fails without any error.

Expected behaviour
--
Function should run but then only fail after note reading the json value for the json response, e.g (req.bodyRaw.value)

**Comment by stnguyen90** [comment]
@ItzNotABug you said the actual behavior is:

> Execution fails without any error.

What exactly shows in Appwrite for the execution (including the logs and errors)?

**Comment by ItzNotABug** [comment]
@stnguyen90 Nothing shows up in Logs or Errors tab, the status just shows `failed`.

**Comment by Meldiron** [comment]
Logging has been reworked in OpenRuntimes, and we are no longer getting reports about this problem, so I am marking as resolved.
Feel free to reopen, or open new issue, if you are still able to reproduce this problem.
