### ISSUE TITLE
🐛 Bug Report: Certificate for custom domain not generated due to error

### ISSUE THREAD

**Issue by maendamedia** [appwrite/appwrite#6913]
### 👟 Reproduction steps

Added a custom domain using the dashboard and added cname for that into the dns.
Domain is verified successfully by Appwrite. But ssl is not generated

Error in logs:

```
appwrite-worker-certificates  | [notice] Starting work on (Job{v1-certificates} | ID: 33193cc6c22754d68d3db465494555f7 | CertificatesV1 | [{"project":null,"domain":{"domain":"sub.mydomain.com"},"skipRenewCheck":true}])
appwrite-worker-certificates  | [critical] (Job{v1-certificates} | ID: 33193cc6c22754d68d3db465494555f7 | CertificatesV1 | [{"project":null,"domain":{"domain":"sub.mydomain.com"},"skipRenewCheck":true}]) has failed Utopia\Database\Exception\Structure: Invalid document structure: Unknown attribute: "log" in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php:2504
appwrite-worker-certificates  | Stack trace:
appwrite-worker-certificates  | #0 /usr/src/code/app/workers/certificates.php(171): Utopia\Database\Database->createDocument(Object(Utopia\Database\Document), Object(Utopia\Database\Document))
appwrite-worker-certificates  | #1 /usr/src/code/app/workers/certificates.php(145): CertificatesV1->saveCertificateDocument('sub.my...', Object(Utopia\Database\Document))
appwrite-worker-certificates  | #2 /usr/src/code/src/Appwrite/Resque/Worker.php(122): CertificatesV1->run()
appwrite-worker-certificates  | #3 /usr/src/code/vendor/resque/php-resque/lib/Resque/Job.php(201): Appwrite\Resque\Worker->perform()
appwrite-worker-certificates  | #4 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(303): Resque_Job->perform()
appwrite-worker-certificates  | #5 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(242): Resque_Worker->perform(Object(Resque_Job))
appwrite-worker-certificates  | #6 /usr/src/code/vendor/resque/php-resque/bin/resque(185): Resque_Worker->work('1', false)
```

### 👍 Expected behavior

Generate ssl for custom domain

### 👎 Actual Behavior

It gives error on ssl generating part

```
appwrite-worker-certificates  | [notice] Starting work on (Job{v1-certificates} | ID: 33193cc6c22754d68d3db465494555f7 | CertificatesV1 | [{"project":null,"domain":{"domain":"sub.mydomain.com"},"skipRenewCheck":true}])
appwrite-worker-certificates  | [critical] (Job{v1-certificates} | ID: 33193cc6c22754d68d3db465494555f7 | CertificatesV1 | [{"project":null,"domain":{"domain":"sub.mydomain.com"},"skipRenewCheck":true}]) has failed Utopia\Database\Exception\Structure: Invalid document structure: Unknown attribute: "log" in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php:2504
appwrite-worker-certificates  | Stack trace:
appwrite-worker-certificates  | #0 /usr/src/code/app/workers/certificates.php(171): Utopia\Database\Database->createDocument(Object(Utopia\Database\Document), Object(Utopia\Database\Document))
appwrite-worker-certificates  | #1 /usr/src/code/app/workers/certificates.php(145): CertificatesV1->saveCertificateDocument('sub.my...', Object(Utopia\Database\Document))
appwrite-worker-certificates  | #2 /usr/src/code/src/Appwrite/Resque/Worker.php(122): CertificatesV1->run()
appwrite-worker-certificates  | #3 /usr/src/code/vendor/resque/php-resque/lib/Resque/Job.php(201): Appwrite\Resque\Worker->perform()
appwrite-worker-certificates  | #4 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(303): Resque_Job->perform()
appwrite-worker-certificates  | #5 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(242): Resque_Worker->perform(Object(Resque_Job))
appwrite-worker-certificates  | #6 /usr/src/code/vendor/resque/php-resque/bin/resque(185): Resque_Worker->work('1', false)
```

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

1.4.5
No extra configs

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by adarsh-jha-dev** [comment]
@maendamedia  can you please assign this to me?

**Comment by maendamedia** [comment]
> you please assign this to me and I will come up with some solution.

Where do you want me to assign you too?

**Comment by stnguyen90** [comment]
@maendamedia, thanks for creating this issue! 🙏🏼 Did you upgrade to 1.4.5 or did you have a clean install?

**Comment by maendamedia** [comment]
> @maendamedia, thanks for creating this issue! 🙏🏼 Did you upgrade to 1.4.5 or did you have a clean install?

I upgraded from 1.4.4 to 1.4.5. Altough I still have the upgrade issue in my other issue :)

**Comment by maendamedia** [comment]
@stnguyen90  Any idea how to fix this?

**Comment by stnguyen90** [comment]
> I upgraded from 1.4.4 to 1.4.5. Altough I still have the upgrade issue in my other issue :)

So, you had a clean install of 1.4.4?

**Comment by eldadfux** [comment]
Closing due to inactivity
