### ISSUE TITLE
🐛 Bug Report: Query.search throw an error while searching for name in user api

### ISSUE THREAD

**Issue by vuggy17** [appwrite/appwrite#7237]
### 👟 Reproduction steps

1. Create a user with cloud console
2. Search for that user using: `users.list([Query.search('name', <your query>);`

### 👍 Expected behavior

It does not throw any error

### 👎 Actual Behavior

Logging from server: 

```
AppwriteException [Error]: Server Error
    at Client.call (E:\projects\idle\node_modules\.pnpm\node-appwrite@11.0.0\node_modules\node-appwrite\lib\client.js:174:31)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Users.list (E:\projects\idle\node_modules\.pnpm\node-appwrite@11.0.0\node_modules\node-appwrite\lib\services\users.js:40:16)
    at UserService.getUserSearchSuggestions (E:\projects\idle\dist\apps\idle.api\webpack:\src\modules\user\user.service.ts:10:15)
    at UserController.getUserSearchSuggestions (E:\projects\idle\dist\apps\idle.api\webpack:\src\modules\user\user.controller.ts:17:23)
    at E:\projects\idle\node_modules\.pnpm\@nestjs+core@10.0.2_@nestjs+common@10.0.2_@nestjs+platform-express@10.0.2_reflect-metadata@0.1.13_rxjs@7.8.0\node_modules\@nestjs\core\router\router-execution-context.js:46:28
    at E:\projects\idle\node_modules\.pnpm\@nestjs+core@10.0.2_@nestjs+common@10.0.2_@nestjs+platform-express@10.0.2_reflect-metadata@0.1.13_rxjs@7.8.0\node_modules\@nestjs\core\router\router-proxy.js:9:17 {       
  code: 500,
  type: 'general_unknown',
  response: {
    message: 'Server Error',
    code: 500,
    type: 'general_unknown',
    version: '0.11.38'
  }
}
```

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

- I'm using appwrite-node sdk: `"node-appwrite": "^11.0.0"`
- There is no customization

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by zdanl** [comment]
i just reported something to security@appwrite.io but now i'm having a similiar issue, in the same line of code that also displayed the security issue.

this is the bug, i think it originates inside the Server SDK

```
API listening on port 3000
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Error! Invalid address format".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v21.3.0
```

the corresponding code is 

```
 82   var docs = [];
 83   try {
 84   docs = await databases.listDocuments('cryptfire', 'api', [
 85     sdk.Query.equal('key', apikey)
 86   ]);
 87   } catch (err) {
 88     console.log('database error: ' + err);
 89   }
 90   
 91   console.log(docs);
```

what is a search param, plz?
