### ISSUE TITLE
🐛 Bug Report: Cannot query for relation field in a document

### ISSUE THREAD

**Issue by vuggy17** [appwrite/appwrite#7302]
### 👟 Reproduction steps

- Create a document using App write console
![image](https://github.com/appwrite/appwrite/assets/61084329/28e780c7-42e8-445a-8bd7-63205b8003ea)

- Query for that document using node-appwrite sdk
```
  async getMyRooms(myId: string) {
    try {
      const { documents } =
        await this.appwriteAdmin.database.listDocuments(
          AppWriteProvider.defaultDatabaseId, // "<my database id>"
          AppWriteProvider.projectDbCollections.chat.room, // "rooms"
          [Query.equal('members', [myId])],
        );

      return documents.map((doc) => new RoomEntity(doc));
    } catch (error) {
      console.log(error);
    }
  }
```

### 👍 Expected behavior

- Document returned and not raise an error

### 👎 Actual Behavior

- An error raised

In backend console: 
```
AppwriteException [Error]: Server Error
    at Client.call (E:\projects\idle\node_modules\.pnpm\node-appwrite@11.0.0\node_modules\node-appwrite\lib\client.js:174:31)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Databases.listDocuments (E:\projects\idle\node_modules\.pnpm\node-appwrite@11.0.0\node_modules\node-appwrite\lib\services\databases.js:1638:16)
    at RoomRepositoryImpl.getMyRooms (E:\projects\idle\dist\apps\idle.api\webpack:\src\modules\room\repository.ts:45:9) {
  code: 500,
  type: 'general_unknown',
  response: {
    message: 'Server Error',
    code: 500,
    type: 'general_unknown',
    version: '1.4.13'
  }
}

```

In docker, using `docker logs appwrite`
```
[Error] Method: GET
[Error] URL: /v1/databases/:databaseId/collections/:collectionId/documents
[Error] Type: PDOException
[Error] Message: Unknown column 'members' in 'where clause'
[Error] File: @swoole-src/library/core/Database/PDOStatementProxy.php
[Error] Line: 62
```

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Windows

### 🧱 Your Environment

I'm using 
`"node-appwrite": "^11.0.0",`

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by vuggy17** [comment]
Here is my collection attributes
![image](https://github.com/appwrite/appwrite/assets/61084329/728340ad-afbc-447c-a809-4112d44584c4)

![image](https://github.com/appwrite/appwrite/assets/61084329/686a2740-0cf6-4809-8486-26be2f811f5f)

**Comment by gepd** [comment]
Currently there is no support for queries with relationships

https://appwrite.io/docs/products/databases/relationships#queries

**Comment by vuggy17** [comment]
@gepd, thank you for spending your time, 
Is there any chance query works on fields which is not an array? I notice that the following snippet won't throw.

```
 async findFriendRequest(
    sender: ID,
    receiver: ID,
  ): Promise<FriendRequestEntity | null> {
    const { total, documents } =
      await this._appwriteAdmin.database.listDocuments(
        AppWriteProvider.defaultDatabaseId, // <my database id>
        AppWriteProvider.projectDbCollections.chat.friendInvitation, // friend-invitations 
        [Query.equal('receiver', receiver), Query.equal('sender', sender)],
      );

    if (total === 0) {
      return null;
    }
    return new FriendRequestEntity(documents[0]);
  }
```

Here is the collection: 
![image](https://github.com/appwrite/appwrite/assets/61084329/a3557971-2846-434f-a923-bc7d91c8cea4)


![image](https://github.com/appwrite/appwrite/assets/61084329/d432d054-ad85-4d18-91da-68bf99fbf239)

![image](https://github.com/appwrite/appwrite/assets/61084329/b2224669-5b2b-45fd-9a20-9d923fd2fc5f)

**Comment by stnguyen90** [comment]
Appwrite Cloud now supports [relationship queries](https://appwrite.io/changelog/entry/2026-02-06). This feature will be included in the next self-hosted release.
