### ISSUE TITLE
🐛 Bug Report: Failed to create connection in webhooks container

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#7844]
### 👟 Reproduction steps

1. Start a 1.5.x version of Appwrite
2. Trigger an event
3. Look at the docker logs of the webhooks container

### 👍 Expected behavior

No errors

### 👎 Actual Behavior

Errors:

```
gitpod /workspace/integration-for-gitpod (main) $ docker compose logs -f appwrite-worker-webhooks
appwrite-worker-webhooks  | [Worker] Worker 0 is ready!
appwrite-worker-webhooks  | Worker webhooks  started
appwrite-worker-webhooks  | [Job] Received Job (65f9b33aae8c45.62247897).
appwrite-worker-webhooks  | [Job] (65f9b33aae8c45.62247897) failed to run.
appwrite-worker-webhooks  | [Job] (65f9b33aae8c45.62247897) Failed to create connection: SQLSTATE[HY000] [1045] Access denied for user ''@'172.18.0.16' (using password: NO)
appwrite-worker-webhooks  | 
appwrite-worker-webhooks  | Fatal error: Uncaught Exception: Failed to create connection: SQLSTATE[HY000] [1045] Access denied for user ''@'172.18.0.16' (using password: NO) in /usr/src/code/vendor/utopia-php/pools/src/Pools/Pool.php:193
appwrite-worker-webhooks  | Stack trace:
appwrite-worker-webhooks  | #0 /usr/src/code/app/worker.php(48): Utopia\Pools\Pool->pop()
appwrite-worker-webhooks  | #1 /usr/src/code/vendor/utopia-php/queue/src/Queue/Server.php(99): {closure}(Object(Utopia\Cache\Cache), Object(Utopia\Registry\Registry))
appwrite-worker-webhooks  | #2 /usr/src/code/vendor/utopia-php/queue/src/Queue/Server.php(119): Utopia\Queue\Server->getResource('dbForConsole')
appwrite-worker-webhooks  | #3 /usr/src/code/vendor/utopia-php/queue/src/Queue/Server.php(99): Utopia\Queue\Server->getResources(Array)
appwrite-worker-webhooks  | #4 /usr/src/code/vendor/utopia-php/queue/src/Queue/Server.php(388): Utopia\Queue\Server->getResource('project')
appwrite-worker-webhooks  | #5 /usr/src/code/vendor/utopia-php/queue/src/Queue/Server.php(295): Utopia\Queue\Server->getArguments(Object(Utopia\Hook))
appwrite-worker-webhooks  | #6 [internal function]: Utopia\Queue\Server->Utopia\Queue\{closure}('0')
appwrite-worker-webhooks  | #7 /usr/src/code/vendor/utopia-php/queue/src/Queue/Adapter/Swoole.php(37): call_user_func(Object(Closure), '0')
appwrite-worker-webhooks  | #8 [internal function]: Utopia\Queue\Adapter\Swoole->Utopia\Queue\Adapter\{closure}(Object(Swoole\Process\Pool), '0')
appwrite-worker-webhooks  | #9 {main}
appwrite-worker-webhooks  |   thrown in /usr/src/code/vendor/utopia-php/pools/src/Pools/Pool.php on line 193
```

Related: https://discord.com/channels/564160730845151244/1217133084302901288

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
It seems like the webhooks container is missing the DB env vars:

https://github.com/appwrite/appwrite/blob/7392e5bc5d470bb77f497344d26622948e2e7b94/app/views/install/compose.phtml#L251-L260

**Comment by eldadfux** [comment]
Fixed at https://github.com/appwrite/appwrite/pull/7848
