### ISSUE TITLE
🐛 Bug Report: Using deleteMfaAuthenticator causes Error

### ISSUE THREAD

**Issue by laurencetroyv** [appwrite/appwrite#8004]
### 👟 Reproduction steps

`deleteMfaAuthenticator` will cause an Unhandled Exception
```dart
class MultiFactorAuthenticationDataSource {
  final Account _account;

  MultiFactorAuthenticationDataSource() : _account = Account(client);

  /// Disable authenticator app
  Future<void> disableAuthenticatorApp(String otp) async {
    try {
      // delete authenticator app
      await _account.deleteMfaAuthenticator(
        otp: otp,
        type: AuthenticatorType.totp,
      );

      // update user mfa status to false
      await _account.updateMFA(mfa: false);
    } on AppwriteException catch (error) {
      throw Exception(error.message);
    }
  }
  ```

### 👍 Expected behavior

No error should occur when deleting MFA Authenticator

### 👎 Actual Behavior

it will return an error saying

```dart
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'String' is not a subtype of type 'Map<String, dynamic>'
#0      Account.deleteMfaAuthenticator (package:appwrite/services/account.dart:256:36)
<asynchronous suspension>
#1      MultiFactorAuthenticationDataSource.disableAuthenticatorApp (package:otoscopia/src/features/settings/data/datasources/multi_factor_authentication_data_source.dart:41:7)
<asynchronous suspension>
#2      _MfaWidgetState.build.<anonymous closure> (package:otoscopia/src/features/settings/presentation/widgets/profile/disable_mfa_widget.dart:41:19)
<asynchronous suspension>```

but it deletes the authenticator in the console. it just returns an error but proceed with the job

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Windows

### 🧱 Your Environment

Appwrite Version 1.5.4, Flutter SDK Version `appwrite: ^12.0.1`

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@laurencetroyv, thanks for creating this issue! 🙏🏼 It looks like we set the model to be user:

https://github.com/appwrite/appwrite/blob/2d8694baea9cc997ef0ace6a51d215849b46f11d/app/controllers/api/account.php#L3801

when it should be none like:

https://github.com/appwrite/appwrite/blob/2d8694baea9cc997ef0ace6a51d215849b46f11d/app/controllers/api/account.php#L435
