### ISSUE TITLE
🐛 Bug Report: Node SDK Fetch Fails Issues

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/appwrite#8311]
### 👟 Reproduction steps

When using a batch process like below (or even `listDocuments`), `Node SDK` often fails with timeouts and fetch failed - 
```js
// exact 60 items in here.
for (const [index, randomId] of randomIds.entries()) {
  try {
      const document = await databases.getDocument(
          databaseId,
          collectionId,
          randomId.toString(),
      );

      await updateDocument(document, index);
  } catch (error) {
      console.error(`Index: ${index + 1}, Identifier: ${randomId}, ${error}`);
  }
}
```

---
Error Cause -
```json
{"error":{"cause":{"code":"ETIMEDOUT"}}}
```

---
The same is pretty usable on Dart SDK (only tested this) and on local executions.
Sometimes a logic like `sleep`/`delay` is helpful but not always & is really not optimal as it can take upto minutes to update the documents where using something like `Promise.all` is pretty much under 10s.

### 👍 Expected behavior

No timeouts.

### 👎 Actual Behavior

Timeouts.

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ItzNotABug** [comment]
Update: I've found the cause for this which might be coming from `Node:20+` Runtime.
I tested the same logic on `Node:18`, `Node:19` and the same worked fine.

The problem seems to be coming from `DNS` logic that was changed on `Node:20`+ I think. I say this because I used a custom domain for the Server SDK Endpoint which was proxied through Cloudflare and that caused an issue.

---
Node:20 Specific Tests:
1. Main Domain => Pass
2. CNAME Domain **With** Cloudflare Proxy On => Fail
3. CNAME Domain **Without** Cloudflare Proxy On => Pass

Runtimes:
1. Node: 18 => Pass
2. Node: 19 => Pass
3. Node: 20 => Timeout Errors

**Comment by stnguyen90** [comment]
@ItzNotABug, whoa! Can you reproduce this with just node (specific version in the runtime) and not in an Appwrite Function?

**Comment by ItzNotABug** [comment]
> @ItzNotABug, whoa! Can you reproduce this with just node (specific version in the runtime) and not in an Appwrite Function?

I've tested on a self hosted instance with Functions. Usage via Server Side SDK on a local machine works fine. Its just the function runtime acting out.

**Comment by ItzNotABug** [comment]
Update 2: I somehow also managed to get this on a local execution (via a `node misc.js`).

Trace -
```text
TypeError: fetch failed
at Object.fetch (node:internal/deps/undici/undici:11372:11)
at process.processTicksAndRejections (node: internal/process/task_queues:95:5)
at async _Client.call (file:///Users/itznotabug/ProjectName/node_modules/node-appwrite/dist/client.mjs:263:22)
at async Messaging.createSubscriber (file:///Users/itznotabug/ProjectName/node_modules/node-appwrite/dist/services/messaging.mjs:2083:12)
at async file:///Users/itznotabug/ProjectName/misc.js:17:17
at async Promise.all (index 277)
at async processUsers (file:///Users/itznotabug/ProjectName/misc.js:30:21)
at async file:///Users/itznotabug/ProjectName/misc.js:50:1
```

Node: `v20.9.0`

**Comment by stnguyen90** [comment]
@ItzNotABug, nice! Looks like you've narrowed down the problem to `v20.9.0`. Does it occur in the latest v20?

**Comment by ItzNotABug** [comment]
> @ItzNotABug, nice! Looks like you've narrowed down the problem to `v20.9.0`. Does it occur in the latest v20?

Haven't tested this on a `21` but I see that the functions use `FROM node:20.11-alpine3.19` so the error happens there too.

**Comment by Shadowfita** [comment]
I was also experiencing this issue with function runtime "node-20.0", and it seems to work fine with "node-21.0".
