### ISSUE TITLE
🐛 Bug Report: Read permission error on functions.getExecution polling for async function status

### ISSUE THREAD

**Issue by sonicviz** [appwrite/appwrite#8390]
### 👟 Reproduction steps

Discord support thread ref:
https://discord.com/channels/564160730845151244/1261111233646690427

Recommended method for async function call/completion from client is:
![image](https://github.com/user-attachments/assets/4c1f6ddf-f0a0-45ad-95bd-bc869f688cd0)

Basically I have the client create a document before the async function call, and pass the documentID through to the async function so it can save the response to it for later retrieval by the client.
So the async function is working properly (now I set the timeout properly!) and finishes with completed status, saving the AI response to the passed through documentID.
Issue now is the issue 1 above, on the client side, polling the function getExecution to determine the status so you can retrieve the saved response from the document and get back to the user. 
But it looks to be a permission issues. Polling code looks ok, but double checking

Calling functions.getExecution on the retrieved functionId from createExecution gives error:
pwriteException: User (role: guests) missing scope (execution.read)
    at Client.eval (webpack-internal:///./node_modules/appwrite/dist/esm/sdk.js:455:27)
    at Generator.next (<anonymous>)
    at fulfilled (webpack-internal:///./node_modules/appwrite/dist/esm/sdk.js:46:58)
    
    Even with any or guest permissions set on the function.

### 👍 Expected behavior

Polling functions.getExecution on the retrieved functionId should return function status 

### 👎 Actual Behavior

Calling functions.getExecution on the retrieved functionId from createExecution gives error:
pwriteException: User (role: guests) missing scope (execution.read)
    at Client.eval (webpack-internal:///./node_modules/appwrite/dist/esm/sdk.js:455:27)
    at Generator.next (<anonymous>)
    at fulfilled (webpack-internal:///./node_modules/appwrite/dist/esm/sdk.js:46:58)
    
    Even with any or guest permissions set on the function.
    
    Confirmed by darShan in Discord thread @ https://discord.com/channels/564160730845151244/1261111233646690427

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

Client     "appwrite": "^15.0.0",
    "node-appwrite": "^13.0.0",

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
A user is only able to get an execution they created. That means there must be a session so that a user can be given read permissions to the execution.

This is behaving as expected, but we will add documentation to make this clearer.
