### ISSUE TITLE
🐛 Bug Report: Migrations failed 1.5.7 -> 1.5.8

### ISSUE THREAD

**Issue by sysoppl** [appwrite/appwrite#8491]
### 👟 Reproduction steps

I updated appwrite from 1.5.7 to 1.5.8 using docker
```
docker run -it --rm     --volume /var/run/docker.sock:/var/run/docker.sock     --volume "$(pwd)"/appwrite:/usr/src/code/appwrite:rw     --entrypoint="upgrade"     appwrite/appwrite:1.5.8
```

and wanted to perform migrations, but an error occured

```
...
Running "docker compose up -d --remove-orphans --renew-anon-volumes"
Appwrite installed successfully

root@skyapi:~# cd appwrite/
root@skyapi:~/appwrite# docker-compose exec appwrite migrate

Fatal error: Uncaught Swoole\Error: API must be called in the coroutine in /usr/src/code/src/Appwrite/Platform/Tasks/Migrate.php:70
Stack trace:
#0 /usr/src/code/src/Appwrite/Platform/Tasks/Migrate.php(70): Redis->connect('redis', '6379', 3, NULL, 10)
#1 /usr/src/code/src/Appwrite/Platform/Tasks/Migrate.php(36): Appwrite\Platform\Tasks\Migrate->action('1.5.8', Object(Utopia\Database\Database), Object(Closure), Object(Utopia\Registry\Registry))
#2 /usr/src/code/vendor/utopia-php/cli/src/CLI/CLI.php(320): Appwrite\Platform\Tasks\Migrate->Appwrite\Platform\Tasks\{closure}('1.5.8', Object(Utopia\Database\Database), Object(Closure), Object(Utopia\Registry\Registry))
#3 /usr/src/code/app/cli.php(215): Utopia\CLI\CLI->run()
#4 {main}
  thrown in /usr/src/code/src/Appwrite/Platform/Tasks/Migrate.php on line 70
```

### 👍 Expected behavior

Migrations not failing

### 👎 Actual Behavior

Migrations not launching

### 🎲 Appwrite version

Version 1.5.8

### 💻 Operating system

Linux, Ubuntu 22.04 LTS

### 🧱 Your Environment

Docker

Doctor output
```
  __   ____  ____  _  _  ____  __  ____  ____     __  __  
 / _\ (  _ \(  _ \/ )( \(  _ \(  )(_  _)(  __)   (  )/  \ 
/    \ ) __/ ) __/\ /\ / )   / )(   )(   ) _)  _  )((  O )
\_/\_/(__)  (__)  (_/\_)(__\_)(__) (__) (____)(_)(__)\__/ 

👩‍⚕️ Running Appwrite Doctor for version 1.5.8 ...

[Settings]
🔴 Hostname has no public suffix (skyapi)
🟢 CNAME target has a public suffix (api.xxx.pl)
🟢 Using a unique secret key for encryption
🟢 App environment is set for production
🔴 Abuse protection is disabled
🟢 Console access limits are enabled
🔴 HTTPS force option is disabled
🔴 HTTPS force option is disabled for function domains
🔴 Logging adapter is disabled

[Connectivity]
🟢 Console.DB(console)...............................connected
🟢 Projects.DB(database_db_main).....................connected
🟢 Cache(cache_redis_main)...........................connected
🟢 Queue(queue)......................................connected
🟢 PubSub(pubsub)....................................connected
🔴 SMTP...........................................disconnected

[Volumes]
🟢 Uploads Volume is readable
🟢 Uploads Volume is writeable
🟢 Cache Volume is readable
🟢 Cache Volume is writeable
🟢 Config Volume is readable
🟢 Config Volume is writeable
🟢 Certs Volume is readable
🟢 Certs Volume is writeable

[Disk Space]
🟢 Uploads Volume has 97.61GB free space (27.24% used)
🟢 Cache Volume has 97.61GB free space (27.24% used)
🟢 Config Volume has 97.61GB free space (27.24% used)
🟢 Certs Volume has 97.61GB free space (27.24% used)

Failed to check for a newer version
```

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by nmbgeek** [comment]
Same experience.  Following for updates.
