### ISSUE TITLE
🐛 Bug Report: Cannot query database collection from inside function (missing scope)

### ISSUE THREAD

**Issue by ddekkers** [appwrite/appwrite#8614]
### 👟 Reproduction steps

- create a database collection and give it the following Access Permissions: ANY [write, read]
- Create an appwrite function that accesses the created database collection like so: 
```
const client = new Client();
client
  .setProject(APPWRITE_FUNCTION_PROJECT_ID)
  .setKey(req.headers['x-appwrite-key']);
const customers = await database.listDocuments(DATABASE_ID, CUSTOMERS_COLLECTION_ID)
```
- Execute function, e.g. via cli: 'appwrite functions create-execution --function-id=<FUNCTION_ID>`
- (error raises also when using manual execution via dashboard or fetching the api)

### 👍 Expected behavior

Function can query the database collection (which used to work until today)

### 👎 Actual Behavior

Error when accessing the database collection:
```
AppwriteException: app.PROJECT_ID@service.cloud.appwrite.io (role: applications) missing scope (documents.read)
    at _Client.call (/usr/local/server/src/function/node_modules/node-appwrite/dist/client.js:279:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Databases.listDocuments (/usr/local/server/src/function/node_modules/node-appwrite/dist/services/databases.js:1577:12)
```

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

Inside appwrite function: node-appwrite sdk (v14.0.0)
Invoking the function: appwrite-cli (v6.0.0)

**Please let me know if you need any further information. Thank you in advance! I appreciate your help ❤️**

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ddekkers** [comment]
The error indicates, that the function lacks read permissions for the collection. However the dashboard doesn't provide the option to set permissions for functions (or applications for that matter). Is that new in appwrite? (that would actually be great 😄)

**Comment by ddekkers** [comment]
Turns out I hadn't set the correct scopes inside the function settings.
