### ISSUE TITLE
🐛 Bug Report: Invalid URL

### ISSUE THREAD

**Issue by holoto** [appwrite/appwrite#8710]
### 👟 Reproduction steps

Running `appwrite login`

### 👍 Expected behavior

login error

### 👎 Actual Behavior

CLI Error:
```
TypeError: Invalid URL
    at new URL (node:internal/url:816:29)
    at Client.call (/usr/local/share/.config/yarn/global/node_modules/appwrite-cli/lib/client.js:149:17)
    at accountCreateEmailPasswordSession (/usr/local/share/.config/yarn/global/node_modules/appwrite-cli/lib/commands/account.js:1016:29)
    at loginCommand (/usr/local/share/.config/yarn/global/node_modules/appwrite-cli/lib/commands/generic.js:57:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
```

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

CLI version: 6.0.0
Operation System: Linux
Appwrite version: unknown
Is Cloud: No

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by byawitz** [comment]
Hi @holoto, thanks for opening the issue.

This bug is addressed here https://github.com/appwrite/sdk-generator/pull/984 and will be fixed in the next release of the Appwrite CLI.

For now, you can run the command as follows
```sh
 appwrite login --endpoint https://cloud.appwrite.io/v1
```

**Comment by holoto** [comment]
thank you
