### ISSUE TITLE
🐛 Bug Report: Attribute creation timed out.

### ISSUE THREAD

**Issue by DominikJoppa** [appwrite/appwrite#8729]
### 👟 Reproduction steps

Running `appwrite push`

### 👍 Expected behavior

I dont kwow.

### 👎 Actual Behavior

CLI Error:
```
Error: Attribute creation timed out.
    at createAttributes (/snapshot/sdk-for-cli/lib/commands/push.js:889:15)
    at async pushCollection (/snapshot/sdk-for-cli/lib/commands/push.js:1425:13)
    at async pushResources (/snapshot/sdk-for-cli/lib/commands/push.js:914:13)
```

### 🎲 Appwrite version

Appwrite Self-Hosted

### 💻 Operating system

MacOS

### 🧱 Your Environment

CLI version: 6.0.0
Operation System: Darwin
Appwrite version: 1.6.0
Is Cloud: No

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by byawitz** [comment]
Hi @DominikJoppa, thanks for opening the issue.

How many attributes and indexes are in your `appwrite.json` file?

Try to increase the number of retrying to `60` for example by running
```
appwrite push collection --attempts 60
```

**Comment by DH-555** [comment]
Is this still persisting?
