### ISSUE TITLE
🐛 Bug Report: creating documents with SDK does not work when  collection is created in cloud console

### ISSUE THREAD

**Issue by xpediteur** [appwrite/appwrite#8841]
### 👟 Reproduction steps

In every old collection (migration from my self hosted instance) I create a document with SDK, it works fine. With every new collection I create  in the cloud console, it does not work!  Can you pls verify this on your site? THX

### 👍 Expected behavior

document has to be written in the collection

### 👎 Actual Behavior

the document is not written in collection

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

MacOS

### 🧱 Your Environment

    "appwrite": "^16.0.2", WEB SDK

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by xpediteur** [comment]
console error message:
TypeError: Failed to fetch
    at Client.eval (webpack-internal:///./node_modules/appwrite/dist/esm/sdk.js:643:36)
    at Generator.next (<anonymous>)
    at eval (webpack-internal:///./node_modules/appwrite/dist/esm/sdk.js:47:71)
    at new Promise (<anonymous>)
    at __awaiter (webpack-internal:///./node_modules/appwrite/dist/esm/sdk.js:43:12)
    at Client.call (webpack-internal:///./node_modules/appwrite/dist/esm/sdk.js:640:16)
    at Databases.eval (webpack-internal:///./node_modules/appwrite/dist/esm/sdk.js:2400:38)
    at Generator.next (<anonymous>)
    at eval (webpack-internal:///./node_modules/appwrite/dist/esm/sdk.js:47:71)
    at new Promise (<anonymous>)

![Image](https://github.com/user-attachments/assets/9f2b241e-187b-4097-84f8-7aefb2c9c46b)

![Image](https://github.com/user-attachments/assets/fc94b920-8c2d-4f03-bce1-05d4aa50cee2)

**Comment by stnguyen90** [comment]
As discussed over [Discord](https://discord.com/channels/564160730845151244/1297584433318072371), something was wrong with the modal in your app.
