### ISSUE TITLE
🐛 Bug Report: Internal curl errors has occurred within the executor! Error Number: 52 Error Code: 500

### ISSUE THREAD

**Issue by sbhatm1213** [appwrite/appwrite#8907]
### 👟 Reproduction steps

I have a python function that works fine on my device. 
The same function does not work on Appwrite cloud.

I have set timeout to 900 second on the function. But function has always failed at around 32 to 34 seconds. [So it is not my timeout config issue]
I have given DB, Auth, etc permissions to the function
I have given ANY permissions on DB, so that the function can write to DB
Function starts, writes some data to DB [So it is not permission issue]. It fails somewhere in the middle giving this Internal curl errors

![Image](https://github.com/user-attachments/assets/d3009fcf-b70f-4854-bfc3-f9382c3c4cc1)

**_Internal curl errors has occurred within the executor! Error Number: 52
Error Code: 500_**

![Image](https://github.com/user-attachments/assets/b437fe3a-82cc-4fa3-94d8-6d40f86cd0fb)

### 👍 Expected behavior

Works well on my local device. So there is no issues with the code.

### 👎 Actual Behavior

**_Internal curl errors has occurred within the executor! Error Number: 52
Error Code: 500_**

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
The team is looking into this issue as we speak.

**Comment by eldadfux** [comment]
@sbhatm1213 after checking with the team, error 52 is because to a timeout. Looking at your response times it also makes sense.
It might be that the problem is in your function's code. Have you been able to get any successful execution? can you share your source code? 

In case the code is private, and you're on the pro plan, you can also contact email support through your console.

**Comment by sbhatm1213** [comment]
@eldadfux 
es, the code works fine on my device—no errors or timeouts. I've also raised a support request from the Appwrite Dashboard.

I plan to run much longer functions on Appwrite; this one is just a quick test and completes in under a minute.

**Comment by konavai** [comment]
I have the same issue multiple times today. Any idea when these are solved?

**Comment by ashar2001** [comment]
getting exactly the same issue. Kindly help me on that.

**Comment by ashar2001** [comment]
> getting exactly the same issue. Kindly help me on that.

@stnguyen90 could you please help me on how to disable gunicorn timeout in appwrite. I couldn't find anything there.

**Comment by loks0n** [comment]
This issue should be fixed with latest python runtime https://github.com/open-runtimes/open-runtimes/pull/330

If you aren't using cloud, you'll have to restart your openruntimes-executor containers to trigger the python runtime to redownload

**Comment by KillerLuk** [comment]
I find the result , it is OOM kill
![Image](https://github.com/user-attachments/assets/e300184e-19cf-4310-9049-87b1664ec7b1)

**Comment by cloudatlas9** [comment]
Getting the same error in just one specific function, but it shouldn't be a normal timeout issue since function timeout is set to  900 seconds. The function is doing some heavy, batched API fetches from the Meta API, not sure if it has to do anything with that. But no other logic in my app has this problem.

The Sentry error log (which is connected to Appwrite) says this:

`File /usr/src/code/src/Appwrite/Platform/Workers/Functions.php line 608`

```
#0 /usr/src/code/src/Appwrite/Platform/Workers/Functions.php(170): Appwrite\Platform\Workers\Functions->execute(Object(Utopia\Logger\Log), Object(Utopia\Database\Database), Object(Appwrite\Event\Func), Object(Appwrite\Event\Usage), Object(Appwrite\Event\Event), Object(Utopia\Database\Document), Object(Utopia\Database\Document), 'http', '/', 'POST', Array, '{"action":"conn...', Object(Utopia\Database\Document), 'eyJ0eXAiOiJKV1Q...', NULL, NULL, '678684f2e467915...') #1 /usr/src/code/src/Appwrite/Platform/Workers/Functions.php(50): Appwrite\Platform\Workers\Functions->action(Object(Utopia\Queue\Message), Object(Utopia\Database\Database), Object(Appwrite\Event\Func), Object(Appwrite\Event\Event), Object(Appwrite\Event\Usage), Object(Utopia\Logger\Log)) #2 /usr/src/code/vendor/utopia-php/queue/src/Queue/Server.php(248): Appwrite\Platform\Workers\Functions->Appwrite\Platform\Workers\{closure}(Object(Utopia\Queue\Message), Object(Utopia\Database\Database), Object(Appwrite\Event\Func), Object(Appwrite\Event\Event), Object(Appwrite\Event\Usage), Object(Utopia\Logger\Log)) #3 [internal function]: Utopia\Queue\Server->Utopia\Queue\{closure}('0') #4 /usr/src/code/vendor/utopia-php/queue/src/Queue/Adapter/Swoole.php(37): call_user_func(Object(Closure), '0') #5 [internal function]: Utopia\Queue\Adapter\Swoole->Utopia\Queue\Adapter\{closure}(Object(Swoole\Process\Pool), '0') #6 {main}
```

**Comment by sreehari156** [comment]
Internal curl error has occurred within the executor! Error Number: 52
Error Code: 500   on appwrite


my code is     const express = require('express');

const app = express();
const port=process.env.PORT || 3000;

// Basic route to test the function
app.get('/', (req, res) => {
  res.json({
    status: 'success',
    message: 'Hello, World from Appwrite Express function!',
  });
});

app.listen(port, () => {        
  console.log(`Server running on port ${port}`);
} );

**Comment by andre-felipe-wonsik-alves** [comment]
I'm running into the same problem with large file uploads in my cloud function, using Python 3.11. Did you manage to find a workaround or fix?

**Comment by loks0n** [comment]
> I'm running into the same problem with large file uploads in my cloud function, using Python 3.11. Did you manage to find a workaround or fix?

Most likely scenario is you are running out of memory in your function, or your function is crashing in some other way. We can improve the UX here, but probably the workaround for you will be profile and optimise your resource intensive function.

**Comment by andre-felipe-wonsik-alves** [comment]
Improving the UX will be a great quality-of-life enhancement (to be honest, I was a bit confused when I saw the error for the first time)! I’ll work on optimizing my function :) Thanks for the quick response!

**Comment by sysoppl** [comment]
I have found a workaround: in newest version of appwrite we are able to change CPU and memory in function settings, so I changed it to 8vcpu and 8gb, no more errors

<img width="866" height="325" alt="Image" src="https://github.com/user-attachments/assets/62389267-cd6d-4252-8288-786d1a56dec8" />

**Comment by andre-felipe-wonsik-alves** [comment]
Ooooh, that's really helpful! I think with that and the little optimizations I made to the function, everything will work. Thank you for the reply! :)
