### ISSUE TITLE
🐛 Bug Report: Cannot create a project using command line arguments: Param "name" is not optional.

### ISSUE THREAD

**Issue by berthou** [appwrite/appwrite#8935]
### 👟 Reproduction steps

Create a project from the CLI non-interactively using switches given by 'appwrite init project -h'

Running `appwrite init project --organization-id 64c3e7ea9900c00f47ef --project-id test --project-name test`

### 👍 Expected behavior

create a new project

### 👎 Actual Behavior

CLI Error:
```
Error: Param "name" is not optional.
    at Client.call (/opt/homebrew/Cellar/appwrite/6.1.0/libexec/lib/node_modules/appwrite-cli/lib/client.js:211:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async projectsCreate (/opt/homebrew/Cellar/appwrite/6.1.0/libexec/lib/node_modules/appwrite-cli/lib/commands/projects.js:154:16)
    at async initProject (/opt/homebrew/Cellar/appwrite/6.1.0/libexec/lib/node_modules/appwrite-cli/lib/commands/init.js:95:20)
```

If I add '--name test' I get
```
error: unknown option '--name'
```

### 🎲 Appwrite version

Version 1.6.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

CLI version: 6.1.0
Operation System: Darwin
Appwrite version: 1.6.0
Is Cloud: No

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by berthou** [comment]
the interactive version works fine

**Comment by bertramdesigns** [comment]
The workaround is to use the undocumented 'projects' (with s) command. [source file](https://github.com/appwrite/sdk-for-cli/blob/master/lib/commands/projects.js#L1906)

```bash
appwrite projects create --project-id PROJECT_ID --team-id ORG_ID --name PROJECT_NAME
```

## Some notes:
### --team-id
This is your organization ID. The fastest way to get it through the CLI is:
```bash
appwrite account get-prefs
```
### --project-id
Unlike `appwrite init project` you cannot pass unique() to generate a random ID. You will need to supply your own.
An imperfect copilot-generated script which can be directly copied into the terminal to replicate [id.js](https://github.com/appwrite/sdk-for-cli/blob/master/lib/id.js) is 
```zsh
hex_timestamp() {
    sec=$(date +%s)
    msec=$(date +%N | cut -c1-3)
    printf "%x%03x" "$sec" "$msec"
}

unique_id() {
    padding=${1:-7}
    base_id=$(hex_timestamp)
    random_padding=""
    for ((i = 0; i < padding; i++)); do
        random_hex_digit=$(printf "%x" $((RANDOM % 16)))
        random_padding+=$random_hex_digit
    done
    echo "$base_id$random_padding"
}

unique_id
```

**Comment by HarshMN2345** [comment]
CLI 27.3.0 correctly passes ``--project-name`` as the required name field, Closing this as fixed in the current CLI.
