### ISSUE TITLE
🐛 Bug Report: Attribute creation timed out.

### ISSUE THREAD

**Issue by LuisPeMoraRod** [appwrite/appwrite#8994]
### 👟 Reproduction steps

When running `appwrite push all` I got the `Error: Attribute creation timed out`

I was trying to duplicate a project into another one for testing and development purposes, using the method proposed by @byawitz in https://github.com/appwrite/appwrite/issues/366#issuecomment-2353455945

```
# Install appwrite
npm install -g appwrite

# Connect the client to your original project
appwrite client --projectId ORIGIN_PROJECT_ID --key APY_KEY

# Pull all resources from original project
appwrite pull all --force

# Connect the client to your destination project
appwrite client --projectId DEST_PROJECT_ID --key APY_KEY

# Push all resources to the destination project
appwrite push all --force
```

![Image](https://github.com/user-attachments/assets/37e1b853-3fff-4048-b331-75efa970b405)

### 👍 Expected behavior

Create the attributes of the specified collection

### 👎 Actual Behavior

CLI Error:
```
Error: Attribute creation timed out.
    at createAttributes (/home/luispedro/.nvm/versions/node/v18.18.2/lib/node_modules/appwrite-cli/lib/commands/push.js:889:15)
    at async pushCollection (/home/luispedro/.nvm/versions/node/v18.18.2/lib/node_modules/appwrite-cli/lib/commands/push.js:1425:13)
    at async pushResources (/home/luispedro/.nvm/versions/node/v18.18.2/lib/node_modules/appwrite-cli/lib/commands/push.js:907:13)
```

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

CLI version: 6.1.0
Operation System: Linux
Appwrite version: 1.6.0
Is Cloud: Yes

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by dhonig-weizmann** [comment]
Same thing here, on a Windows computer, with cloud hosted Appwrite. CLI version 6.0.0. Thank you
