### ISSUE TITLE
🐛 Bug Report: Param "name" is not optional.

### ISSUE THREAD

**Issue by kevinjosephjohn** [appwrite/appwrite#8999]
### 👟 Reproduction steps

Running `appwrite init project --organization-id 648ab2fb4856acfc1e30 --project-name testapp --project-id testname`. 

If I remove the --project-id argument then the cli proceeds to ask for the project id.

![Image](https://github.com/user-attachments/assets/8ecded81-311e-480f-8ab9-ddae513d814e)

### 👍 Expected behavior

It should create the project successfully. But I get the error "name" is not optional

### 👎 Actual Behavior

CLI Error:
```
Error: Param "name" is not optional.
    at Client.call (/Users/kevinjohn/.nvm/versions/node/v21.7.1/lib/node_modules/appwrite-cli/lib/client.js:211:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async projectsCreate (/Users/kevinjohn/.nvm/versions/node/v21.7.1/lib/node_modules/appwrite-cli/lib/commands/projects.js:154:16)
    at async initProject (/Users/kevinjohn/.nvm/versions/node/v21.7.1/lib/node_modules/appwrite-cli/lib/commands/init.js:96:20)
```

### 🎲 Appwrite version

Version 1.6.x

### 💻 Operating system

Linux

### 🧱 Your Environment

CLI version: 6.1.0
Operation System: Darwin
Appwrite version: 1.6.0
Is Cloud: No

Server is running on Linux, Appwrite CLI is running on MacOS 

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kevinjosephjohn** [comment]
Duplicate of 
https://github.com/appwrite/appwrite/issues/8935
Interactive version works fine but will be good to get this fixed.
