### ISSUE TITLE
🐛 Bug Report: Project with the requested ID could not be found. Please check the value of the X-Appwrite-Project header to ensure the correct project ID is being used.

### ISSUE THREAD

**Issue by spyshow** [appwrite/appwrite#9042]
### 👟 Reproduction steps

Running `appwrite pull`

### 👍 Expected behavior

it should pull the settings correctly 

### 👎 Actual Behavior

CLI Error:
```
Error: Project with the requested ID could not be found. Please check the value of the X-Appwrite-Project header to ensure the correct project ID is being used.
    at Client.call (C:\Users\jihad.kherfan\AppData\Roaming\npm\node_modules\appwrite-cli\lib\client.js:211:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async projectsGet (C:\Users\jihad.kherfan\AppData\Roaming\npm\node_modules\appwrite-cli\lib\commands\projects.js:185:16)
    at async pullSettings (C:\Users\jihad.kherfan\AppData\Roaming\npm\node_modules\appwrite-cli\lib\commands\pull.js:46:24)
    at async pullResources (C:\Users\jihad.kherfan\AppData\Roaming\npm\node_modules\appwrite-cli\lib\commands\pull.js:37:13)
```

I can pull functions but not the settings
this is the project ( id is :"radar")
![Image](https://github.com/user-attachments/assets/20bbc756-49ea-45db-b5b7-3f1dc62bf4d3)

### 🎲 Appwrite version

Version 1.6.x

### 💻 Operating system

Windows

### 🧱 Your Environment

CLI version: 6.1.0
Operation System: Windows_NT
Appwrite version: 1.6.0
Is Cloud: No

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by DH-555** [comment]
You mean the functions settings or the project settings?

**Comment by DH-555** [comment]
This is happening in the CLI? Do you have set the URL to your appwrite instance and logged in?

**Comment by spyshow** [comment]
yes in after make " appwrite init project" I choose existing project and as you can see in the attached photo the project linked successfully but it give this error when pulling the project settings

![Image](https://github.com/user-attachments/assets/a1dd4030-a2ef-4e2f-b201-3f204976f907)

**Comment by StephenHodgson** [comment]
also running into this issue

**Comment by StephenHodgson** [comment]
> but did you have set the endpoint in the CLI to your local instance URL?

I tried that as well. 
```
appwrite client --endpoint http://localhost/v1 --key your-secret-key --project-id  PROJECT_ID -ss true
```

**Comment by watzon** [comment]
This is definitely an issue with self hosted instances. I am getting the same thing through the CLI. Login is successful, it is able to list projects and resources, but upon trying to pull anything it gives the above error.

**Comment by watzon** [comment]
Update: this is specifically an issue on macOS it seems. At least for me. When I install the appwrite cli in an arch linux container it works fine.
