### ISSUE TITLE
🐛 Bug Report: 404 Collection not found

### ISSUE THREAD

**Issue by Tsukishima1** [appwrite/appwrite#9049]
### 👟 Reproduction steps

Hey, when I access https://cloud.appwrite.io/console/ my project shows “404 Collection not found” and the project is also unable to connect. Why is this happening? Everything was working fine an hour ago.
![Image](https://github.com/user-attachments/assets/c6b3a7b0-684f-407b-9fc8-1cfbcef6fffc)

### 👍 Expected behavior

/

### 👎 Actual Behavior

404 collection not found
![Image](https://github.com/user-attachments/assets/dfbe0617-4d42-4394-b9e1-25b29e0d5004)

error: 
AppwriteException: Collection not found
    at _Client.call (webpack-internal:///(rsc)/./node_modules/node-appwrite/dist/client.mjs:287:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Account.get (webpack-internal:///(rsc)/./node_modules/node-appwrite/dist/services/account.mjs:28:12)    
    at async eval (webpack-internal:///(rsc)/./src/lib/session-middleware.ts:28:18)
    at async dispatch (webpack-internal:///(rsc)/./node_modules/hono/dist/compose.js:34:17)
    at async eval (webpack-internal:///(rsc)/./node_modules/hono/dist/hono-base.js:209:25)
    at async D:\Study\MyProject\hara-projectie\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:55778
    at async eO.execute (D:\Study\MyProject\hara-projectie\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:46527)
    at async eO.handle (D:\Study\MyProject\hara-projectie\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:57112)
    at async doRender (D:\Study\MyProject\hara-projectie\node_modules\next\dist\server\base-server.js:1352:42)       
    at async cacheEntry.responseCache.get.routeKind (D:\Study\MyProject\hara-projectie\node_modules\next\dist\server\base-server.js:1562:40)
    at async DevServer.renderToResponseWithComponentsImpl (D:\Study\MyProject\hara-projectie\node_modules\next\dist\server\base-server.js:1482:28)
    at async DevServer.renderPageComponent (D:\Study\MyProject\hara-projectie\node_modules\next\dist\server\base-server.js:1908:24)
    at async DevServer.renderToResponseImpl (D:\Study\MyProject\hara-projectie\node_modules\next\dist\server\base-server.js:1946:32)
    at async DevServer.pipeImpl (D:\Study\MyProject\hara-projectie\node_modules\next\dist\server\base-server.js:921:25)
    at async NextNodeServer.handleCatchallRenderRequest (D:\Study\MyProject\hara-projectie\node_modules\next\dist\server\next-server.js:272:17)
    at async DevServer.handleRequestImpl (D:\Study\MyProject\hara-projectie\node_modules\next\dist\server\base-server.js:817:17)
    at async D:\Study\MyProject\hara-projectie\node_modules\next\dist\server\dev\next-dev-server.js:339:20
    at async Span.traceAsyncFn (D:\Study\MyProject\hara-projectie\node_modules\next\dist\trace\trace.js:154:20)      
    at async DevServer.handleRequest (D:\Study\MyProject\hara-projectie\node_modules\next\dist\server\dev\next-dev-server.js:336:24)
    at async invokeRender (D:\Study\MyProject\hara-projectie\node_modules\next\dist\server\lib\router-server.js:173:21)
    at async handleRequest (D:\Study\MyProject\hara-projectie\node_modules\next\dist\server\lib\router-server.js:350:24)
    at async requestHandlerImpl (D:\Study\MyProject\hara-projectie\node_modules\next\dist\server\lib\router-server.js:374:13)
    at async Server.requestListener (D:\Study\MyProject\hara-projectie\node_modules\next\dist\server\lib\start-server.js:141:13) {
  code: 404,
  type: 'collection_not_found',
  response: {
    message: 'Collection not found',
    code: 404,
    type: 'collection_not_found',
    version: '1.6.0'
  }
}

### 🎲 Appwrite version

Version 1.6.x

### 💻 Operating system

Windows

### 🧱 Your Environment

Appwrite 1.6.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by SJ22032003** [comment]
Today I was going to launch my app 😭 and this just suddenly ruined it.

**Comment by Tsukishima1** [comment]
> Today I was going to launch my app 😭 and this just suddenly ruined it.

Have you encountered this situation as well? This is really terrible...

**Comment by SJ22032003** [comment]
> > Today I was going to launch my app 😭 and this just suddenly ruined it.
> 
> Have you encountered this situation as well? This is really terrible...

They are working on it, but who knows how long it's going to take? Pretty sure there are way more people affected by it.

[Appwrite Status](https://status.appwrite.online/)

**Comment by arsh-meharwal** [comment]
Hey I got the same problem suddenly all my databases is unavailable

**Comment by pdas9647** [comment]
Hey, same issue with me as well. All the tabs (Auth, Databases, Functions, Messaging, Storage) 404 Collection not found for one of my projects (projectId: 672a5dc10020c2355959).
![Image](https://github.com/user-attachments/assets/fe680b76-5ee0-4549-8a24-3cd782f44b8f)
![Image](https://github.com/user-attachments/assets/64153aee-24ab-412f-bcc8-800e69160934)

**Comment by arsh-meharwal** [comment]
Is this once in a blue moon kind of situation? moreover what caused this outage external attacks or something? Just curious

**Comment by Tsukishima1** [comment]
> Is this once in a blue moon kind of situation? moreover what caused this outage external attacks or something? Just curious这是千载难逢的情况吗？此外，是什么原因导致这次中断的外部攻击或其他什么？只是好奇

Not sure either, but we can check the current progress of the fix on this website https://status.appwrite.online/incident/470403?mp=true .

**Comment by harshvardhan-anand** [comment]
I believe there was a production deployment, as everything was functioning until 11:30 IST. After that, my job listing tracker cron job, which monitors company career pages and sends notifications every 60 minutes, stopped working.

![Image](https://github.com/user-attachments/assets/199b7441-24ad-4a5e-8d06-ace975676d70)

**Comment by Yogeshthangm** [comment]
I have a client demo eveing but there is nothing in the server pls fix this ASAP. This is unaccetable

![Image](https://github.com/user-attachments/assets/b7930f92-2207-427d-9cc5-e6f375030cc0)

**Comment by masterthuku** [comment]
just launced my app today while coding only to realize all the collections in my project vanished.

![Image](https://github.com/user-attachments/assets/cabc186d-df48-48fa-8742-5877761caaf3)

**Comment by kinleyrabgay** [comment]
This is the status right now:
![Image](https://github.com/user-attachments/assets/af89ec73-aa61-4adc-9192-6065cbfb9415)

**Comment by Nurullah-Sadekin** [comment]
I am getting the same issue.
![Image](https://github.com/user-attachments/assets/9cd39b63-14c4-4d9b-a669-aa84f294d31e)

**Comment by arsh-meharwal** [comment]
I can see my data now ![Image](https://github.com/user-attachments/assets/a4a25d8c-ea17-4ee5-9e25-ad6515cb7e51)

**Comment by Yogeshthangm** [comment]
Yes Data restored now.

**Comment by omnandurkar** [comment]
i faced a similar issue when manually adding data to  the appwrite

**Comment by kristandere** [comment]
same issue as well, even with a pro plan with back up storage, restored the data and then still says collection not found. appwrite is not reliable at all

**Comment by Tsukishima1** [comment]
Is it not completely fixed??😟

**Comment by stnguyen90** [comment]
As mentioned previously, this was caused by an [incident](https://status.appwrite.online/incident/470403?mp=true). If you're still having issues, please create a support ticket in the Appwrite Console or a support post on [Discord](https://appwrite.io/discord).
