### ISSUE TITLE
losing Collections

### ISSUE THREAD

**Issue by kabyfunfit** [appwrite/appwrite#9114]
i have had 5 collections show up as 404 not found and I have lost all of the data in them? What is going on and will we be able to recover these collection? also what would be causing me to lose these?

![Image](https://github.com/user-attachments/assets/e2bd303f-ec20-4427-befe-e225d0dbf369)

**Comment by stnguyen90** [comment]
@kabyfunfit, thanks for creating this issue! 🙏 Would you please share:

1. Your project ID
2. Your database ID
3. Your collection IDs
4. When you created the collections
5. When you were last able to access your collections

**Comment by kabyfunfit** [comment]
the project id 66eece54000385eea8d3
the database id 66f2ec4f00053c36a3d0

i have am pitching my app to investors tomorrow so I have had to recreate the collections and I do not have the ids any more as I am trying to get this to work the way it did last week. 

i created these about a month ago and it seems they all are not functional.  

I am also having collection ids throw unauthorized error even though they are set up all with users having all permissions.

**Comment by kabyfunfit** [comment]
we are now getting this
Error creating Tournament Team: AppwriteException: The current user is not authorized to perform the requested action.
    at async createTeam (src\app\actions\createTeam.ts:47:4)
    at async (webpack://next/dist/src/server/app-render/action-handler.ts:881:24)
    at async handleAction (webpack://next/dist/src/server/app-render/action-handler.ts:617:4)
    at async renderToHTMLOrFlightImpl (webpack://next/dist/src/server/app-render/app-render.tsx:1310:34)
    at async doRender (node_modules\next\src\server\base-server.ts:2666:21)
    at async responseGenerator (node_modules\next\src\server\base-server.ts:3027:21)        
    at async DevServer.renderToResponseWithComponentsImpl (node_modules\next\src\server\base-server.ts:3039:23)
    at async DevServer.renderPageComponent (node_modules\next\src\server\base-server.ts:3597:15)
    at async DevServer.renderToResponseImpl (node_modules\next\src\server\base-server.ts:3659:23)
    at async DevServer.pipeImpl (node_modules\next\src\server\base-server.ts:1698:20)       
    at async NextNodeServer.handleCatchallRenderRequest (node_modules\next\src\server\next-server.ts:1034:6)
    at async DevServer.handleRequestImpl (node_modules\next\src\server\base-server.ts:1462:8)
    at async (node_modules\next\src\server\dev\next-dev-server.ts:514:13)
    at async Span.traceAsyncFn (node_modules\next\src\trace\trace.ts:143:13)
    at async DevServer.handleRequest (node_modules\next\src\server\dev\next-dev-server.ts:512:19)
    at async invokeRender (node_modules\next\src\server\lib\router-server.ts:284:10)        
    at async handleRequest (node_modules\next\src\server\lib\router-server.ts:530:15)       
    at async requestHandlerImpl (node_modules\next\src\server\lib\router-server.ts:576:6)   
    at async Server.requestListener (node_modules\next\src\server\lib\start-server.ts:146:6)  45 |     }
  46 |
> 47 |     await databases.createDocument(
     |    ^
  48 |       process.env.NEXT_PUBLIC_APPWRITE_DATABASE!,
  49 |       process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_TOURNAMENT_TEAMS!,
  50 |       ID.unique(), {
  code: 401,
  type: 'user_unauthorized',
  response: [Object]

this is for our

collection ID 6761c5cf00110bc211c1

this is the permissions as we have them set up now 

![Image](https://github.com/user-attachments/assets/b75470bc-732b-475e-95d2-2c0859c3cb47)


it seems to be only this collection that is having this issue at this time, but like the 404 on the 3 collection that i had to start over, we are afraid this will spread to other vital collections.

**Comment by fogelito** [comment]
@kabyfunfit Hey do you get the 404 error when trying to list the database collection or listing the attributes of a specific collection?

**Comment by kabyfunfit** [comment]
I get the 404 when the collection disappears. I have yet again lost a collection to be not found. 
![Image](https://github.com/user-attachments/assets/e3d37a2c-544b-43cd-8b45-a75363ae8217)
this is in every way shape and form in accessing the collection. it is not even in the appwrite console as you can see in the screenshot provide.

I have only deleted collection that are not found and created new ones because these are collection needed to run the app. as I don't have time to wait for someone to tell me "yup, your data is gone, I guess you should have paid us to back up your data".

**Comment by kabyfunfit** [comment]
As of this moment we have lost
collectionID's 
6761bbbd002a7696c3a2
6761c3f800254df9d997
since Friday

**Comment by kabyfunfit** [comment]
and now i am getting 500 error on the new collections I am trying to work with as I need this to be functioning tomorrow

![Image](https://github.com/user-attachments/assets/5a34761f-d179-45a2-92bf-c8b42ebfa7f4)

i certainly do apricate your toast telling me to upgrade to back up my data. I am very eager to subscribe to this quality product

**Comment by fogelito** [comment]
Both collections still exist in the system 
6761bbbd002a7696c3a2
6761c3f800254df9d997

Will try to see if I can help

**Comment by kabyfunfit** [comment]
That's because I haven't deleted them to show that they are empty.   I am
not having my relationship with the locations collection saying it can not
be found.

Should I be finding another database solution since this seems to be
crashing and I am clearly not a web developer qualified for your software?

**Comment by fogelito** [comment]
Yes I see you are using lots of relationship attribute, which seems to be make the problem in this case.

**Comment by kabyfunfit** [comment]
So does this mean that I should not be using relationships? or is it that I have these relationships and am deleting documents that have relationships?

**Comment by stnguyen90** [comment]
@kabyfunfit, relationships are experimental and should be used with care. The more relationship attributes and documents, the more performance problems you'll face that can lead to the 500 errors.
