### ISSUE TITLE
🐛 Bug Report: Issue with Session.fromMap: List<dynamic> is not a subtype of List<String>

### ISSUE THREAD

**Issue by HBFLEX** [appwrite/appwrite#9119]
### 👟 Reproduction steps

I am encountering a runtime error in my Flutter app when attempting to log in using the createEmailPasswordSession method from the Appwrite SDK. The error appears to be caused by a data type mismatch in the Session.fromMap method.

ERROR DETAILS
```
E/flutter (30738): [ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: type 'List<dynamic>' is not a subtype of type 'List<String>'
E/flutter (30738): #0      new Session.fromMap (package:appwrite/src/models/session.dart:152:31)
E/flutter (30738): #1      Account.createEmailPasswordSession (package:appwrite/services/account.dart:646:27)
E/flutter (30738): <asynchronous suspension>
```

### 👍 Expected behavior

The createEmailPasswordSession method should successfully create a session and return a Session object without any type mismatch errors. Specifically:

The Session.fromMap method should correctly parse the server response, ensuring all fields are mapped to their expected types, including List<String> fields.
The application should proceed without any runtime exceptions or crashes.

### 👎 Actual Behavior

- The error occurs when attempting to parse the session response.
- It seems that the Session.fromMap method expects a List<String> but is receiving a List<dynamic> from the Appwrite server. This causes the type mismatch and the subsequent crash.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

I am using the Appwrite Flutter SDK version [^13.0.0].

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@HBFLEX, thanks for raising this issue! 🙏🏼 This should be fixed as part of https://github.com/appwrite/sdk-generator/pull/1020

**Comment by HBFLEX** [comment]
Glad I could help 👍

**Comment by bigbott** [comment]
I am not sure is it worth opening a new issue, since something similar is going to be fixed. 

Problem: I followed https://appwrite.io/docs/quick-starts/flutter and got this exception: 

DartError: TypeError: Instance of 'JSArray<dynamic>': type 'List<dynamic>' is not a subtype of type 'List<String>'
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3  throw_
dart-sdk/lib/_internal/js_shared/lib/rti.dart 1405:3                         _failedAsCheck
dart-sdk/lib/_internal/js_shared/lib/rti.dart 1383:3                         _generalAsCheckImplementation
dart-sdk/lib/_internal/js_shared/lib/rti.dart 1278:30                        _installSpecializedAsCheck
packages/appwrite/src/models/user.dart 94:19                                 fromMap

and also similar from the Session.fromMap 

maybe you should update the above tutorial and mention downgrading to a major version.
