### ISSUE TITLE
🐛 Bug Report:  type 'List<dynamic>' is not a subtype of type 'List<String>'

### ISSUE THREAD

**Issue by Ibeenoch** [appwrite/appwrite#9123]
### 👟 Reproduction steps

when i called the account.create method to create a user

`   final user = await account.create(
              userId: ID.unique(),
              email: email.text,
              name: fullname.text,
              password: password.text,
            );
`
i got an error  type 'List<dynamic>' is not a subtype of type 'List<String>'
but when i check the appWrite console the email, name, and userId was created, but the password was not created ( but it was kept blank), even though when i print the password type, it return a type of String and it was not null. 

how could have went wrong:

here is my full code:

import 'dart:io';
import 'dart:ui';

import 'package:airlineticket/AppRoutes.dart';
import 'package:airlineticket/base/data/supabaseServices/imageUploads.dart';
import 'package:airlineticket/base/reuseables/media/App_Media.dart';
import 'package:airlineticket/base/reuseables/resources/countries.dart';
import 'package:airlineticket/base/reuseables/styles/App_styles.dart';
import 'package:appwrite/appwrite.dart';
import 'package:flutter/material.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:provider/provider.dart';

class Signup extends StatefulWidget {
  const Signup({super.key});

  @override
  State<Signup> createState() => _SignupState();
}

class _SignupState extends State<Signup> {
  final TextEditingController email = TextEditingController();
  final TextEditingController password = TextEditingController();
  final TextEditingController bio = TextEditingController();
  final TextEditingController fullname = TextEditingController();
  final TextEditingController address = TextEditingController();
  final TextEditingController country = TextEditingController();

  FocusNode email_f = FocusNode();
  FocusNode password_f = FocusNode();
  FocusNode bio_f = FocusNode();
  FocusNode fullname_f = FocusNode();
  FocusNode address_f = FocusNode();
  FocusNode country_f = FocusNode();

  bool isPasswordVisible = false;
  String? fullnameError;
  String? bioError;
  String? addressError;
  String? emailError;
  String? passwordError;
  String? countryError;
  String _selectedCountry = '';
  bool _isBottomSheetOpen = false;
  File? profileImg;

  @override
  void dispose() {
    email.dispose();
    password.dispose();
    bio.dispose();
    fullname.dispose();
    address.dispose();
    country.dispose();
    super.dispose();
  }

  // add event listener when email is focus
  @override
  void initState() {
    super.initState();

    email_f.addListener(() {
      if (!email_f.hasFocus) {
        validateEmail();
      }
    });
    password_f.addListener(() {
      if (!password_f.hasFocus) {
        validatePassword();
      }
    });

    fullname_f.addListener(() {
      if (!fullname_f.hasFocus) {
        validateFullname();
      }
    });

    bio_f.addListener(() {
      if (!bio_f.hasFocus) {
        validateBio();
      }
    });

    address_f.addListener(() {
      if (!address_f.hasFocus) {
        validateAddress();
      }
    });
  }

  void validateEmail() {
    final emailText = email.text.trim();
    if (emailText.isEmpty) {
      setState(() {
        emailError = 'Email is required';
      });
    } else if (!RegExp(r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$')
        .hasMatch(emailText)) {
      setState(() {
        emailError = 'Enter a valid email address';
      });
    } else {
      setState(() {
        emailError = null;
      });
    }
  }

  void validatePassword() {
    final passwordText = password.text;
    if (passwordText.isEmpty) {
      setState(() {
        passwordError = 'Password is required';
      });
    } else if (passwordText.length < 8) {
      setState(() {
        passwordError = 'Password Length is too Short';
      });
    } else {
      setState(() {
        passwordError = null;
      });
    }
  }

  void validateFullname() {
    final fullNameText = fullname.text;
    if (fullNameText.isEmpty) {
      setState(() {
        fullnameError = 'Full name is required';
      });
    } else {
      setState(() {
        fullnameError = null;
      });
    }
  }

  void validateAddress() {
    final addressText = address.text;
    if (addressText.isEmpty) {
      setState(() {
        addressError = 'Address is required';
      });
    } else {
      setState(() {
        addressError = null;
      });
    }
  }

  void validateBio() {
    final bioText = bio.text;
    if (bioText.isEmpty) {
      setState(() {
        bioError = 'bio is required';
      });
    } else {
      setState(() {
        bioError = null;
      });
    }
  }

  void _openBottomSheet(BuildContext context) async {
    setState(() {
      _isBottomSheetOpen = true;
    });
    final selectedCountry = await showModalBottomSheet<String>(
        context: context,
        isScrollControlled: true,
        shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.vertical(top: Radius.circular(16.r))),
        builder: (BuildContext context) {
          String? _currentSelectedCountry = _selectedCountry;
          return DraggableScrollableSheet(
              expand: false,
              builder: (_, scrollController) {
                return Container(
                  padding: EdgeInsets.all(16.w),
                  child: Column(
                    children: [
                      Text(
                        'Choose an option',
                        style: TextStyle(
                            color: AppStyles.textWhiteBlack(context),
                            fontSize: 12.sp),
                      ),
                      Expanded(
                          child: ListView.builder(
                              controller: scrollController,
                              itemCount: countries.length,
                              itemBuilder: (context, index) {
                                final country = countries[index];
                                return RadioListTile<String>(
                                    value: country,
                                    title: Text(country),
                                    groupValue: _currentSelectedCountry,
                                    onChanged: (String? value) {
                                      setState(() {
                                        _currentSelectedCountry = value;
                                      });

                                      Navigator.pop(context, value);
                                    });
                              }))
                    ],
                  ),
                );
              });
        });

    if (selectedCountry != null) {
      setState(() {
        _selectedCountry = selectedCountry;
      });
    }

    setState(() {
      _isBottomSheetOpen = false;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        Scaffold(
          appBar: AppBar(
            title: Text(
              'Sign Up',
              style: TextStyle(fontSize: 15.sp, fontWeight: FontWeight.bold),
            ),
            centerTitle: true,
            backgroundColor: AppStyles.defaultBackGroundColor(context),
          ),
          backgroundColor: AppStyles.defaultBackGroundColor(context),
          body: SafeArea(
              child: ListView(
            children: [
              Container(
                width: 250.w,
                child: SvgPicture.asset("assets/icons/spinster.svg"),
                height: 70.h,
              ), // load custom svg
              Padding(
                padding: EdgeInsets.symmetric(horizontal: 15.w),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    userProfile(),
                    SizedBox(
                      height: 15.h,
                    ),
                    inputs(
                        fullname,
                        fullname_f,
                        Icons.person,
                        true,
                        false,
                        'Enter your full name',
                        fullnameError != null ? true : false,
                        'FullName'),
                    if (fullnameError != null) errorMessage(fullnameError!),
                    SizedBox(
                      height: 15.h,
                    ),
                    inputs(
                        address,
                        address_f,
                        Icons.location_city,
                        true,
                        false,
                        'Enter your address',
                        addressError != null ? true : false,
                        'Address'),
                    if (addressError != null) errorMessage(addressError!),
                    SizedBox(
                      height: 15.h,
                    ),
                    inputs(
                        bio,
                        bio_f,
                        Icons.abc,
                        true,
                        false,
                        'Tell us about yourself',
                        bioError != null ? true : false,
                        'Bio'),
                    if (bioError != null) errorMessage(bioError!),
                    SizedBox(
                      height: 15.h,
                    ),
                    inputs(
                        email,
                        email_f,
                        Icons.email,
                        true,
                        false,
                        'Enter your email address',
                        emailError != null ? true : false,
                        'Email'),
                    if (emailError != null) errorMessage(emailError!),
                    SizedBox(
                      height: 15.h,
                    ),
                    inputs(
                        password,
                        password_f,
                        Icons.lock,
                        true,
                        true,
                        'Enter your password',
                        passwordError != null ? true : false,
                        'Password'),
                    if (passwordError != null) errorMessage(passwordError!),
                    SizedBox(
                      height: 15.h,
                    ),
                    selectCountry(context),
                    SizedBox(
                      height: 15.h,
                    ),
                    actionBtn(),
                    SizedBox(
                      height: 10.h,
                    ),
                    switchScreen(context)
                  ],
                ),
              )
            ],
          )),
        ),
        if (_isBottomSheetOpen)
          Positioned.fill(
              child: BackdropFilter(
            filter: ImageFilter.blur(sigmaX: 10, sigmaY: 10),
            child: Container(
              color: Colors.black.withOpacity(0.3),
            ),
          ))
      ],
    );
  }

  Widget userProfile() {
    return GestureDetector(
      onTap: () async {
        File img = await ImageStorage().uploadImage('gallery');
        setState(() {
          profileImg = img;
        });
      },
      child: Center(
        child: CircleAvatar(
            radius: 21.sp,
            backgroundColor: Colors.grey.shade200,
            child: profileImg == null
                ? Padding(
                    padding: const EdgeInsets.all(8),
                    child: CircleAvatar(
                      radius: 20.sp,
                      backgroundColor: Colors.grey.shade200,
                      child: Image(
                        image: AssetImage(AppMedia.user),
                        width: 20.sp,
                        height: 20.sp,
                        color: Colors.grey,
                      ),
                    ),
                  )
                : CircleAvatar(
                    radius: 20.sp,
                    backgroundColor: Colors.grey.shade200,
                    backgroundImage: Image.file(
                      profileImg!,
                      fit: BoxFit.contain,
                    ).image,
                  )),
      ),
    );
  }

  Widget switchScreen(BuildContext context) {
    return Padding(
      padding: EdgeInsets.only(left: 17.w, bottom: 15.h),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.start,
        children: [
          Text(
            'Already have an account?',
            style: TextStyle(
                fontWeight: FontWeight.normal,
                fontSize: 10.sp,
                color: AppStyles.textWhiteBlack(context)),
          ),
          SizedBox(
            width: 7.w,
          ),
          InkWell(
            onTap: () {
              Navigator.pushNamed(context, AppRoutes.loginScreen);
            },
            child: Text(
              'Log In',
              style: TextStyle(
                  fontWeight: FontWeight.normal,
                  fontSize: 11.sp,
                  color: AppStyles.cardBlueColor),
            ),
          ),
        ],
      ),
    );
  }

  Widget selectCountry(BuildContext context) {
    return Padding(
      padding: EdgeInsets.symmetric(horizontal: 3.w),
      child: Container(
        padding: EdgeInsets.symmetric(horizontal: 8, vertical: 8),
        decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(8.r),
            color: AppStyles.borderBackGroundColor(context)),
        child: Container(
          height: 45,
          decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(8.r),
              color: AppStyles.defaultBackGroundColor(context)),
          child: TextField(
            controller: country,
            readOnly: true,
            decoration: InputDecoration(
              contentPadding: EdgeInsets.symmetric(vertical: 8.h),
              hintText: _selectedCountry.length > 1
                  ? _selectedCountry
                  : 'Choose your country',
              hintStyle: const TextStyle(fontSize: 12, color: Colors.grey),
              prefixIcon: Icon(
                Icons.public,
                size: 12.sp,
              ),
              enabledBorder: InputBorder.none,
              border: InputBorder.none,
              focusedBorder: InputBorder.none,
            ),
            onTap: () => _openBottomSheet(context),
          ),
        ),
      ),
    );
  }

  Widget actionBtn() {
    final account = Provider.of<Account>(context);
    final storage = Provider.of<Storage>(context);
    final database = Provider.of<Databases>(context);
    return Padding(
      padding: EdgeInsets.symmetric(horizontal: 5.w),
      child: InkWell(
        onTap: () async {
          try {
            if (email.text.isEmpty || password.text.isEmpty) {
              print('Email or password cannot be empty');
              return;
            }
            String publicImgUrl = '';

            print('Step 1: Signing up the user');
            // Step 1: Sign up user using the Appwrite account service
            final user = await account.create(
              userId: ID.unique(),
              email: email.text,
              name: fullname.text,
              password: password.text,
            );

            print('User created successfully: ${user.toMap()}');
            final userId = user.$id;

            // Step 2: Upload profile image if provided
            print('User signed up successfully: ${user.$id}');

            print('Step 2: Uploading profile image');

            if (profileImg != null) {
              final uniqueId = DateTime.now().millisecondsSinceEpoch.toString();
              final bytes = await profileImg!.readAsBytes();
              final bucketId = dotenv.env["APPWRITE_BUCKETID"]!;
              final file = await storage.createFile(
                bucketId: bucketId,
                fileId: ID.unique(),
                file: InputFile.fromBytes(
                    bytes: bytes, filename: '$uniqueId-profile.png'),
              );
              publicImgUrl =
                  'https://cloud.appwrite.io/v1/storage/buckets/$bucketId/files/${file.$id}/view?project=${dotenv.env["APPWRITE_PROJECTID"]}';
            }

            print('Step 3: Saving user data to database');

            // Step 3: Save user data in database
            await database.createDocument(
              databaseId: dotenv.env["APPWRITE_DATABASEID"]!,
              collectionId: dotenv.env["APPWRITE_COLLECTID"]!,
              documentId: ID.unique(),
              data: {
                'userId': userId,
                'email': email.text,
                'bio': bio.text,
                'address': address.text,
                'fullname': fullname.text,
                'profile_img': publicImgUrl ??
                    'https://www.gravatar.com/avatar/00000000000000000000000000000000?d=mp&f=y',
              },
            );

            print('User data saved successfully to database');

            print('Step 4: Creating email/password session');

            // Step 4: Create email/password session
            await account.createEmailPasswordSession(
              email: email.text,
              password: password.text,
            );

            // Success message
            print('User signed up successfully');
          } catch (e, stackTrace) {
            print('Error during sign-up: $e');
            print('Stack trace: $stackTrace');
          }
        },
        child: Container(
          width: double.infinity,
          height: 50.h,
          padding: EdgeInsets.symmetric(
            horizontal: 10.w,
          ),
          decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(8.r),
              color: AppStyles.cardBlueColor),
          child: Center(
            child: Text(
              'Sign Up',
              style: TextStyle(
                  fontWeight: FontWeight.bold,
                  fontSize: 13.sp,
                  color: Colors.white),
            ),
          ),
        ),
      ),
    );
  }

  Widget errorMessage(String err) {
    return Padding(
      padding: EdgeInsets.only(left: 18.w, top: 1.h),
      child: Text(
        err,
        style: TextStyle(color: Colors.red, fontSize: 8.sp),
      ),
    );
  }

  Widget inputs(
    TextEditingController controller,
    FocusNode focus,
    IconData icon,
    bool showPrefixIcon,
    bool showSuffixIcon,
    String hintText,
    bool hasErr,
    String focusname,
  ) {
    return Container(
      decoration: BoxDecoration(
          color: AppStyles.borderBackGroundColor(context),
          borderRadius: BorderRadius.circular(10.r)),
      child: Padding(
        padding: EdgeInsets.symmetric(horizontal: 1.w),
        child: StatefulBuilder(builder: (context, setState) {
          focus.addListener(() {
            setState(() {});
          });

          return Container(
            padding:
                EdgeInsets.only(left: 6.w, bottom: 8.h, right: 8.w, top: 0.h),
            decoration: BoxDecoration(borderRadius: BorderRadius.circular(8.r)),
            child: Stack(children: [
              Padding(
                padding: EdgeInsets.only(top: 10.h),
                child: Container(
                  height: 45.h,
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(8.r),
                    color: AppStyles.defaultBackGroundColor(context),
                  ),
                  child: TextField(
                    controller: controller,
                    focusNode: focus,
                    obscureText: isPasswordVisible,
                    onChanged: (value) {
                      if (focusname == 'Email') {
                        validateEmail();
                      } else if (focusname == 'Password') {
                        validatePassword();
                      } else if (focusname == 'FullName') {
                        validateFullname();
                      } else if (focusname == 'Address') {
                        validateAddress();
                      } else if (focusname == 'Bio') {
                        validateBio();
                      } else {}
                    },
                    style: TextStyle(
                      fontSize: 12.sp,
                    ),
                    cursorColor: AppStyles.cardBlueColor,
                    decoration: InputDecoration(
                        hintText: focus.hasFocus ? '' : hintText,
                        hintStyle:
                            TextStyle(fontSize: 10.sp, color: Colors.grey),
                        contentPadding: EdgeInsets.symmetric(vertical: 9.h),
                        prefixIcon: showPrefixIcon
                            ? Icon(
                                icon,
                                size: 15.sp,
                                color: Colors.grey,
                              )
                            : null,
                        suffixIcon: showSuffixIcon
                            ? GestureDetector(
                                onTap: () {
                                  setState(() {
                                    isPasswordVisible = !isPasswordVisible;
                                  });
                                },
                                child: Icon(
                                  isPasswordVisible
                                      ? Icons.visibility
                                      : Icons.visibility_off,
                                  size: 15.sp,
                                  color: Colors.grey,
                                ),
                              )
                            : null,
                        enabledBorder: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(8.r),
                            borderSide: BorderSide(
                                color: hasErr
                                    ? Colors.red
                                    : AppStyles.borderlineColor(context))),
                        focusedBorder: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(8.r),
                            borderSide:
                                BorderSide(color: AppStyles.cardBlueColor))),
                    autofillHints: null,
                  ),
                ),
              ),
              (focus.hasFocus) // display the label overlapping the top border
                  ? Positioned(
                      top: 3.h,
                      left: 20.w,
                      child: Container(
                        decoration: BoxDecoration(
                            color: AppStyles.defaultBackGroundColor(context)),
                        child: Padding(
                          padding: EdgeInsets.symmetric(horizontal: 2.w),
                          child: Text(
                            focusname,
                            style: TextStyle(
                              fontSize: 8.sp,
                            ),
                          ),
                        ),
                      ),
                    )
                  : Container(),
            ]),
          );
        }),
      ),
    );
  }
}

### 👍 Expected behavior

it ought to seamlessly create a user

### 👎 Actual Behavior

it gave an error of  type 'List<dynamic>' is not a subtype of type 'List<String>'

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Aboidrees** [comment]
Same problem here.


`Self Hosted 1.6.0`


`pubspec.yaml`
```
....
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.24.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
...
  appwrite: ^13.0.0
....

```


```
[log] Error during authentication: Unexpected error: Exception(message: type 'List<dynamic>' is not a subtype of type 'List<String>', stackTrace: #0      new Session.fromMap (package:appwrite/src/models/session.dart:152:31)
      #1      Account.getSession (package:appwrite/services/account.dart:796:27)
account.dart:796
      <asynchronous suspension>
      #2      AccountRemoteDataSource.getCurrentUser (package:hodhod/features/account/data/sources/remote/account_remote_data_source.dart:89:23)
account_remote_data_source.dart:89
      <asynchronous suspension>
      #3      AccountRepositoryImpl.getCurrentUser (package:hodhod/features/account/data/repositories/account_repository.dart:46:22)
account_repository.dart:46
      <asynchronous suspension>
      #4      AuthStateNotifier._init (package:hodhod/features/account/presentation/controller/auth_controller.dart:23:20)
auth_controller.dart:23
      <asynchronous suspension>
      )
```


```
   Future<User> getCurrentUser() async {
    // check there are sessions
    try {
      final session = await account.getSession(sessionId: "current");
      if (session.userId.isEmpty) {
        throw ServerException(message: "No sessions found");
      } else {
        return await account.get();
      }
    } on AppwriteException catch (e, s) {
      if (e.code == 401) {
        throw ServerException(message: "Unauthorized");
      }
      throw ServerException(message: e.message ?? "Unknown error", stackTrace: s);
    } catch (e, s) {
      throw ServerException(message: e.toString(), stackTrace: s);
    }
  }

```



```
[log] Error getting sessions:
[log] _TypeError (type 'List<dynamic>' is not a subtype of type 'List<String>')
[log] #0      new Session.fromMap (package:appwrite/src/models/session.dart:152:31)
      #1      Account.getSession (package:appwrite/services/account.dart:796:27)
account.dart:796
      <asynchronous suspension>
      #2      AccountRemoteDataSource.login (package:hodhod/features/account/data/sources/remote/account_remote_data_source.dart:59:31)
account_remote_data_source.dart:59
      <asynchronous suspension>
      #3      AccountRepositoryImpl.login (package:hodhod/features/account/data/repositories/account_repository.dart:68:22)
account_repository.dart:68
      <asynchronous suspension>
      #4      AuthStateNotifier.login (package:hodhod/features/account/presentation/controller/auth_controller.dart:40:7)
auth_controller.dart:40
      <asynchronous suspension>
      #5      LoginScreen.build.<anonymous closure> (package:hodhod/features/account/presentation/screens/login_screen.dart:95:31)
login_screen.dart:95
      <asynchronous suspension>
```


```
 Future<User> login(String email, String password) async {
    bool isSessionEmpty = false;

    try {
      final Session session = await account.getSession(sessionId: "current");
      isSessionEmpty = session.userId.isEmpty;
    } catch (e, s) {
      log("Error getting sessions:", error: e, stackTrace: s);
      if (e is AppwriteException && e.code == 401) {
        isSessionEmpty = true;
      } else {
        throw ServerException(message: e.toString(), stackTrace: s);
      }
    }

    try {
      if (isSessionEmpty) {
        await account.createEmailPasswordSession(email: email, password: password);
      }
      return await account.get();
    } catch (e, s) {
      throw ServerException(message: e.toString(), stackTrace: s);
    }
  }
```

**Comment by lgLindstrom** [comment]
Hi,, I have the same problem.

**Comment by mudassir-jmi** [comment]
### Solution

The error `type 'List<dynamic>' is not a subtype of type 'List<String>'` occurs because a `List<dynamic>` is being passed where a `List<String>` is expected. To resolve this issue:

1. **Explicitly Cast List to `List<String>`**: Ensure that any `List<dynamic>` is cast to `List<String>`. For example:

   ```dart
   List<String> myList = (dynamicList as List).cast<String>();

Validate Input Types: Make sure that the variables passed into methods such as account.create() are indeed of the proper type. For instance, check out the password field and see that it's a String:

```

if password.text is! String {

  throw Exception('Password must be a String');
}

Debugging Null or Blank Password: The account.create() method needs a password that's not null nor blank. Implement validation of the password field to avoid it being blank

if (password.text.trim().isEmpty)
throw Exception('Password cannot be empty');
}

Ensure Correct Appwrite SDK Usage: Check the version of the appwrite SDK in your pubspec.yaml. If your SDK is outdated, upgrade it:

Correct Profile Image Upload (if nullable): Initialize the publicImgUrl, even if profileImg is null:

String publicImgUrl = 'https://www.gravatar.com/avatar/placeholder?d=mp';

Error Handling for Appwrite Operations: Enclose the account.create() call in a try-catch block and log extensive error messages for debugging purposes:

try {
final user = await account.create(
    userId: ID.unique(),
    email: email.text,
    name: fullname.text,
    password: password.text,
  );
} catch (e) {
  print('Error creating user: $e');
}

**Comment by lgLindstrom** [comment]
Thanks for a fast response, but,,

My call looks like this:
      var result = await account.create(
          userId: ID.unique(), email: email, password: password);

email and password are of type String.
name is not required as understand and left out (name or not, no
difference.)

The call (account.create) is not returning a User as expected instead a
dart Exception is thrown with error the message
 'List<dynamic>' is not a subtype of type 'List<String>'

if I for example provides a incorrect email address a AppwriteException is
thrown with explanation.

/mvh
/lg
_____________________________________________________
Lars-Göran Lindström
Consius AB
+46 70 190 23 30
***@***.***


Den ons 25 dec. 2024 kl 16:42 skrev Md Mudassir Akhter <
***@***.***>:

**Comment by lgLindstrom** [comment]
Finally I was able to setup VsCode to debug third party packages.

In the User model, this line cause the Exception.

`labels: map['labels'] ?? [],
`

**Comment by Aboidrees** [comment]
@lgLindstrom 
I found the solution here #9119 

I hardcode to version 13.0.0

update  `pubspec.yaml` 

```
...
  appwrite:  13.0.0
....
```

```
flutter pub clean
flutter pub cache clean
flutter pub get
```
